SPOOL C:\PCMSDATAPROD\12.LOG;
SET ECHO ON;
-- 12. new tables 
--------------------------------------------------------
--  DDL for Table USER_PREFERENCE
--------------------------------------------------------
-- Sequence
CREATE SEQUENCE PCMSDATAPROD.USER_PREFERENCE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999999999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

-- Table
CREATE TABLE PCMSDATAPROD.USER_PREFERENCE(	
    ID                          NUMBER(19, 0),
    NO_STAFF                     NUMBER(19, 0),
    USERNAME		            VARCHAR2(20 CHAR),
    KEY_PREFERENCE              VARCHAR2(100 CHAR),
    VALUE_PREFERENCE            VARCHAR2(2000 CHAR),
    USERNAME_CREATED            VARCHAR2(20 CHAR),
    DATE_CREATED                DATE,
    USERNAME_LAST_MODIFIED      VARCHAR2(20 CHAR),
    DATE_LAST_MODIFIED          DATE,
    CONSTRAINT USER_PREFERENCE_PK PRIMARY KEY(ID) ENABLE
);

-- Constraints
ALTER TABLE PCMSDATAPROD.USER_PREFERENCE MODIFY (NO_STAFF NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.USER_PREFERENCE MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.USER_PREFERENCE MODIFY (KEY_PREFERENCE NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.USER_PREFERENCE MODIFY (VALUE_PREFERENCE NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.USER_PREFERENCE MODIFY (USERNAME_CREATED NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.USER_PREFERENCE MODIFY (DATE_CREATED NOT NULL ENABLE);

--------------------------------------------------------
--  Grant privileges on tables & sequences
--------------------------------------------------------
/* GRANT PRIVILEGES ON TABLES */
BEGIN
   FOR r IN (SELECT owner, table_name FROM all_tables WHERE owner='PCMSDATAPROD') LOOP
      EXECUTE IMMEDIATE 'GRANT INSERT, SELECT, UPDATE, DELETE on '||r.owner||'.'||r.table_name||' to PCMSUSER_ROLE';
   END LOOP;
END;
/
/*
BEGIN
   FOR r IN (SELECT owner, table_name FROM all_tables WHERE owner='PCMSDATAPROD') LOOP
      EXECUTE IMMEDIATE 'GRANT SELECT on '||r.owner||'.'||r.table_name||' to IMS_SUPPORT_ROLE_QS';
   END LOOP;
END;
/
*/

/* GRANT PRIVILEGES ON SEQUENCE */
BEGIN   
   FOR s IN (SELECT * FROM USER_SEQUENCES) LOOP
      EXECUTE IMMEDIATE 'GRANT select on ' || s.SEQUENCE_NAME || ' to PCMSUSER_ROLE';
   END LOOP;
END;
/
/*
BEGIN   
   FOR s IN (SELECT * FROM USER_SEQUENCES) LOOP
      EXECUTE IMMEDIATE 'GRANT select on ' || s.SEQUENCE_NAME || ' to IMS_SUPPORT_ROLE_QS';
   END LOOP;
END;
/
*/

SPOOL OFF;