SPOOL C:\2DROPTABLESEQ.LOG;
SET ECHO ON;
-- 2. Drop tables and sequences
BEGIN 
  FOR c IN (
    SELECT OBJECT_NAME FROM ALL_OBJECTS 
    WHERE OBJECT_TYPE = 'TABLE' 
    AND OWNER = 'PCMSDATAPROD' 
    AND OBJECT_NAME not like 'QS_%' 
    AND OBJECT_NAME not like 'QRTZ_%'
    )
    LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || c.OBJECT_NAME;
    END LOOP;
END;
/
BEGIN 
  FOR c IN (
    SELECT OBJECT_NAME FROM ALL_OBJECTS 
    WHERE OBJECT_TYPE = 'SEQUENCE' 
    AND OWNER = 'PCMSDATAPROD' 
    AND OBJECT_NAME not like 'QS_%'
	AND OBJECT_NAME != 'MAIN_CONTRACT_CERTIFICATE_SEQ'
    )
    LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || c.OBJECT_NAME;
    END LOOP;
END;
/
-- drop 13 unnecessary tables (originally have 47 tables)
drop table PCMSDATAPROD.QS_TERM;
drop table PCMSDATAPROD.QS_TERM_VARIANCES;
drop table PCMSDATAPROD.QS_FORECAST;
drop table PCMSDATAPROD.QS_OBJECT_SUBSIDIARY_RULE;
drop table PCMSDATAPROD.QS_MSG_BOARD_ATTACHMENT;
drop table PCMSDATAPROD.QS_MESSAGE_BOARD;

drop table PCMSDATAPROD.QS_BQITEM_CONTROL;
drop table PCMSDATAPROD.QS_RESOURCE_CONTROL;
drop table PCMSDATAPROD.QS_BQRESOURCE_SUMMARY_CONTROL;
drop table PCMSDATAPROD.QS_SCPACKAGE_CONTROL;
drop table PCMSDATAPROD.QS_SC_DETAILS_CONTROL;
drop table PCMSDATAPROD.QS_SCPAYMENT_CERT_CONTROL;
drop table PCMSDATAPROD.QS_SCPAYMENT_DETAIL_CONTROL;
--34 tables starting with 'QS_*' remaining
select count(*) from SYS.ALL_TABLES where OWNER = 'PCMSDATAPROD' and TABLE_NAME like 'QS%';
--11 tables starting with 'QRTZ_*' remaining
select count(*) from SYS.ALL_TABLES where 
OWNER = 'PCMSDATAPROD' and TABLE_NAME like 'QRTZ%';

-- drop 12 unncessary sequences (originally have 38 sequences)
drop sequence PCMSDATAPROD.QS_TERM_VARIANCES_SEQ;
drop sequence PCMSDATAPROD.QS_FORECAST_SEQ;
drop sequence PCMSDATAPROD.QS_OBJECT_SUBSIDIARY_RULE_SEQ;
drop sequence PCMSDATAPROD.QS_MSG_ATTACH_SEQ;
drop sequence PCMSDATAPROD.QS_MESSAGE_BOARD_SEQ;

drop sequence PCMSDATAPROD.QS_BQITEM_CONTROL_SEQ;
drop sequence PCMSDATAPROD.QS_RESOURCE_CONTROL_SEQ;
drop sequence PCMSDATAPROD.QS_BQRESOURCE_SUMMARY_CTL_SEQ;
drop sequence PCMSDATAPROD.QS_SC_PACKAGE_CONTROL_SEQ;
drop sequence PCMSDATAPROD.QS_SC_DETAILS_CONTROL_SEQ;
drop sequence PCMSDATAPROD.QS_SC_PAYMENT_CERT_CONTROL_SEQ;
drop sequence PCMSDATAPROD.QS_SC_PAYMENT_DETAIL_CTL_SEQ;
-- 26 sequences remaining -- 28 
select count(*) from SYS.ALL_SEQUENCES 
where SEQUENCE_OWNER = 'PCMSDATAPROD' or SEQUENCE_NAME = 'MAIN_CONTRACT_CERTIFICATE_SEQ'

SPOOL OFF;