package com.gammon.pcms.model;
// Generated Jun 14, 2016 11:29:35 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.hibernate.envers.AuditOverride;
import org.hibernate.envers.Audited;

import com.gammon.pcms.application.PcmsPersistedAuditObject;

/**
 * AddendumDetail generated by hbm2java
 */
@Audited
@AuditOverride(forClass = PcmsPersistedAuditObject.class)
@Entity
@DynamicUpdate
@SelectBeforeUpdate
@Table(name = "ADDENDUM_DETAIL")
@SequenceGenerator(name = "ADDENDUM_DETAIL_GEN", sequenceName = "ADDENDUM_DETAIL_SEQ", allocationSize = 1)
public class AddendumDetail extends PcmsPersistedAuditObject {

	private static final long serialVersionUID = -844399764451138531L;

	public static enum TYPE_HD {
		HEADER, DETAIL
	}
	
	public static enum TYPE_ACTION {
		ADD, UPDATE, DELETE
	}

	private BigDecimal id;
	private Addendum idAddendum;
	private String noJob;
	private String noSubcontract;
	private long no;
	private String typeHd;
	private String typeVo;
	private String bpi;
	private String description;
	private BigDecimal quantity;
	private BigDecimal rateAddendum;
	private BigDecimal amtAddendum;
	private BigDecimal rateBudget;
	private BigDecimal amtBudget;
	private BigDecimal quantityTba;
	private BigDecimal rateAddendumTba;
	private BigDecimal amtAddendumTba;
	private BigDecimal rateBudgetTba;
	private BigDecimal amtBudgetTba;
	private String codeObject;
	private String codeSubsidiary;
	private String unit;
	private String remarks;
	private BigDecimal idHeaderRef;
	private String codeObjectForDaywork;
	private String noSubcontractChargedRef;
	private String typeAction; //ADD, UPDATE, DELETE
	private BigDecimal idResourceSummary; //ADD, UPDATE, DELETE
	
	public AddendumDetail() {
	}

	public AddendumDetail(BigDecimal id, Addendum idAddendum, String noJob, String noSubcontract, long no,
			String typeHd, String typeVo, String usernameCreated, Date dateCreated) {
		this.id = id;
		this.idAddendum = idAddendum;
		this.noJob = noJob;
		this.noSubcontract = noSubcontract;
		this.no = no;
		this.typeHd = typeHd;
		this.typeVo = typeVo;
		this.usernameCreated = usernameCreated;
		this.dateCreated = dateCreated;
	}

	public AddendumDetail(BigDecimal id, Addendum idAddendum, String noJob, String noSubcontract, long no,
			String typeHd, String typeVo, String bpi, String description, BigDecimal quantity, BigDecimal rateAddendum,
			BigDecimal amtAddendum, BigDecimal rateBudget, BigDecimal amtBudget, BigDecimal quantityTba,
			BigDecimal rateAddendumTba, BigDecimal amtAddendumTba, BigDecimal rateBudgetTba, BigDecimal amtBudgetTba,
			String codeObject, String codeSubsidiary, String unit, String remarks, String usernameCreated,
			Date dateCreated, String usernameLastModified, Date dateLastModified, BigDecimal idHeaderRef) {
		this.id = id;
		this.idAddendum = idAddendum;
		this.noJob = noJob;
		this.noSubcontract = noSubcontract;
		this.no = no;
		this.typeHd = typeHd;
		this.typeVo = typeVo;
		this.bpi = bpi;
		this.description = description;
		this.quantity = quantity;
		this.rateAddendum = rateAddendum;
		this.amtAddendum = amtAddendum;
		this.rateBudget = rateBudget;
		this.amtBudget = amtBudget;
		this.quantityTba = quantityTba;
		this.rateAddendumTba = rateAddendumTba;
		this.amtAddendumTba = amtAddendumTba;
		this.rateBudgetTba = rateBudgetTba;
		this.amtBudgetTba = amtBudgetTba;
		this.codeObject = codeObject;
		this.codeSubsidiary = codeSubsidiary;
		this.unit = unit;
		this.remarks = remarks;
		this.usernameCreated = usernameCreated;
		this.dateCreated = dateCreated;
		this.usernameLastModified = usernameLastModified;
		this.dateLastModified = dateLastModified;
		this.idHeaderRef = idHeaderRef;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ADDENDUM_DETAIL_GEN")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "ID_ADDENDUM", nullable = false)
	public Addendum getIdAddendum() {
		return this.idAddendum;
	}

	public void setIdAddendum(Addendum idAddendum) {
		this.idAddendum = idAddendum;
	}

	@Column(name = "NO_JOB", nullable = false, length = 10)
	public String getNoJob() {
		return this.noJob;
	}

	public void setNoJob(String noJob) {
		this.noJob = noJob;
	}

	@Column(name = "NO_SUBCONTRACT", nullable = false, length = 8)
	public String getNoSubcontract() {
		return this.noSubcontract;
	}

	public void setNoSubcontract(String noSubcontract) {
		this.noSubcontract = noSubcontract;
	}

	@Column(name = "NO", nullable = false, precision = 10, scale = 0)
	public long getNo() {
		return this.no;
	}

	public void setNo(long no) {
		this.no = no;
	}

	@Column(name = "TYPE_HD", nullable = false, length = 20)
	public String getTypeHd() {
		return this.typeHd;
	}

	public void setTypeHd(String typeHd) {
		this.typeHd = typeHd;
	}

	@Column(name = "TYPE_VO", length = 4)
	public String getTypeVo() {
		return this.typeVo;
	}

	public void setTypeVo(String typeVo) {
		this.typeVo = typeVo;
	}

	@Column(name = "BPI", length = 510)
	public String getBpi() {
		return this.bpi;
	}

	public void setBpi(String bpi) {
		this.bpi = bpi;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "QUANTITY", scale = 4)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "RATE_ADDENDUM", scale = 4)
	public BigDecimal getRateAddendum() {
		return this.rateAddendum;
	}

	public void setRateAddendum(BigDecimal rateAddendum) {
		this.rateAddendum = rateAddendum;
	}

	@Column(name = "AMT_ADDENDUM")
	public BigDecimal getAmtAddendum() {
		return this.amtAddendum;
	}

	public void setAmtAddendum(BigDecimal amtAddendum) {
		this.amtAddendum = amtAddendum;
	}

	@Column(name = "RATE_BUDGET", scale = 4)
	public BigDecimal getRateBudget() {
		return this.rateBudget;
	}

	public void setRateBudget(BigDecimal rateBudget) {
		this.rateBudget = rateBudget;
	}

	@Column(name = "AMT_BUDGET")
	public BigDecimal getAmtBudget() {
		return this.amtBudget;
	}

	public void setAmtBudget(BigDecimal amtBudget) {
		this.amtBudget = amtBudget;
	}

	@Column(name = "QUANTITY_TBA", scale = 4)
	public BigDecimal getQuantityTba() {
		return this.quantityTba;
	}

	public void setQuantityTba(BigDecimal quantityTba) {
		this.quantityTba = quantityTba;
	}

	@Column(name = "RATE_ADDENDUM_TBA", scale = 4)
	public BigDecimal getRateAddendumTba() {
		return this.rateAddendumTba;
	}

	public void setRateAddendumTba(BigDecimal rateAddendumTba) {
		this.rateAddendumTba = rateAddendumTba;
	}

	@Column(name = "AMT_ADDENDUM_TBA")
	public BigDecimal getAmtAddendumTba() {
		return this.amtAddendumTba;
	}

	public void setAmtAddendumTba(BigDecimal amtAddendumTba) {
		this.amtAddendumTba = amtAddendumTba;
	}

	@Column(name = "RATE_BUDGET_TBA", scale = 4)
	public BigDecimal getRateBudgetTba() {
		return this.rateBudgetTba;
	}

	public void setRateBudgetTba(BigDecimal rateBudgetTba) {
		this.rateBudgetTba = rateBudgetTba;
	}

	@Column(name = "AMT_BUDGET_TBA")
	public BigDecimal getAmtBudgetTba() {
		return this.amtBudgetTba;
	}

	public void setAmtBudgetTba(BigDecimal amtBudgetTba) {
		this.amtBudgetTba = amtBudgetTba;
	}

	@Column(name = "CODE_OBJECT", length = 12)
	public String getCodeObject() {
		return this.codeObject;
	}

	public void setCodeObject(String codeObject) {
		this.codeObject = codeObject;
	}

	@Column(name = "CODE_SUBSIDIARY", length = 16)
	public String getCodeSubsidiary() {
		return this.codeSubsidiary;
	}

	public void setCodeSubsidiary(String codeSubsidiary) {
		this.codeSubsidiary = codeSubsidiary;
	}

	@Column(name = "UNIT", length = 20)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "REMARKS", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "ID_HEADER_REF", precision = 19, scale = 0)
	public BigDecimal getIdHeaderRef() {
		return this.idHeaderRef;
	}

	public void setIdHeaderRef(BigDecimal idHeaderRef) {
		this.idHeaderRef = idHeaderRef;
	}

	@Column(name = "NO_SUBCONTRACT_CHARGED_REF", length = 4)
	public String getNoSubcontractChargedRef() {
		return noSubcontractChargedRef;
	}

	public void setNoSubcontractChargedRef(String noSubcontractChargedRef) {
		this.noSubcontractChargedRef = noSubcontractChargedRef;
	}

	@Column(name = "CODE_OBJECT_FOR_DAYWORK", length = 6)
	public String getCodeObjectForDaywork() {
		return codeObjectForDaywork;
	}

	public void setCodeObjectForDaywork(String codeObjectForDaywork) {
		this.codeObjectForDaywork = codeObjectForDaywork;
	}

	@Column(name = "TYPE_ACTION", length = 10)
	public String getTypeAction() {
		return typeAction;
	}

	public void setTypeAction(String typeAction) {
		this.typeAction = typeAction;
	}
	
	@Column(name = "ID_RESOURCE_SUMMARY")
	public BigDecimal getIdResourceSummary() {
		return idResourceSummary;
	}

	public void setIdResourceSummary(BigDecimal idResourceSummary) {
		this.idResourceSummary = idResourceSummary;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AddendumDetail [id=" + id + ", idAddendum=" + idAddendum + ", noJob=" + noJob + ", noSubcontract="
				+ noSubcontract + ", no=" + no + ", typeHd=" + typeHd + ", typeVo=" + typeVo + ", bpi=" + bpi
				+ ", description=" + description + ", quantity=" + quantity + ", rateAddendum=" + rateAddendum
				+ ", amtAddendum=" + amtAddendum + ", rateBudget=" + rateBudget + ", amtBudget=" + amtBudget
				+ ", quantityTba=" + quantityTba + ", rateAddendumTba=" + rateAddendumTba + ", amtAddendumTba="
				+ amtAddendumTba + ", rateBudgetTba=" + rateBudgetTba + ", amtBudgetTba=" + amtBudgetTba
				+ ", codeObject=" + codeObject + ", codeSubsidiary=" + codeSubsidiary + ", unit=" + unit + ", remarks="
				+ remarks + ", idHeaderRef=" + idHeaderRef + "]";
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((amtAddendum == null) ? 0 : amtAddendum.hashCode());
		result = prime * result + ((amtAddendumTba == null) ? 0 : amtAddendumTba.hashCode());
		result = prime * result + ((amtBudget == null) ? 0 : amtBudget.hashCode());
		result = prime * result + ((amtBudgetTba == null) ? 0 : amtBudgetTba.hashCode());
		result = prime * result + ((bpi == null) ? 0 : bpi.hashCode());
		result = prime * result + ((codeObject == null) ? 0 : codeObject.hashCode());
		result = prime * result + ((codeSubsidiary == null) ? 0 : codeSubsidiary.hashCode());
		result = prime * result + ((description == null) ? 0 : description.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((idAddendum == null) ? 0 : idAddendum.hashCode());
		result = prime * result + ((idHeaderRef == null) ? 0 : idHeaderRef.hashCode());
		result = prime * result + (int) (no ^ (no >>> 32));
		result = prime * result + ((noJob == null) ? 0 : noJob.hashCode());
		result = prime * result + ((noSubcontract == null) ? 0 : noSubcontract.hashCode());
		result = prime * result + ((quantity == null) ? 0 : quantity.hashCode());
		result = prime * result + ((quantityTba == null) ? 0 : quantityTba.hashCode());
		result = prime * result + ((rateAddendum == null) ? 0 : rateAddendum.hashCode());
		result = prime * result + ((rateAddendumTba == null) ? 0 : rateAddendumTba.hashCode());
		result = prime * result + ((rateBudget == null) ? 0 : rateBudget.hashCode());
		result = prime * result + ((rateBudgetTba == null) ? 0 : rateBudgetTba.hashCode());
		result = prime * result + ((remarks == null) ? 0 : remarks.hashCode());
		result = prime * result + ((typeHd == null) ? 0 : typeHd.hashCode());
		result = prime * result + ((typeVo == null) ? 0 : typeVo.hashCode());
		result = prime * result + ((unit == null) ? 0 : unit.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		AddendumDetail other = (AddendumDetail) obj;
		if (amtAddendum == null) {
			if (other.amtAddendum != null)
				return false;
		} else if (!amtAddendum.equals(other.amtAddendum))
			return false;
		if (amtAddendumTba == null) {
			if (other.amtAddendumTba != null)
				return false;
		} else if (!amtAddendumTba.equals(other.amtAddendumTba))
			return false;
		if (amtBudget == null) {
			if (other.amtBudget != null)
				return false;
		} else if (!amtBudget.equals(other.amtBudget))
			return false;
		if (amtBudgetTba == null) {
			if (other.amtBudgetTba != null)
				return false;
		} else if (!amtBudgetTba.equals(other.amtBudgetTba))
			return false;
		if (bpi == null) {
			if (other.bpi != null)
				return false;
		} else if (!bpi.equals(other.bpi))
			return false;
		if (codeObject == null) {
			if (other.codeObject != null)
				return false;
		} else if (!codeObject.equals(other.codeObject))
			return false;
		if (codeSubsidiary == null) {
			if (other.codeSubsidiary != null)
				return false;
		} else if (!codeSubsidiary.equals(other.codeSubsidiary))
			return false;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (idAddendum == null) {
			if (other.idAddendum != null)
				return false;
		} else if (!idAddendum.equals(other.idAddendum))
			return false;
		if (idHeaderRef == null) {
			if (other.idHeaderRef != null)
				return false;
		} else if (!idHeaderRef.equals(other.idHeaderRef))
			return false;
		if (no != other.no)
			return false;
		if (noJob == null) {
			if (other.noJob != null)
				return false;
		} else if (!noJob.equals(other.noJob))
			return false;
		if (noSubcontract == null) {
			if (other.noSubcontract != null)
				return false;
		} else if (!noSubcontract.equals(other.noSubcontract))
			return false;
		if (quantity == null) {
			if (other.quantity != null)
				return false;
		} else if (!quantity.equals(other.quantity))
			return false;
		if (quantityTba == null) {
			if (other.quantityTba != null)
				return false;
		} else if (!quantityTba.equals(other.quantityTba))
			return false;
		if (rateAddendum == null) {
			if (other.rateAddendum != null)
				return false;
		} else if (!rateAddendum.equals(other.rateAddendum))
			return false;
		if (rateAddendumTba == null) {
			if (other.rateAddendumTba != null)
				return false;
		} else if (!rateAddendumTba.equals(other.rateAddendumTba))
			return false;
		if (rateBudget == null) {
			if (other.rateBudget != null)
				return false;
		} else if (!rateBudget.equals(other.rateBudget))
			return false;
		if (rateBudgetTba == null) {
			if (other.rateBudgetTba != null)
				return false;
		} else if (!rateBudgetTba.equals(other.rateBudgetTba))
			return false;
		if (remarks == null) {
			if (other.remarks != null)
				return false;
		} else if (!remarks.equals(other.remarks))
			return false;
		if (typeHd == null) {
			if (other.typeHd != null)
				return false;
		} else if (!typeHd.equals(other.typeHd))
			return false;
		if (typeVo == null) {
			if (other.typeVo != null)
				return false;
		} else if (!typeVo.equals(other.typeVo))
			return false;
		if (unit == null) {
			if (other.unit != null)
				return false;
		} else if (!unit.equals(other.unit))
			return false;
		return true;
	}

	


}
