--02.1 copy ATTACH_MAIN_CERT
insert into PCMSDATAPROD.ATTACHMENT (
ID,
ID_TABLE,
NAME_TABLE,
NO_SEQUENCE,
TYPE_DOCUMENT,
NAME_FILE,
PATH_FILE,
TEXT,
USERNAME_CREATED,
DATE_CREATED,
USERNAME_LAST_MODIFIED,
DATE_LAST_MODIFIED
)
(select
PCMSDATAPROD.ATTACHMENT_SEQ.nextval as ID,
attach.MAIN_CERT_ID as ID_TABLE,
'MAIN_CERT' as NAME_TABLE,
attach.SEQUENCENO as NO_SEQUENCE,
attach.DOCUMENTTYPE as TYPE_DOCUMENT,
attach.FILENAME as NAME_FILE,
attach.FILELINK as PATH_FILE,
attach.TEXTATTACHMENT as TEXT,
attach.CREATED_USER as USERNAME_CREATED,
attach.CREATED_DATE as DATE_CREATED,
attach.LAST_MODIFIED_USER as USERNAME_LAST_MODIFIED,
attach.LAST_MODIFIED_DATE as DATE_LAST_MODIFIED
from PCMSDATAPROD.ATTACH_MAIN_CERT attach
where attach.SYSTEM_STATUS = 'ACTIVE'
);

--02.2 copy ATTACH_PAYMENT
insert into PCMSDATAPROD.ATTACHMENT (
ID,
ID_TABLE,
NAME_TABLE,
NO_SEQUENCE,
TYPE_DOCUMENT,
NAME_FILE,
PATH_FILE,
TEXT,
USERNAME_CREATED,
DATE_CREATED,
USERNAME_LAST_MODIFIED,
DATE_LAST_MODIFIED
)
(select
PCMSDATAPROD.ATTACHMENT_SEQ.nextval as ID,
attach.PAYMENT_CERT_ID as ID_TABLE,
'PAYMENT' as NAME_TABLE,
attach.SEQUENCENO as NO_SEQUENCE,
attach.DOCUMENTTYPE as TYPE_DOCUMENT,
attach.FILENAME as NAME_FILE,
attach.FILELINK as PATH_FILE,
attach.TEXTATTACHMENT as TEXT,
attach.CREATED_USER as USERNAME_CREATED,
attach.CREATED_DATE as DATE_CREATED,
attach.LAST_MODIFIED_USER as USERNAME_LAST_MODIFIED,
attach.LAST_MODIFIED_DATE as DATE_LAST_MODIFIED
from PCMSDATAPROD.ATTACH_PAYMENT attach
where attach.SYSTEM_STATUS = 'ACTIVE'
);

--02.3 copy ATTACH_REPACKAGING
insert into PCMSDATAPROD.ATTACHMENT (
ID,
ID_TABLE,
NAME_TABLE,
NO_SEQUENCE,
TYPE_DOCUMENT,
NAME_FILE,
PATH_FILE,
TEXT,
USERNAME_CREATED,
DATE_CREATED,
USERNAME_LAST_MODIFIED,
DATE_LAST_MODIFIED
)
(select
PCMSDATAPROD.ATTACHMENT_SEQ.nextval as ID,
attach.REPACKAGING_ID as ID_TABLE,
'REPACKAGING' as NAME_TABLE,
attach.SEQUENCENO as NO_SEQUENCE,
attach.DOCUMENTTYPE as TYPE_DOCUMENT,
attach.FILENAME as NAME_FILE,
attach.FILELINK as PATH_FILE,
attach.TEXTATTACHMENT as TEXT,
attach.CREATED_USER as USERNAME_CREATED,
attach.CREATED_DATE as DATE_CREATED,
attach.LAST_MODIFIED_USER as USERNAME_LAST_MODIFIED,
attach.LAST_MODIFIED_DATE as DATE_LAST_MODIFIED
from PCMSDATAPROD.ATTACH_REPACKAGING attach
where attach.SYSTEM_STATUS = 'ACTIVE'
);

--02.4 copy ATTACH_SUBCONTRACT
insert into PCMSDATAPROD.ATTACHMENT (
ID,
ID_TABLE,
NAME_TABLE,
NO_SEQUENCE,
TYPE_DOCUMENT,
NAME_FILE,
PATH_FILE,
TEXT,
USERNAME_CREATED,
DATE_CREATED,
USERNAME_LAST_MODIFIED,
DATE_LAST_MODIFIED
)
(select
PCMSDATAPROD.ATTACHMENT_SEQ.nextval as ID,
attach.SUBCONTRACT_ID as ID_TABLE,
'SUBCONTRACT' as NAME_TABLE,
attach.SEQUENCENO as NO_SEQUENCE,
attach.DOCUMENTTYPE as TYPE_DOCUMENT,
attach.FILENAME as NAME_FILE,
attach.FILELINK as PATH_FILE,
attach.TEXTATTACHMENT as TEXT,
attach.CREATED_USER as USERNAME_CREATED,
attach.CREATED_DATE as DATE_CREATED,
attach.LAST_MODIFIED_USER as USERNAME_LAST_MODIFIED,
attach.LAST_MODIFIED_DATE as DATE_LAST_MODIFIED
from PCMSDATAPROD.ATTACH_SUBCONTRACT attach
where attach.SYSTEM_STATUS = 'ACTIVE'
);

