--drop 5 table
drop table PCMSDATAPROD.ATTACH_MAIN_CERT;
drop table PCMSDATAPROD.ATTACH_PAYMENT;
drop table PCMSDATAPROD.ATTACH_REPACKAGING;
drop table PCMSDATAPROD.ATTACH_SUBCONTRACT;
drop table PCMSDATAPROD.ATTACH_SUBCONTRACT_DETAIL;