package com.gammon.pcms.model.adl.id;
// Generated Jun 21, 2016 2:04:43 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.gammon.pcms.model.adl.AccountMaster;

/**
 * AccountBalanceId generated by hbm2java
 */

public class AccountBalanceId implements Serializable {

	private static final long serialVersionUID = -6209048153370339914L;
	private AccountMaster accountMaster;
	private BigDecimal fiscalYear;
	private String accountTypeLedger;

	public AccountBalanceId() {

	}

	public AccountBalanceId(AccountMaster accountMaster,
							BigDecimal fiscalYear,
							String accountTypeLedger) {
		super();
		this.accountMaster = accountMaster;
		this.fiscalYear = fiscalYear;
		this.accountTypeLedger = accountTypeLedger;
	}

	@ManyToOne
	@JoinColumn(name = "ACCOUNT_CODE_KEY",
				nullable = false)
	public AccountMaster getAccountMaster() {
		return this.accountMaster;
	}

	public void setAccountMaster(AccountMaster accountMaster) {
		this.accountMaster = accountMaster;
	}

	@Column(name = "FISCAL_YEAR",
			nullable = false,
			precision = 22,
			scale = 0)
	public BigDecimal getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(BigDecimal fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "ACCOUNT_TYPE_LEDGER",
			nullable = false,
			length = 8)
	public String getAccountTypeLedger() {
		return this.accountTypeLedger;
	}

	public void setAccountTypeLedger(String accountTypeLedger) {
		this.accountTypeLedger = accountTypeLedger;
	}

	@Override
	public String toString() {
		return "AccountBalanceId [accountMaster=" + accountMaster + ", fiscalYear=" + fiscalYear + ", accountTypeLedger=" + accountTypeLedger + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((accountMaster == null) ? 0 : accountMaster.hashCode());
		result = prime * result + ((accountTypeLedger == null) ? 0 : accountTypeLedger.hashCode());
		result = prime * result + ((fiscalYear == null) ? 0 : fiscalYear.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AccountBalanceId other = (AccountBalanceId) obj;
		if (accountMaster == null) {
			if (other.accountMaster != null)
				return false;
		} else if (!accountMaster.equals(other.accountMaster))
			return false;
		if (accountTypeLedger == null) {
			if (other.accountTypeLedger != null)
				return false;
		} else if (!accountTypeLedger.equals(other.accountTypeLedger))
			return false;
		if (fiscalYear == null) {
			if (other.fiscalYear != null)
				return false;
		} else if (!fiscalYear.equals(other.fiscalYear))
			return false;
		return true;
	}

}
