package com.gammon.pcms.model.adl.id;
// Generated Jun 28, 2016 4:30:40 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountLedgerId generated by hbm2java
 */

public class AccountLedgerId implements Serializable {

	private static final long serialVersionUID = 3450135772317991849L;

	private String entityDocCompanyKey;
	private String typeDocument;
	private BigDecimal numberDocument;
	private BigDecimal numberJournalEntryLine;
	private String numberJeLineExtension;
	private String accountTypeLedger;
	private Date dateGl;
	
	public AccountLedgerId() {}

	public AccountLedgerId(	String entityDocCompanyKey,
							String typeDocument,
							BigDecimal numberDocument,
							BigDecimal numberJournalEntryLine,
							String numberJeLineExtension,
							String accountTypeLedger,
							Date dateGl) {
		this.entityDocCompanyKey = entityDocCompanyKey;
		this.typeDocument = typeDocument;
		this.numberDocument = numberDocument;
		this.numberJournalEntryLine = numberJournalEntryLine;
		this.numberJeLineExtension = numberJeLineExtension;
		this.accountTypeLedger = accountTypeLedger;
		this.dateGl = dateGl;
	}

	@Column(name = "ENTITY_DOC_COMPANY_KEY",
			nullable = false,
			length = 20)
	public String getEntityDocCompanyKey() {
		return this.entityDocCompanyKey;
	}

	public void setEntityDocCompanyKey(String entityDocCompanyKey) {
		this.entityDocCompanyKey = entityDocCompanyKey;
	}

	@Column(name = "TYPE_DOCUMENT",
			nullable = false,
			length = 8)
	public String getTypeDocument() {
		return this.typeDocument;
	}

	public void setTypeDocument(String typeDocument) {
		this.typeDocument = typeDocument;
	}

	@Column(name = "NUMBER_DOCUMENT",
			nullable = false,
			precision = 22,
			scale = 0)
	public BigDecimal getNumberDocument() {
		return this.numberDocument;
	}

	public void setNumberDocument(BigDecimal numberDocument) {
		this.numberDocument = numberDocument;
	}

	@Column(name = "NUMBER_JOURNAL_ENTRY_LINE",
			nullable = false,
			precision = 22,
			scale = 0)
	public BigDecimal getNumberJournalEntryLine() {
		return this.numberJournalEntryLine;
	}

	public void setNumberJournalEntryLine(BigDecimal numberJournalEntryLine) {
		this.numberJournalEntryLine = numberJournalEntryLine;
	}

	@Column(name = "NUMBER_JE_LINE_EXTENSION",
			nullable = false,
			length = 8)
	public String getNumberJeLineExtension() {
		return this.numberJeLineExtension;
	}

	public void setNumberJeLineExtension(String numberJeLineExtension) {
		this.numberJeLineExtension = numberJeLineExtension;
	}

	@Column(name = "ACCOUNT_TYPE_LEDGER",
			nullable = false,
			length = 8)
	public String getAccountTypeLedger() {
		return this.accountTypeLedger;
	}

	public void setAccountTypeLedger(String accountTypeLedger) {
		this.accountTypeLedger = accountTypeLedger;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_GL",
			length = 7)
	public Date getDateGl() {
		return this.dateGl;
	}

	public void setDateGl(Date dateGl) {
		this.dateGl = dateGl;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dateGl == null) ? 0 : dateGl.hashCode());
		result = prime * result + ((accountTypeLedger == null) ? 0 : accountTypeLedger.hashCode());
		result = prime * result + ((entityDocCompanyKey == null) ? 0 : entityDocCompanyKey.hashCode());
		result = prime * result + ((numberDocument == null) ? 0 : numberDocument.hashCode());
		result = prime * result + ((numberJeLineExtension == null) ? 0 : numberJeLineExtension.hashCode());
		result = prime * result + ((numberJournalEntryLine == null) ? 0 : numberJournalEntryLine.hashCode());
		result = prime * result + ((typeDocument == null) ? 0 : typeDocument.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AccountLedgerId)) {
			return false;
		}
		AccountLedgerId other = (AccountLedgerId) obj;
		if (dateGl == null) {
			if (other.dateGl != null) {
				return false;
			}
		} else if (!dateGl.equals(other.dateGl)) {
			return false;
		}
		if (accountTypeLedger == null) {
			if (other.accountTypeLedger != null) {
				return false;
			}
		} else if (!accountTypeLedger.equals(other.accountTypeLedger)) {
			return false;
		}
		if (entityDocCompanyKey == null) {
			if (other.entityDocCompanyKey != null) {
				return false;
			}
		} else if (!entityDocCompanyKey.equals(other.entityDocCompanyKey)) {
			return false;
		}
		if (numberDocument == null) {
			if (other.numberDocument != null) {
				return false;
			}
		} else if (!numberDocument.equals(other.numberDocument)) {
			return false;
		}
		if (numberJeLineExtension == null) {
			if (other.numberJeLineExtension != null) {
				return false;
			}
		} else if (!numberJeLineExtension.equals(other.numberJeLineExtension)) {
			return false;
		}
		if (numberJournalEntryLine == null) {
			if (other.numberJournalEntryLine != null) {
				return false;
			}
		} else if (!numberJournalEntryLine.equals(other.numberJournalEntryLine)) {
			return false;
		}
		if (typeDocument == null) {
			if (other.typeDocument != null) {
				return false;
			}
		} else if (!typeDocument.equals(other.typeDocument)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "AccountLedgerId [entityDocCompanyKey=" + entityDocCompanyKey + ", typeDocument=" + typeDocument + ", numberDocument=" + numberDocument + ", numberJournalEntryLine=" + numberJournalEntryLine + ", numberJeLineExtension=" + numberJeLineExtension + ", accountTypeLedger=" + accountTypeLedger + ", dateGl=" + dateGl + "]";
	}

}
