ALTER SESSION SET CURRENT_SCHEMA = ACDATAPROD;

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050101','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050102','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050301','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050302','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050303','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050304','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050305','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050306','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050307','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02050501','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02080303','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02080304','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02080305','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02080307','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02090303','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02090304','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02090305','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02110101','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02110102','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02110103','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02110104','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02110105','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02110301','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02130101','ENABLE','A',sysdate,'IDT');

INSERT INTO AC_FUNCTIONSECURITY (APPLICATIONCODE,ROLENAME,FUNCTIONNAME,ACCESSRIGHT,STATUS,LASTMODIFYDATE,LASTMODIFYUSER) 
VALUES ('QS','ROLE_QS_REVIEWER','F02130211','ENABLE','A',sysdate,'IDT');
