package com.gammon.qs.domain;
// Generated Jun 14, 2016 11:29:35 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Addendum generated by hbm2java
 */
@Entity
@Table(name = "ADDENDUM")
public class Addendum implements java.io.Serializable {

	private static final long serialVersionUID = -730074274051941598L;
	private BigDecimal id;
	private Subcontract idSubcontract;
	private String noJob;
	private String noSubcontract;
	private String descriptionSubcontract;
	private String noSubcontractor;
	private String nameSubcontractor;
	private long no;
	private String title;
	private BigDecimal amtSubcontractRemeasured;
	private BigDecimal amtSubcontractRevised;
	private BigDecimal amtAddendumTotal;
	private BigDecimal amtAddendumTotalTba;
	private BigDecimal amtAddendum;
	private BigDecimal amtSubcontractRevisedTba;
	private Date dateSubmission;
	private Date dateApproval;
	private String status;
	private String statusApproval;
	private String usernamePreparedBy;
	private String remarks;
	private String usernameCreated;
	private Date dateCreated;
	private String usernameLastModified;
	private Date dateLastModified;

	public Addendum() {
	}

	public Addendum(BigDecimal id, String noJob, String noSubcontract, String noSubcontractor, long no,
			String usernameCreated, Date dateCreated) {
		this.id = id;
		this.noJob = noJob;
		this.noSubcontract = noSubcontract;
		this.noSubcontractor = noSubcontractor;
		this.no = no;
		this.usernameCreated = usernameCreated;
		this.dateCreated = dateCreated;
	}

	public Addendum(BigDecimal id, Subcontract idSubcontract, String noJob, String noSubcontract,
			String descriptionSubcontract, String noSubcontractor, String nameSubcontractor, long no, String title,
			BigDecimal amtSubcontractRemeasured, BigDecimal amtSubcontractRevised, BigDecimal amtAddendumTotal,
			BigDecimal amtAddendumTotalTba, BigDecimal amtAddendum, BigDecimal amtSubcontractRevisedTba,
			Date dateSubmission, Date dateApproval, String status, String statusApproval, String usernamePreparedBy,
			String remarks, String usernameCreated, Date dateCreated, String usernameLastModified,
			Date dateLastModified) {
		this.id = id;
		this.idSubcontract = idSubcontract;
		this.noJob = noJob;
		this.noSubcontract = noSubcontract;
		this.descriptionSubcontract = descriptionSubcontract;
		this.noSubcontractor = noSubcontractor;
		this.nameSubcontractor = nameSubcontractor;
		this.no = no;
		this.title = title;
		this.amtSubcontractRemeasured = amtSubcontractRemeasured;
		this.amtSubcontractRevised = amtSubcontractRevised;
		this.amtAddendumTotal = amtAddendumTotal;
		this.amtAddendumTotalTba = amtAddendumTotalTba;
		this.amtAddendum = amtAddendum;
		this.amtSubcontractRevisedTba = amtSubcontractRevisedTba;
		this.dateSubmission = dateSubmission;
		this.dateApproval = dateApproval;
		this.status = status;
		this.statusApproval = statusApproval;
		this.usernamePreparedBy = usernamePreparedBy;
		this.remarks = remarks;
		this.usernameCreated = usernameCreated;
		this.dateCreated = dateCreated;
		this.usernameLastModified = usernameLastModified;
		this.dateLastModified = dateLastModified;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}
	
	@ManyToOne
	@JoinColumn(name = "ID_SUBCONTRACT", nullable = false)
	public Subcontract getIdSubcontract() {
		return this.idSubcontract;
	}

	public void setIdSubcontract(Subcontract idSubcontract) {
		this.idSubcontract = idSubcontract;
	}

	@Column(name = "NO_JOB", nullable = false, length = 10)
	public String getNoJob() {
		return this.noJob;
	}

	public void setNoJob(String noJob) {
		this.noJob = noJob;
	}

	@Column(name = "NO_SUBCONTRACT", nullable = false, length = 8)
	public String getNoSubcontract() {
		return this.noSubcontract;
	}

	public void setNoSubcontract(String noSubcontract) {
		this.noSubcontract = noSubcontract;
	}

	@Column(name = "DESCRIPTION_SUBCONTRACT", length = 510)
	public String getDescriptionSubcontract() {
		return this.descriptionSubcontract;
	}

	public void setDescriptionSubcontract(String descriptionSubcontract) {
		this.descriptionSubcontract = descriptionSubcontract;
	}

	@Column(name = "NO_SUBCONTRACTOR", nullable = false, length = 20)
	public String getNoSubcontractor() {
		return this.noSubcontractor;
	}

	public void setNoSubcontractor(String noSubcontractor) {
		this.noSubcontractor = noSubcontractor;
	}

	@Column(name = "NAME_SUBCONTRACTOR", length = 510)
	public String getNameSubcontractor() {
		return this.nameSubcontractor;
	}

	public void setNameSubcontractor(String nameSubcontractor) {
		this.nameSubcontractor = nameSubcontractor;
	}

	@Column(name = "NO", nullable = false, precision = 10, scale = 0)
	public long getNo() {
		return this.no;
	}

	public void setNo(long no) {
		this.no = no;
	}

	@Column(name = "TITLE", length = 510)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "AMT_SUBCONTRACT_REMEASURED")
	public BigDecimal getAmtSubcontractRemeasured() {
		return this.amtSubcontractRemeasured;
	}

	public void setAmtSubcontractRemeasured(BigDecimal amtSubcontractRemeasured) {
		this.amtSubcontractRemeasured = amtSubcontractRemeasured;
	}

	@Column(name = "AMT_SUBCONTRACT_REVISED")
	public BigDecimal getAmtSubcontractRevised() {
		return this.amtSubcontractRevised;
	}

	public void setAmtSubcontractRevised(BigDecimal amtSubcontractRevised) {
		this.amtSubcontractRevised = amtSubcontractRevised;
	}

	@Column(name = "AMT_ADDENDUM_TOTAL")
	public BigDecimal getAmtAddendumTotal() {
		return this.amtAddendumTotal;
	}

	public void setAmtAddendumTotal(BigDecimal amtAddendumTotal) {
		this.amtAddendumTotal = amtAddendumTotal;
	}

	@Column(name = "AMT_ADDENDUM_TOTAL_TBA")
	public BigDecimal getAmtAddendumTotalTba() {
		return this.amtAddendumTotalTba;
	}

	public void setAmtAddendumTotalTba(BigDecimal amtAddendumTotalTba) {
		this.amtAddendumTotalTba = amtAddendumTotalTba;
	}

	@Column(name = "AMT_ADDENDUM")
	public BigDecimal getAmtAddendum() {
		return this.amtAddendum;
	}

	public void setAmtAddendum(BigDecimal amtAddendum) {
		this.amtAddendum = amtAddendum;
	}

	@Column(name = "AMT_SUBCONTRACT_REVISED_TBA")
	public BigDecimal getAmtSubcontractRevisedTba() {
		return this.amtSubcontractRevisedTba;
	}

	public void setAmtSubcontractRevisedTba(BigDecimal amtSubcontractRevisedTba) {
		this.amtSubcontractRevisedTba = amtSubcontractRevisedTba;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_SUBMISSION", length = 7)
	public Date getDateSubmission() {
		return this.dateSubmission;
	}

	public void setDateSubmission(Date dateSubmission) {
		this.dateSubmission = dateSubmission;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_APPROVAL", length = 7)
	public Date getDateApproval() {
		return this.dateApproval;
	}

	public void setDateApproval(Date dateApproval) {
		this.dateApproval = dateApproval;
	}

	@Column(name = "STATUS", length = 40)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "STATUS_APPROVAL", length = 40)
	public String getStatusApproval() {
		return this.statusApproval;
	}

	public void setStatusApproval(String statusApproval) {
		this.statusApproval = statusApproval;
	}

	@Column(name = "USERNAME_PREPARED_BY", length = 40)
	public String getUsernamePreparedBy() {
		return this.usernamePreparedBy;
	}

	public void setUsernamePreparedBy(String usernamePreparedBy) {
		this.usernamePreparedBy = usernamePreparedBy;
	}

	@Column(name = "REMARKS", length = 2000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "USERNAME_CREATED", nullable = false, length = 40)
	public String getUsernameCreated() {
		return this.usernameCreated;
	}

	public void setUsernameCreated(String usernameCreated) {
		this.usernameCreated = usernameCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATED", nullable = false, length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "USERNAME_LAST_MODIFIED", length = 40)
	public String getUsernameLastModified() {
		return this.usernameLastModified;
	}

	public void setUsernameLastModified(String usernameLastModified) {
		this.usernameLastModified = usernameLastModified;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_LAST_MODIFIED", length = 7)
	public Date getDateLastModified() {
		return this.dateLastModified;
	}

	public void setDateLastModified(Date dateLastModified) {
		this.dateLastModified = dateLastModified;
	}

}
