import {
  TextBoxComponent,
  NumericTextBoxComponent
} from "@syncfusion/ej2-react-inputs"
import {
  ButtonComponent
} from "@syncfusion/ej2-react-buttons"
import {
  GridComponent,
  ColumnsDirective,
  ColumnDirective,
  Inject,
  ToolbarItems,
  Filter,
  VirtualScroll,
  Sort,
  ExcelExport,Toolbar,
  Page
} from "@syncfusion/ej2-react-grids"
import { DropDownListComponent } from "@syncfusion/ej2-react-dropdowns"
import { TooltipComponent } from "@syncfusion/ej2-react-popups"
import './style.css'

const SubcontractDetail = () => {

  const toolbar: ToolbarItems[] = ['Search', 'ExcelExport', 'CsvExport'];
  const data = [
    {
      createdUser: "SYSTEM",
      createdDate: "2020-11-17T15:00:04.000+00:00",
      lastModifiedUser: "SYSTEM",
      lastModifiedDate: "2020-11-17T15:00:04.000+00:00",
      systemStatus: "ACTIVE",
      id: 603069,
      jobNo: "13892",
      sequenceNo: 1,
      resourceNo: 402141,
      billItem: " ",
      description: "Ground Investigation Works (Buying Gain)",
      quantity: 171239.9,
      scRate: 0.00125,
      objectCode: "149999",
      subsidiaryCode: "25999999",
      lineType: "BQ",
      approved: "A",
      unit: "UN",
      remark: null,
      typeRecoverable: null,
      postedCertifiedQuantity: 0.0,
      cumCertifiedQuantity: 0.0,
      amountCumulativeCert: 0,
      amountPostedCert: 0,
      amountSubcontractNew: 0,
      newQuantity: 171239.9,
      originalQuantity: 171239.9,
      tenderAnalysisDetail_ID: 215988,
      subcontract: {
        createdUser: "victorhui",
        createdDate: "2020-11-12T03:41:58.000+00:00",
        lastModifiedUser: "victorhui",
        lastModifiedDate: "2022-09-02T06:47:40.000+00:00",
        systemStatus: "ACTIVE",
        id: 75852,
        jobInfo: {
          createdUser: "mioucheang",
          createdDate: "2020-07-03T07:59:15.000+00:00",
          lastModifiedUser: "IDT-KOEY",
          lastModifiedDate: "2022-09-05T13:45:09.000+00:00",
          systemStatus: "ACTIVE",
          id: 7870,
          budgetPosted: null,
          eotApplied: 0.0,
          eotAwarded: 848.0,
          ldExposureAmount: 0.0,
          residualAfterEot: 0.0,
          nameExecutiveDirector: null,
          nameDirector: null,
          nameDirectSupervisorPic: null,
          nameProjectInCharge: null,
          nameCommercialInCharge: null,
          nameTempWorkController: null,
          nameSafetyEnvRep: null,
          nameAuthorizedPerson: null,
          nameSiteAdmin1: null,
          nameSiteAdmin2: null,
          nameSiteManagement1: null,
          nameSiteManagement2: null,
          nameSiteManagement3: null,
          nameSiteManagement4: null,
          nameSiteSupervision1: null,
          nameSiteSupervision2: null,
          nameSiteSupervision3: null,
          nameSiteSupervision4: null,
          noReference: 0,
          statusApproval: null,
          projectFullDescription:
            "Airport Authority APM and BHS Tunnels and Related Works \nSub-Contract J3880/SC1302 - Ground Investigation",
          projectLocation: "Part of Three Runway System",
          natureOfWorkBB: null,
          natureOfWorkGammon: "F04",
          tenderNumber: "T19022",
          immediateParentJobNumber: null,
          ultimateParentJobNumber: null,
          ultimateClient: "31704",
          immediateClientBusinessSector: null,
          ultimateClientBusinessSector: null,
          clientType: null,
          engineerArchitect: null,
          beam: null,
          beamPlus: null,
          leed: null,
          innovationApplicable: "0",
          innovationPercent: null,
          paymentTermFromClient: null,
          provision: "N",
          isParentCompanyGuarantee: null,
          jobNo: "13892",
          description: "APM & BHS Tunnels - GI(S13880)",
          company: "00001",
          employer: "33540",
          contractType: "RMC",
          division: "FDN",
          department: "GE",
          internalJob: "FC",
          soloJV: "S",
          completionStatus: "1",
          insuranceCAR: " ",
          insuranceECI: " ",
          insuranceTPL: " ",
          clientContractNo: "Contract 3802",
          parentJobNo: "13892",
          jvPartnerNo: "0",
          jvPercentage: 0.0,
          originalContractValue: 3.4122665e7,
          projectedContractValue: 3.4122665e7,
          orginalNSCContractValue: 0.0,
          tenderGP: 1876746.58,
          forecastEndYear: 2022,
          forecastEndPeriod: 6,
          maxRetPercent: 5.0,
          interimRetPercent: 5.0,
          mosRetPercent: 5.0,
          valueOfBSWork: 0.0,
          grossFloorArea: 0.0,
          grossFloorAreaUnit: "  ",
          billingCurrency: "   ",
          paymentTermForNSC: null,
          defectProvisionPercent: null,
          cpfApplicable: "0",
          cpfIndexName: null,
          cpfBaseYear: null,
          cpfBasePeriod: null,
          levyApplicable: "0",
          levyCITAPercent: 0.0,
          levyPCFBPercent: 0.0,
          expectedPCCDate: null,
          actualPCCDate: "2023-03-31",
          expectedMakingGoodDate: null,
          actualMakingGoodDate: null,
          defectLiabilityPeriod: 12,
          defectListIssuedDate: null,
          financialEndDate: null,
          dateFinalACSettlement: null,
          yearOfCompletion: 0,
          bqFinalizedFlag: " ",
          manualInputSCWD: "Y",
          legacyJob: null,
          conversionStatus: "Y",
          repackagingType: "1",
          finQS0Review: "D",
        },
        packageNo: "1001",
        description: "Ground Investigation Works",
        packageType: "S",
        packageStatus: null,
        subcontractorNature: "DSC",
        originalSubcontractSum: 6467155.0,
        approvedVOAmount: 14483292.44,
        remeasuredSubcontractSum: 6467155.0,
        approvalRoute: null,
        retentionTerms: "Percentage - Revised SC Sum",
        maxRetentionPercentage: 10.0,
        interimRentionPercentage: 10.0,
        mosRetentionPercentage: 10.0,
        retentionAmount: 2095044.74,
        accumlatedRetention: 1531883.08,
        retentionReleased: 0.0,
        paymentInformation: null,
        paymentCurrency: "HKD",
        exchangeRate: 1.0,
        paymentTerms: "QS2",
        subcontractTerm: "Re-measurement",
        cpfCalculation: "0",
        cpfBasePeriod: null,
        cpfBaseYear: null,
        formOfSubcontract: "Major",
        internalJobNo: null,
        paymentStatus: "I",
        submittedAddendum: " ",
        splitTerminateStatus: "0",
        paymentTermsDescription: null,
        notes: null,
        workscope: 201,
        nameSubcontractor: "Gaint Dragon Construction Engineering Ltd",
        scCreatedDate: null,
        latestAddendumValueUpdatedDate: "2022-07-25",
        firstPaymentCertIssuedDate: "2020-11-30",
        lastPaymentCertIssuedDate: "2022-08-16",
        finalPaymentIssuedDate: null,
        scAwardApprovalRequestSentDate: "2020-11-12",
        scApprovalDate: "2020-11-17",
        labourIncludedContract: true,
        plantIncludedContract: true,
        materialIncludedContract: true,
        totalPostedWorkDoneAmount: 21750288.02,
        totalCumWorkDoneAmount: 21750288.02,
        totalPostedCertifiedAmount: 15318830.8,
        totalCumCertifiedAmount: 16578535.72,
        totalCCPostedCertAmount: -28500.0,
        totalMOSPostedCertAmount: 0.0,
        totalAPPostedCertAmount: 0,
        totalRecoverableAmount: 14483292.44,
        totalNonRecoverableAmount: 0,
        requisitionApprovedDate: null,
        tenderAnalysisApprovedDate: "2020-06-12",
        preAwardMeetingDate: null,
        loaSignedDate: null,
        scDocScrDate: "2020-06-22",
        scDocLegalDate: null,
        workCommenceDate: "2020-06-15",
        onSiteStartDate: "2020-06-23",
        scFinalAccDraftDate: null,
        scFinalAccSignoffDate: null,
        paymentMethod: null,
        periodForPayment: null,
        amountPackageStretchTarget: null,
        reasonLoa: null,
        dateScExecutionTarget: null,
        executionMethodMainContract: null,
        executionMethodPropsed: null,
        durationFrom: null,
        durationTo: null,
        reasonQuotation: null,
        reasonManner: null,
        amtCEDApproved: 12540244.8,
        retentionBalance: 1531883.08,
        totalNetPostedCertifiedAmount: 13758447.72,
        paymentStatusText: "Interim",
        subcontractType: "Labour & Plant & Material",
        splitTerminateStatusText: "Not Submitted",
        totalProvisionAmount: 6431457.22,
        balanceToCompleteAmount: -799840.58,
        subcontractSum: 20950447.44,
        awarded: true,
        vendorNo: "400875",
        scStatus: 500,
      },
      amountSubcontract: 0,
      amountBudget: 171239.9,
      balanceType: "",
      amountPostedWD: 0,
      postedWorkDoneQuantity: 0.0,
      amountCumulativeWD: 0,
      cumWorkDoneQuantity: 0.0,
      costRate: 1.0,
      toBeApprovedAmount: 0.0,
      totalAmount: 0.0,
      sourceType: "BQ",
      ivamount: 0.0,
      projectedProvision: 0.0,
      workDoneMovement: 0.0,
      provision: 0.0,
      toBeApprovedRate: 0.0,
      toBeApprovedQuantity: 0.0,
      altObjectCode: "",
      contraChargeSCNo: "",
      corrSCLineSeqNo: 0,
      amountBudgetNew: 0.0,
    },
    {
      createdUser: "SYSTEM",
      createdDate: "2020-11-17T15:00:04.000+00:00",
      lastModifiedUser: "koeyyeung",
      lastModifiedDate: "2022-01-20T06:38:36.000+00:00",
      systemStatus: "ACTIVE",
      id: 603070,
      jobNo: "13892",
      sequenceNo: 2,
      resourceNo: 402140,
      billItem: " ",
      description: "Ground Investigation Works",
      quantity: 6467155.0,
      scRate: 1.0,
      objectCode: "149999",
      subsidiaryCode: "25999999",
      lineType: "BQ",
      approved: "A",
      unit: "UN",
      remark: null,
      typeRecoverable: null,
      postedCertifiedQuantity: 0.0,
      cumCertifiedQuantity: 0.0,
      amountCumulativeCert: 6467155,
      amountPostedCert: 6467155,
      amountSubcontractNew: 6467155,
      newQuantity: 6467155.0,
      originalQuantity: 6467155.0,
      tenderAnalysisDetail_ID: 215989,
      subcontract: {
        createdUser: "victorhui",
        createdDate: "2020-11-12T03:41:58.000+00:00",
        lastModifiedUser: "victorhui",
        lastModifiedDate: "2022-09-02T06:47:40.000+00:00",
        systemStatus: "ACTIVE",
        id: 75852,
        jobInfo: {
          createdUser: "mioucheang",
          createdDate: "2020-07-03T07:59:15.000+00:00",
          lastModifiedUser: "IDT-KOEY",
          lastModifiedDate: "2022-09-05T13:45:09.000+00:00",
          systemStatus: "ACTIVE",
          id: 7870,
          budgetPosted: null,
          eotApplied: 0.0,
          eotAwarded: 848.0,
          ldExposureAmount: 0.0,
          residualAfterEot: 0.0,
          nameExecutiveDirector: null,
          nameDirector: null,
          nameDirectSupervisorPic: null,
          nameProjectInCharge: null,
          nameCommercialInCharge: null,
          nameTempWorkController: null,
          nameSafetyEnvRep: null,
          nameAuthorizedPerson: null,
          nameSiteAdmin1: null,
          nameSiteAdmin2: null,
          nameSiteManagement1: null,
          nameSiteManagement2: null,
          nameSiteManagement3: null,
          nameSiteManagement4: null,
          nameSiteSupervision1: null,
          nameSiteSupervision2: null,
          nameSiteSupervision3: null,
          nameSiteSupervision4: null,
          noReference: 0,
          statusApproval: null,
          projectFullDescription:
            "Airport Authority APM and BHS Tunnels and Related Works \nSub-Contract J3880/SC1302 - Ground Investigation",
          projectLocation: "Part of Three Runway System",
          natureOfWorkBB: null,
          natureOfWorkGammon: "F04",
          tenderNumber: "T19022",
          immediateParentJobNumber: null,
          ultimateParentJobNumber: null,
          ultimateClient: "31704",
          immediateClientBusinessSector: null,
          ultimateClientBusinessSector: null,
          clientType: null,
          engineerArchitect: null,
          beam: null,
          beamPlus: null,
          leed: null,
          innovationApplicable: "0",
          innovationPercent: null,
          paymentTermFromClient: null,
          provision: "N",
          isParentCompanyGuarantee: null,
          jobNo: "13892",
          description: "APM & BHS Tunnels - GI(S13880)",
          company: "00001",
          employer: "33540",
          contractType: "RMC",
          division: "FDN",
          department: "GE",
          internalJob: "FC",
          soloJV: "S",
          completionStatus: "1",
          insuranceCAR: " ",
          insuranceECI: " ",
          insuranceTPL: " ",
          clientContractNo: "Contract 3802",
          parentJobNo: "13892",
          jvPartnerNo: "0",
          jvPercentage: 0.0,
          originalContractValue: 3.4122665e7,
          projectedContractValue: 3.4122665e7,
          orginalNSCContractValue: 0.0,
          tenderGP: 1876746.58,
          forecastEndYear: 2022,
          forecastEndPeriod: 6,
          maxRetPercent: 5.0,
          interimRetPercent: 5.0,
          mosRetPercent: 5.0,
          valueOfBSWork: 0.0,
          grossFloorArea: 0.0,
          grossFloorAreaUnit: "  ",
          billingCurrency: "   ",
          paymentTermForNSC: null,
          defectProvisionPercent: null,
          cpfApplicable: "0",
          cpfIndexName: null,
          cpfBaseYear: null,
          cpfBasePeriod: null,
          levyApplicable: "0",
          levyCITAPercent: 0.0,
          levyPCFBPercent: 0.0,
          expectedPCCDate: null,
          actualPCCDate: "2023-03-31",
          expectedMakingGoodDate: null,
          actualMakingGoodDate: null,
          defectLiabilityPeriod: 12,
          defectListIssuedDate: null,
          financialEndDate: null,
          dateFinalACSettlement: null,
          yearOfCompletion: 0,
          bqFinalizedFlag: " ",
          manualInputSCWD: "Y",
          legacyJob: null,
          conversionStatus: "Y",
          repackagingType: "1",
          finQS0Review: "D",
        },
        packageNo: "1001",
        description: "Ground Investigation Works",
        packageType: "S",
        packageStatus: null,
        subcontractorNature: "DSC",
        originalSubcontractSum: 6467155.0,
        approvedVOAmount: 14483292.44,
        remeasuredSubcontractSum: 6467155.0,
        approvalRoute: null,
        retentionTerms: "Percentage - Revised SC Sum",
        maxRetentionPercentage: 10.0,
        interimRentionPercentage: 10.0,
        mosRetentionPercentage: 10.0,
        retentionAmount: 2095044.74,
        accumlatedRetention: 1531883.08,
        retentionReleased: 0.0,
        paymentInformation: null,
        paymentCurrency: "HKD",
        exchangeRate: 1.0,
        paymentTerms: "QS2",
        subcontractTerm: "Re-measurement",
        cpfCalculation: "0",
        cpfBasePeriod: null,
        cpfBaseYear: null,
        formOfSubcontract: "Major",
        internalJobNo: null,
        paymentStatus: "I",
        submittedAddendum: " ",
        splitTerminateStatus: "0",
        paymentTermsDescription: null,
        notes: null,
        workscope: 201,
        nameSubcontractor: "Gaint Dragon Construction Engineering Ltd",
        scCreatedDate: null,
        latestAddendumValueUpdatedDate: "2022-07-25",
        firstPaymentCertIssuedDate: "2020-11-30",
        lastPaymentCertIssuedDate: "2022-08-16",
        finalPaymentIssuedDate: null,
        scAwardApprovalRequestSentDate: "2020-11-12",
        scApprovalDate: "2020-11-17",
        labourIncludedContract: true,
        plantIncludedContract: true,
        materialIncludedContract: true,
        totalPostedWorkDoneAmount: 21750288.02,
        totalCumWorkDoneAmount: 21750288.02,
        totalPostedCertifiedAmount: 15318830.8,
        totalCumCertifiedAmount: 16578535.72,
        totalCCPostedCertAmount: -28500.0,
        totalMOSPostedCertAmount: 0.0,
        totalAPPostedCertAmount: 0,
        totalRecoverableAmount: 14483292.44,
        totalNonRecoverableAmount: 0,
        requisitionApprovedDate: null,
        tenderAnalysisApprovedDate: "2020-06-12",
        preAwardMeetingDate: null,
        loaSignedDate: null,
        scDocScrDate: "2020-06-22",
        scDocLegalDate: null,
        workCommenceDate: "2020-06-15",
        onSiteStartDate: "2020-06-23",
        scFinalAccDraftDate: null,
        scFinalAccSignoffDate: null,
        paymentMethod: null,
        periodForPayment: null,
        amountPackageStretchTarget: null,
        reasonLoa: null,
        dateScExecutionTarget: null,
        executionMethodMainContract: null,
        executionMethodPropsed: null,
        durationFrom: null,
        durationTo: null,
        reasonQuotation: null,
        reasonManner: null,
        amtCEDApproved: 12540244.8,
        retentionBalance: 1531883.08,
        totalNetPostedCertifiedAmount: 13758447.72,
        paymentStatusText: "Interim",
        subcontractType: "Labour & Plant & Material",
        splitTerminateStatusText: "Not Submitted",
        totalProvisionAmount: 6431457.22,
        balanceToCompleteAmount: -799840.58,
        subcontractSum: 20950447.44,
        awarded: true,
        vendorNo: "400875",
        scStatus: 500,
      },
      amountSubcontract: 6467155,
      amountBudget: 6467155,
      balanceType: "",
      amountPostedWD: 6467155,
      postedWorkDoneQuantity: 6467155.0,
      amountCumulativeWD: 6467155,
      cumWorkDoneQuantity: 6467155.0,
      costRate: 1.0,
      toBeApprovedAmount: 0.0,
      totalAmount: 6467155.0,
      sourceType: "BQ",
      ivamount: 6467155.0,
      projectedProvision: 0.0,
      workDoneMovement: 0.0,
      provision: 0.0,
      toBeApprovedRate: 0.0,
      toBeApprovedQuantity: 0.0,
      altObjectCode: "",
      contraChargeSCNo: "",
      corrSCLineSeqNo: 0,
      amountBudgetNew: 6467155.0,
    },
    {
      createdUser: "SYSTEM",
      createdDate: "2022-01-14T13:34:31.000+00:00",
      lastModifiedUser: "victorhui",
      lastModifiedDate: "2022-09-02T06:47:39.000+00:00",
      systemStatus: "ACTIVE",
      id: 619736,
      jobNo: "13892",
      sequenceNo: 5,
      resourceNo: 0,
      billItem: "95/1/V1/0002",
      description: "Addendum No.1",
      quantity: 6073089.8,
      scRate: 1.0,
      objectCode: "140299",
      subsidiaryCode: "25999999",
      lineType: "V1",
      approved: "A",
      unit: "UN",
      remark: null,
      typeRecoverable: "R",
      postedCertifiedQuantity: 0.0,
      cumCertifiedQuantity: 0.0,
      amountCumulativeCert: 6073089.8,
      amountPostedCert: 6073089.8,
      amountSubcontractNew: 6073089.8,
      newQuantity: 6073089.8,
      originalQuantity: 0.0,
      tenderAnalysisDetail_ID: null,
      subcontract: {
        createdUser: "victorhui",
        createdDate: "2020-11-12T03:41:58.000+00:00",
        lastModifiedUser: "victorhui",
        lastModifiedDate: "2022-09-02T06:47:40.000+00:00",
        systemStatus: "ACTIVE",
        id: 75852,
        jobInfo: {
          createdUser: "mioucheang",
          createdDate: "2020-07-03T07:59:15.000+00:00",
          lastModifiedUser: "IDT-KOEY",
          lastModifiedDate: "2022-09-05T13:45:09.000+00:00",
          systemStatus: "ACTIVE",
          id: 7870,
          budgetPosted: null,
          eotApplied: 0.0,
          eotAwarded: 848.0,
          ldExposureAmount: 0.0,
          residualAfterEot: 0.0,
          nameExecutiveDirector: null,
          nameDirector: null,
          nameDirectSupervisorPic: null,
          nameProjectInCharge: null,
          nameCommercialInCharge: null,
          nameTempWorkController: null,
          nameSafetyEnvRep: null,
          nameAuthorizedPerson: null,
          nameSiteAdmin1: null,
          nameSiteAdmin2: null,
          nameSiteManagement1: null,
          nameSiteManagement2: null,
          nameSiteManagement3: null,
          nameSiteManagement4: null,
          nameSiteSupervision1: null,
          nameSiteSupervision2: null,
          nameSiteSupervision3: null,
          nameSiteSupervision4: null,
          noReference: 0,
          statusApproval: null,
          projectFullDescription:
            "Airport Authority APM and BHS Tunnels and Related Works \nSub-Contract J3880/SC1302 - Ground Investigation",
          projectLocation: "Part of Three Runway System",
          natureOfWorkBB: null,
          natureOfWorkGammon: "F04",
          tenderNumber: "T19022",
          immediateParentJobNumber: null,
          ultimateParentJobNumber: null,
          ultimateClient: "31704",
          immediateClientBusinessSector: null,
          ultimateClientBusinessSector: null,
          clientType: null,
          engineerArchitect: null,
          beam: null,
          beamPlus: null,
          leed: null,
          innovationApplicable: "0",
          innovationPercent: null,
          paymentTermFromClient: null,
          provision: "N",
          isParentCompanyGuarantee: null,
          jobNo: "13892",
          description: "APM & BHS Tunnels - GI(S13880)",
          company: "00001",
          employer: "33540",
          contractType: "RMC",
          division: "FDN",
          department: "GE",
          internalJob: "FC",
          soloJV: "S",
          completionStatus: "1",
          insuranceCAR: " ",
          insuranceECI: " ",
          insuranceTPL: " ",
          clientContractNo: "Contract 3802",
          parentJobNo: "13892",
          jvPartnerNo: "0",
          jvPercentage: 0.0,
          originalContractValue: 3.4122665e7,
          projectedContractValue: 3.4122665e7,
          orginalNSCContractValue: 0.0,
          tenderGP: 1876746.58,
          forecastEndYear: 2022,
          forecastEndPeriod: 6,
          maxRetPercent: 5.0,
          interimRetPercent: 5.0,
          mosRetPercent: 5.0,
          valueOfBSWork: 0.0,
          grossFloorArea: 0.0,
          grossFloorAreaUnit: "  ",
          billingCurrency: "   ",
          paymentTermForNSC: null,
          defectProvisionPercent: null,
          cpfApplicable: "0",
          cpfIndexName: null,
          cpfBaseYear: null,
          cpfBasePeriod: null,
          levyApplicable: "0",
          levyCITAPercent: 0.0,
          levyPCFBPercent: 0.0,
          expectedPCCDate: null,
          actualPCCDate: "2023-03-31",
          expectedMakingGoodDate: null,
          actualMakingGoodDate: null,
          defectLiabilityPeriod: 12,
          defectListIssuedDate: null,
          financialEndDate: null,
          dateFinalACSettlement: null,
          yearOfCompletion: 0,
          bqFinalizedFlag: " ",
          manualInputSCWD: "Y",
          legacyJob: null,
          conversionStatus: "Y",
          repackagingType: "1",
          finQS0Review: "D",
        },
        packageNo: "1001",
        description: "Ground Investigation Works",
        packageType: "S",
        packageStatus: null,
        subcontractorNature: "DSC",
        originalSubcontractSum: 6467155.0,
        approvedVOAmount: 14483292.44,
        remeasuredSubcontractSum: 6467155.0,
        approvalRoute: null,
        retentionTerms: "Percentage - Revised SC Sum",
        maxRetentionPercentage: 10.0,
        interimRentionPercentage: 10.0,
        mosRetentionPercentage: 10.0,
        retentionAmount: 2095044.74,
        accumlatedRetention: 1531883.08,
        retentionReleased: 0.0,
        paymentInformation: null,
        paymentCurrency: "HKD",
        exchangeRate: 1.0,
        paymentTerms: "QS2",
        subcontractTerm: "Re-measurement",
        cpfCalculation: "0",
        cpfBasePeriod: null,
        cpfBaseYear: null,
        formOfSubcontract: "Major",
        internalJobNo: null,
        paymentStatus: "I",
        submittedAddendum: " ",
        splitTerminateStatus: "0",
        paymentTermsDescription: null,
        notes: null,
        workscope: 201,
        nameSubcontractor: "Gaint Dragon Construction Engineering Ltd",
        scCreatedDate: null,
        latestAddendumValueUpdatedDate: "2022-07-25",
        firstPaymentCertIssuedDate: "2020-11-30",
        lastPaymentCertIssuedDate: "2022-08-16",
        finalPaymentIssuedDate: null,
        scAwardApprovalRequestSentDate: "2020-11-12",
        scApprovalDate: "2020-11-17",
        labourIncludedContract: true,
        plantIncludedContract: true,
        materialIncludedContract: true,
        totalPostedWorkDoneAmount: 21750288.02,
        totalCumWorkDoneAmount: 21750288.02,
        totalPostedCertifiedAmount: 15318830.8,
        totalCumCertifiedAmount: 16578535.72,
        totalCCPostedCertAmount: -28500.0,
        totalMOSPostedCertAmount: 0.0,
        totalAPPostedCertAmount: 0,
        totalRecoverableAmount: 14483292.44,
        totalNonRecoverableAmount: 0,
        requisitionApprovedDate: null,
        tenderAnalysisApprovedDate: "2020-06-12",
        preAwardMeetingDate: null,
        loaSignedDate: null,
        scDocScrDate: "2020-06-22",
        scDocLegalDate: null,
        workCommenceDate: "2020-06-15",
        onSiteStartDate: "2020-06-23",
        scFinalAccDraftDate: null,
        scFinalAccSignoffDate: null,
        paymentMethod: null,
        periodForPayment: null,
        amountPackageStretchTarget: null,
        reasonLoa: null,
        dateScExecutionTarget: null,
        executionMethodMainContract: null,
        executionMethodPropsed: null,
        durationFrom: null,
        durationTo: null,
        reasonQuotation: null,
        reasonManner: null,
        amtCEDApproved: 12540244.8,
        retentionBalance: 1531883.08,
        totalNetPostedCertifiedAmount: 13758447.72,
        paymentStatusText: "Interim",
        subcontractType: "Labour & Plant & Material",
        splitTerminateStatusText: "Not Submitted",
        totalProvisionAmount: 6431457.22,
        balanceToCompleteAmount: -799840.58,
        subcontractSum: 20950447.44,
        awarded: true,
        vendorNo: "400875",
        scStatus: 500,
      },
      amountSubcontract: 6073089.8,
      amountBudget: 0,
      balanceType: "",
      amountPostedWD: 6073089.8,
      postedWorkDoneQuantity: 6073089.8,
      amountCumulativeWD: 6073089.8,
      cumWorkDoneQuantity: 6073089.8,
      costRate: 0.0,
      toBeApprovedRate: 0.0,
      contraChargeSCNo: null,
      corrSCLineSeqNo: null,
      altObjectCode: null,
      toBeApprovedAmount: 0.0,
      sourceType: "A",
      totalAmount: 6073089.8,
      ivamount: 0.0,
      projectedProvision: 0.0,
      workDoneMovement: 0.0,
      provision: 0.0,
      toBeApprovedQuantity: 0.0,
      amountBudgetNew: 0.0,
    },
    {
      createdUser: "SYSTEM",
      createdDate: "2022-07-25T06:07:39.000+00:00",
      lastModifiedUser: "victorhui",
      lastModifiedDate: "2022-09-02T06:47:39.000+00:00",
      systemStatus: "ACTIVE",
      id: 626321,
      jobNo: "13892",
      sequenceNo: 6,
      resourceNo: 0,
      billItem: "95/2/V1/0008",
      description: "SC1001; Addendum No.2 (Type V1)",
      quantity: 8410202.64,
      scRate: 1.0,
      objectCode: "140299",
      subsidiaryCode: "25999999",
      lineType: "V1",
      approved: "A",
      unit: "UN",
      remark: null,
      typeRecoverable: "R",
      postedCertifiedQuantity: 0.0,
      cumCertifiedQuantity: 0.0,
      amountCumulativeCert: 4038290.92,
      amountPostedCert: 2778586,
      amountSubcontractNew: 8410202.64,
      newQuantity: 8410202.64,
      originalQuantity: 0.0,
      tenderAnalysisDetail_ID: null,
      subcontract: {
        createdUser: "victorhui",
        createdDate: "2020-11-12T03:41:58.000+00:00",
        lastModifiedUser: "victorhui",
        lastModifiedDate: "2022-09-02T06:47:40.000+00:00",
        systemStatus: "ACTIVE",
        id: 75852,
        jobInfo: {
          createdUser: "mioucheang",
          createdDate: "2020-07-03T07:59:15.000+00:00",
          lastModifiedUser: "IDT-KOEY",
          lastModifiedDate: "2022-09-05T13:45:09.000+00:00",
          systemStatus: "ACTIVE",
          id: 7870,
          budgetPosted: null,
          eotApplied: 0.0,
          eotAwarded: 848.0,
          ldExposureAmount: 0.0,
          residualAfterEot: 0.0,
          nameExecutiveDirector: null,
          nameDirector: null,
          nameDirectSupervisorPic: null,
          nameProjectInCharge: null,
          nameCommercialInCharge: null,
          nameTempWorkController: null,
          nameSafetyEnvRep: null,
          nameAuthorizedPerson: null,
          nameSiteAdmin1: null,
          nameSiteAdmin2: null,
          nameSiteManagement1: null,
          nameSiteManagement2: null,
          nameSiteManagement3: null,
          nameSiteManagement4: null,
          nameSiteSupervision1: null,
          nameSiteSupervision2: null,
          nameSiteSupervision3: null,
          nameSiteSupervision4: null,
          noReference: 0,
          statusApproval: null,
          projectFullDescription:
            "Airport Authority APM and BHS Tunnels and Related Works \nSub-Contract J3880/SC1302 - Ground Investigation",
          projectLocation: "Part of Three Runway System",
          natureOfWorkBB: null,
          natureOfWorkGammon: "F04",
          tenderNumber: "T19022",
          immediateParentJobNumber: null,
          ultimateParentJobNumber: null,
          ultimateClient: "31704",
          immediateClientBusinessSector: null,
          ultimateClientBusinessSector: null,
          clientType: null,
          engineerArchitect: null,
          beam: null,
          beamPlus: null,
          leed: null,
          innovationApplicable: "0",
          innovationPercent: null,
          paymentTermFromClient: null,
          provision: "N",
          isParentCompanyGuarantee: null,
          jobNo: "13892",
          description: "APM & BHS Tunnels - GI(S13880)",
          company: "00001",
          employer: "33540",
          contractType: "RMC",
          division: "FDN",
          department: "GE",
          internalJob: "FC",
          soloJV: "S",
          completionStatus: "1",
          insuranceCAR: " ",
          insuranceECI: " ",
          insuranceTPL: " ",
          clientContractNo: "Contract 3802",
          parentJobNo: "13892",
          jvPartnerNo: "0",
          jvPercentage: 0.0,
          originalContractValue: 3.4122665e7,
          projectedContractValue: 3.4122665e7,
          orginalNSCContractValue: 0.0,
          tenderGP: 1876746.58,
          forecastEndYear: 2022,
          forecastEndPeriod: 6,
          maxRetPercent: 5.0,
          interimRetPercent: 5.0,
          mosRetPercent: 5.0,
          valueOfBSWork: 0.0,
          grossFloorArea: 0.0,
          grossFloorAreaUnit: "  ",
          billingCurrency: "   ",
          paymentTermForNSC: null,
          defectProvisionPercent: null,
          cpfApplicable: "0",
          cpfIndexName: null,
          cpfBaseYear: null,
          cpfBasePeriod: null,
          levyApplicable: "0",
          levyCITAPercent: 0.0,
          levyPCFBPercent: 0.0,
          expectedPCCDate: null,
          actualPCCDate: "2023-03-31",
          expectedMakingGoodDate: null,
          actualMakingGoodDate: null,
          defectLiabilityPeriod: 12,
          defectListIssuedDate: null,
          financialEndDate: null,
          dateFinalACSettlement: null,
          yearOfCompletion: 0,
          bqFinalizedFlag: " ",
          manualInputSCWD: "Y",
          legacyJob: null,
          conversionStatus: "Y",
          repackagingType: "1",
          finQS0Review: "D",
        },
        packageNo: "1001",
        description: "Ground Investigation Works",
        packageType: "S",
        packageStatus: null,
        subcontractorNature: "DSC",
        originalSubcontractSum: 6467155.0,
        approvedVOAmount: 14483292.44,
        remeasuredSubcontractSum: 6467155.0,
        approvalRoute: null,
        retentionTerms: "Percentage - Revised SC Sum",
        maxRetentionPercentage: 10.0,
        interimRentionPercentage: 10.0,
        mosRetentionPercentage: 10.0,
        retentionAmount: 2095044.74,
        accumlatedRetention: 1531883.08,
        retentionReleased: 0.0,
        paymentInformation: null,
        paymentCurrency: "HKD",
        exchangeRate: 1.0,
        paymentTerms: "QS2",
        subcontractTerm: "Re-measurement",
        cpfCalculation: "0",
        cpfBasePeriod: null,
        cpfBaseYear: null,
        formOfSubcontract: "Major",
        internalJobNo: null,
        paymentStatus: "I",
        submittedAddendum: " ",
        splitTerminateStatus: "0",
        paymentTermsDescription: null,
        notes: null,
        workscope: 201,
        nameSubcontractor: "Gaint Dragon Construction Engineering Ltd",
        scCreatedDate: null,
        latestAddendumValueUpdatedDate: "2022-07-25",
        firstPaymentCertIssuedDate: "2020-11-30",
        lastPaymentCertIssuedDate: "2022-08-16",
        finalPaymentIssuedDate: null,
        scAwardApprovalRequestSentDate: "2020-11-12",
        scApprovalDate: "2020-11-17",
        labourIncludedContract: true,
        plantIncludedContract: true,
        materialIncludedContract: true,
        totalPostedWorkDoneAmount: 21750288.02,
        totalCumWorkDoneAmount: 21750288.02,
        totalPostedCertifiedAmount: 15318830.8,
        totalCumCertifiedAmount: 16578535.72,
        totalCCPostedCertAmount: -28500.0,
        totalMOSPostedCertAmount: 0.0,
        totalAPPostedCertAmount: 0,
        totalRecoverableAmount: 14483292.44,
        totalNonRecoverableAmount: 0,
        requisitionApprovedDate: null,
        tenderAnalysisApprovedDate: "2020-06-12",
        preAwardMeetingDate: null,
        loaSignedDate: null,
        scDocScrDate: "2020-06-22",
        scDocLegalDate: null,
        workCommenceDate: "2020-06-15",
        onSiteStartDate: "2020-06-23",
        scFinalAccDraftDate: null,
        scFinalAccSignoffDate: null,
        paymentMethod: null,
        periodForPayment: null,
        amountPackageStretchTarget: null,
        reasonLoa: null,
        dateScExecutionTarget: null,
        executionMethodMainContract: null,
        executionMethodPropsed: null,
        durationFrom: null,
        durationTo: null,
        reasonQuotation: null,
        reasonManner: null,
        amtCEDApproved: 12540244.8,
        retentionBalance: 1531883.08,
        totalNetPostedCertifiedAmount: 13758447.72,
        paymentStatusText: "Interim",
        subcontractType: "Labour & Plant & Material",
        splitTerminateStatusText: "Not Submitted",
        totalProvisionAmount: 6431457.22,
        balanceToCompleteAmount: -799840.58,
        subcontractSum: 20950447.44,
        awarded: true,
        vendorNo: "400875",
        scStatus: 500,
      },
      amountSubcontract: 8410202.64,
      amountBudget: 0,
      balanceType: "",
      amountPostedWD: 8410202.64,
      postedWorkDoneQuantity: 8410202.64,
      amountCumulativeWD: 8410202.64,
      cumWorkDoneQuantity: 8410202.64,
      costRate: 0.0,
      toBeApprovedRate: 0.0,
      contraChargeSCNo: null,
      corrSCLineSeqNo: null,
      altObjectCode: null,
      toBeApprovedAmount: 0.0,
      sourceType: "A",
      totalAmount: 8410202.64,
      ivamount: 0.0,
      projectedProvision: 4371911.72,
      workDoneMovement: 0.0,
      provision: 5631616.64,
      toBeApprovedQuantity: 0.0,
      amountBudgetNew: 0.0,
    },
    {
      createdUser: "mioucheang",
      createdDate: "2020-11-25T02:20:24.000+00:00",
      lastModifiedUser: "SYSTEM",
      lastModifiedDate: "2022-08-25T17:11:13.000+00:00",
      systemStatus: "ACTIVE",
      id: 603329,
      jobNo: "13892",
      sequenceNo: 3,
      resourceNo: 0,
      billItem: "98/ /OA/0003",
      description: "Adjustment for SC Provision",
      quantity: 0.0,
      scRate: 1.0,
      objectCode: "140299",
      subsidiaryCode: "29999999",
      lineType: "OA",
      approved: "A",
      unit: "AM",
      remark: null,
      typeRecoverable: null,
      postedCertifiedQuantity: 0.0,
      cumCertifiedQuantity: 0.0,
      amountCumulativeCert: 0,
      amountPostedCert: 0,
      amountSubcontractNew: 0,
      newQuantity: 0.0,
      originalQuantity: 0.0,
      tenderAnalysisDetail_ID: null,
      subcontract: {
        createdUser: "victorhui",
        createdDate: "2020-11-12T03:41:58.000+00:00",
        lastModifiedUser: "victorhui",
        lastModifiedDate: "2022-09-02T06:47:40.000+00:00",
        systemStatus: "ACTIVE",
        id: 75852,
        jobInfo: {
          createdUser: "mioucheang",
          createdDate: "2020-07-03T07:59:15.000+00:00",
          lastModifiedUser: "IDT-KOEY",
          lastModifiedDate: "2022-09-05T13:45:09.000+00:00",
          systemStatus: "ACTIVE",
          id: 7870,
          budgetPosted: null,
          eotApplied: 0.0,
          eotAwarded: 848.0,
          ldExposureAmount: 0.0,
          residualAfterEot: 0.0,
          nameExecutiveDirector: null,
          nameDirector: null,
          nameDirectSupervisorPic: null,
          nameProjectInCharge: null,
          nameCommercialInCharge: null,
          nameTempWorkController: null,
          nameSafetyEnvRep: null,
          nameAuthorizedPerson: null,
          nameSiteAdmin1: null,
          nameSiteAdmin2: null,
          nameSiteManagement1: null,
          nameSiteManagement2: null,
          nameSiteManagement3: null,
          nameSiteManagement4: null,
          nameSiteSupervision1: null,
          nameSiteSupervision2: null,
          nameSiteSupervision3: null,
          nameSiteSupervision4: null,
          noReference: 0,
          statusApproval: null,
          projectFullDescription:
            "Airport Authority APM and BHS Tunnels and Related Works \nSub-Contract J3880/SC1302 - Ground Investigation",
          projectLocation: "Part of Three Runway System",
          natureOfWorkBB: null,
          natureOfWorkGammon: "F04",
          tenderNumber: "T19022",
          immediateParentJobNumber: null,
          ultimateParentJobNumber: null,
          ultimateClient: "31704",
          immediateClientBusinessSector: null,
          ultimateClientBusinessSector: null,
          clientType: null,
          engineerArchitect: null,
          beam: null,
          beamPlus: null,
          leed: null,
          innovationApplicable: "0",
          innovationPercent: null,
          paymentTermFromClient: null,
          provision: "N",
          isParentCompanyGuarantee: null,
          jobNo: "13892",
          description: "APM & BHS Tunnels - GI(S13880)",
          company: "00001",
          employer: "33540",
          contractType: "RMC",
          division: "FDN",
          department: "GE",
          internalJob: "FC",
          soloJV: "S",
          completionStatus: "1",
          insuranceCAR: " ",
          insuranceECI: " ",
          insuranceTPL: " ",
          clientContractNo: "Contract 3802",
          parentJobNo: "13892",
          jvPartnerNo: "0",
          jvPercentage: 0.0,
          originalContractValue: 3.4122665e7,
          projectedContractValue: 3.4122665e7,
          orginalNSCContractValue: 0.0,
          tenderGP: 1876746.58,
          forecastEndYear: 2022,
          forecastEndPeriod: 6,
          maxRetPercent: 5.0,
          interimRetPercent: 5.0,
          mosRetPercent: 5.0,
          valueOfBSWork: 0.0,
          grossFloorArea: 0.0,
          grossFloorAreaUnit: "  ",
          billingCurrency: "   ",
          paymentTermForNSC: null,
          defectProvisionPercent: null,
          cpfApplicable: "0",
          cpfIndexName: null,
          cpfBaseYear: null,
          cpfBasePeriod: null,
          levyApplicable: "0",
          levyCITAPercent: 0.0,
          levyPCFBPercent: 0.0,
          expectedPCCDate: null,
          actualPCCDate: "2023-03-31",
          expectedMakingGoodDate: null,
          actualMakingGoodDate: null,
          defectLiabilityPeriod: 12,
          defectListIssuedDate: null,
          financialEndDate: null,
          dateFinalACSettlement: null,
          yearOfCompletion: 0,
          bqFinalizedFlag: " ",
          manualInputSCWD: "Y",
          legacyJob: null,
          conversionStatus: "Y",
          repackagingType: "1",
          finQS0Review: "D",
        },
        packageNo: "1001",
        description: "Ground Investigation Works",
        packageType: "S",
        packageStatus: null,
        subcontractorNature: "DSC",
        originalSubcontractSum: 6467155.0,
        approvedVOAmount: 14483292.44,
        remeasuredSubcontractSum: 6467155.0,
        approvalRoute: null,
        retentionTerms: "Percentage - Revised SC Sum",
        maxRetentionPercentage: 10.0,
        interimRentionPercentage: 10.0,
        mosRetentionPercentage: 10.0,
        retentionAmount: 2095044.74,
        accumlatedRetention: 1531883.08,
        retentionReleased: 0.0,
        paymentInformation: null,
        paymentCurrency: "HKD",
        exchangeRate: 1.0,
        paymentTerms: "QS2",
        subcontractTerm: "Re-measurement",
        cpfCalculation: "0",
        cpfBasePeriod: null,
        cpfBaseYear: null,
        formOfSubcontract: "Major",
        internalJobNo: null,
        paymentStatus: "I",
        submittedAddendum: " ",
        splitTerminateStatus: "0",
        paymentTermsDescription: null,
        notes: null,
        workscope: 201,
        nameSubcontractor: "Gaint Dragon Construction Engineering Ltd",
        scCreatedDate: null,
        latestAddendumValueUpdatedDate: "2022-07-25",
        firstPaymentCertIssuedDate: "2020-11-30",
        lastPaymentCertIssuedDate: "2022-08-16",
        finalPaymentIssuedDate: null,
        scAwardApprovalRequestSentDate: "2020-11-12",
        scApprovalDate: "2020-11-17",
        labourIncludedContract: true,
        plantIncludedContract: true,
        materialIncludedContract: true,
        totalPostedWorkDoneAmount: 21750288.02,
        totalCumWorkDoneAmount: 21750288.02,
        totalPostedCertifiedAmount: 15318830.8,
        totalCumCertifiedAmount: 16578535.72,
        totalCCPostedCertAmount: -28500.0,
        totalMOSPostedCertAmount: 0.0,
        totalAPPostedCertAmount: 0,
        totalRecoverableAmount: 14483292.44,
        totalNonRecoverableAmount: 0,
        requisitionApprovedDate: null,
        tenderAnalysisApprovedDate: "2020-06-12",
        preAwardMeetingDate: null,
        loaSignedDate: null,
        scDocScrDate: "2020-06-22",
        scDocLegalDate: null,
        workCommenceDate: "2020-06-15",
        onSiteStartDate: "2020-06-23",
        scFinalAccDraftDate: null,
        scFinalAccSignoffDate: null,
        paymentMethod: null,
        periodForPayment: null,
        amountPackageStretchTarget: null,
        reasonLoa: null,
        dateScExecutionTarget: null,
        executionMethodMainContract: null,
        executionMethodPropsed: null,
        durationFrom: null,
        durationTo: null,
        reasonQuotation: null,
        reasonManner: null,
        amtCEDApproved: 12540244.8,
        retentionBalance: 1531883.08,
        totalNetPostedCertifiedAmount: 13758447.72,
        paymentStatusText: "Interim",
        subcontractType: "Labour & Plant & Material",
        splitTerminateStatusText: "Not Submitted",
        totalProvisionAmount: 6431457.22,
        balanceToCompleteAmount: -799840.58,
        subcontractSum: 20950447.44,
        awarded: true,
        vendorNo: "400875",
        scStatus: 500,
      },
      amountSubcontract: 0,
      amountBudget: 0,
      balanceType: "",
      amountPostedWD: 799840.58,
      postedWorkDoneQuantity: 799840.58,
      amountCumulativeWD: 799840.58,
      cumWorkDoneQuantity: 799840.58,
      projectedProvision: 799840.58,
      workDoneMovement: 0.0,
      provision: 799840.58,
      toBeApprovedRate: 0.0,
      toBeApprovedQuantity: 0.0,
      toBeApprovedAmount: 0.0,
      altObjectCode: "",
      totalAmount: 0.0,
      sourceType: "D",
      contraChargeSCNo: "",
      corrSCLineSeqNo: 0,
      ivamount: 0.0,
      costRate: 0.0,
    },
    {
      createdUser: "victorhui",
      createdDate: "2020-11-27T07:56:15.000+00:00",
      lastModifiedUser: "SYSTEM",
      lastModifiedDate: "2020-11-30T14:00:01.000+00:00",
      systemStatus: "ACTIVE",
      id: 603446,
      jobNo: "13892",
      sequenceNo: 4,
      resourceNo: 0,
      billItem: "99/ /C1/0004",
      description: "Fuel",
      quantity: 0.0,
      scRate: -1.0,
      objectCode: "139988",
      subsidiaryCode: "29019999",
      lineType: "C1",
      approved: "A",
      unit: "UN",
      remark: null,
      typeRecoverable: null,
      postedCertifiedQuantity: 0.0,
      cumCertifiedQuantity: 0.0,
      amountCumulativeCert: -28500,
      amountPostedCert: -28500,
      amountSubcontractNew: 0,
      newQuantity: 0.0,
      originalQuantity: 0.0,
      tenderAnalysisDetail_ID: null,
      subcontract: {
        createdUser: "victorhui",
        createdDate: "2020-11-12T03:41:58.000+00:00",
        lastModifiedUser: "victorhui",
        lastModifiedDate: "2022-09-02T06:47:40.000+00:00",
        systemStatus: "ACTIVE",
        id: 75852,
        jobInfo: {
          createdUser: "mioucheang",
          createdDate: "2020-07-03T07:59:15.000+00:00",
          lastModifiedUser: "IDT-KOEY",
          lastModifiedDate: "2022-09-05T13:45:09.000+00:00",
          systemStatus: "ACTIVE",
          id: 7870,
          budgetPosted: null,
          eotApplied: 0.0,
          eotAwarded: 848.0,
          ldExposureAmount: 0.0,
          residualAfterEot: 0.0,
          nameExecutiveDirector: null,
          nameDirector: null,
          nameDirectSupervisorPic: null,
          nameProjectInCharge: null,
          nameCommercialInCharge: null,
          nameTempWorkController: null,
          nameSafetyEnvRep: null,
          nameAuthorizedPerson: null,
          nameSiteAdmin1: null,
          nameSiteAdmin2: null,
          nameSiteManagement1: null,
          nameSiteManagement2: null,
          nameSiteManagement3: null,
          nameSiteManagement4: null,
          nameSiteSupervision1: null,
          nameSiteSupervision2: null,
          nameSiteSupervision3: null,
          nameSiteSupervision4: null,
          noReference: 0,
          statusApproval: null,
          projectFullDescription:
            "Airport Authority APM and BHS Tunnels and Related Works \nSub-Contract J3880/SC1302 - Ground Investigation",
          projectLocation: "Part of Three Runway System",
          natureOfWorkBB: null,
          natureOfWorkGammon: "F04",
          tenderNumber: "T19022",
          immediateParentJobNumber: null,
          ultimateParentJobNumber: null,
          ultimateClient: "31704",
          immediateClientBusinessSector: null,
          ultimateClientBusinessSector: null,
          clientType: null,
          engineerArchitect: null,
          beam: null,
          beamPlus: null,
          leed: null,
          innovationApplicable: "0",
          innovationPercent: null,
          paymentTermFromClient: null,
          provision: "N",
          isParentCompanyGuarantee: null,
          jobNo: "13892",
          description: "APM & BHS Tunnels - GI(S13880)",
          company: "00001",
          employer: "33540",
          contractType: "RMC",
          division: "FDN",
          department: "GE",
          internalJob: "FC",
          soloJV: "S",
          completionStatus: "1",
          insuranceCAR: " ",
          insuranceECI: " ",
          insuranceTPL: " ",
          clientContractNo: "Contract 3802",
          parentJobNo: "13892",
          jvPartnerNo: "0",
          jvPercentage: 0.0,
          originalContractValue: 3.4122665e7,
          projectedContractValue: 3.4122665e7,
          orginalNSCContractValue: 0.0,
          tenderGP: 1876746.58,
          forecastEndYear: 2022,
          forecastEndPeriod: 6,
          maxRetPercent: 5.0,
          interimRetPercent: 5.0,
          mosRetPercent: 5.0,
          valueOfBSWork: 0.0,
          grossFloorArea: 0.0,
          grossFloorAreaUnit: "  ",
          billingCurrency: "   ",
          paymentTermForNSC: null,
          defectProvisionPercent: null,
          cpfApplicable: "0",
          cpfIndexName: null,
          cpfBaseYear: null,
          cpfBasePeriod: null,
          levyApplicable: "0",
          levyCITAPercent: 0.0,
          levyPCFBPercent: 0.0,
          expectedPCCDate: null,
          actualPCCDate: "2023-03-31",
          expectedMakingGoodDate: null,
          actualMakingGoodDate: null,
          defectLiabilityPeriod: 12,
          defectListIssuedDate: null,
          financialEndDate: null,
          dateFinalACSettlement: null,
          yearOfCompletion: 0,
          bqFinalizedFlag: " ",
          manualInputSCWD: "Y",
          legacyJob: null,
          conversionStatus: "Y",
          repackagingType: "1",
          finQS0Review: "D",
        },
        packageNo: "1001",
        description: "Ground Investigation Works",
        packageType: "S",
        packageStatus: null,
        subcontractorNature: "DSC",
        originalSubcontractSum: 6467155.0,
        approvedVOAmount: 14483292.44,
        remeasuredSubcontractSum: 6467155.0,
        approvalRoute: null,
        retentionTerms: "Percentage - Revised SC Sum",
        maxRetentionPercentage: 10.0,
        interimRentionPercentage: 10.0,
        mosRetentionPercentage: 10.0,
        retentionAmount: 2095044.74,
        accumlatedRetention: 1531883.08,
        retentionReleased: 0.0,
        paymentInformation: null,
        paymentCurrency: "HKD",
        exchangeRate: 1.0,
        paymentTerms: "QS2",
        subcontractTerm: "Re-measurement",
        cpfCalculation: "0",
        cpfBasePeriod: null,
        cpfBaseYear: null,
        formOfSubcontract: "Major",
        internalJobNo: null,
        paymentStatus: "I",
        submittedAddendum: " ",
        splitTerminateStatus: "0",
        paymentTermsDescription: null,
        notes: null,
        workscope: 201,
        nameSubcontractor: "Gaint Dragon Construction Engineering Ltd",
        scCreatedDate: null,
        latestAddendumValueUpdatedDate: "2022-07-25",
        firstPaymentCertIssuedDate: "2020-11-30",
        lastPaymentCertIssuedDate: "2022-08-16",
        finalPaymentIssuedDate: null,
        scAwardApprovalRequestSentDate: "2020-11-12",
        scApprovalDate: "2020-11-17",
        labourIncludedContract: true,
        plantIncludedContract: true,
        materialIncludedContract: true,
        totalPostedWorkDoneAmount: 21750288.02,
        totalCumWorkDoneAmount: 21750288.02,
        totalPostedCertifiedAmount: 15318830.8,
        totalCumCertifiedAmount: 16578535.72,
        totalCCPostedCertAmount: -28500.0,
        totalMOSPostedCertAmount: 0.0,
        totalAPPostedCertAmount: 0,
        totalRecoverableAmount: 14483292.44,
        totalNonRecoverableAmount: 0,
        requisitionApprovedDate: null,
        tenderAnalysisApprovedDate: "2020-06-12",
        preAwardMeetingDate: null,
        loaSignedDate: null,
        scDocScrDate: "2020-06-22",
        scDocLegalDate: null,
        workCommenceDate: "2020-06-15",
        onSiteStartDate: "2020-06-23",
        scFinalAccDraftDate: null,
        scFinalAccSignoffDate: null,
        paymentMethod: null,
        periodForPayment: null,
        amountPackageStretchTarget: null,
        reasonLoa: null,
        dateScExecutionTarget: null,
        executionMethodMainContract: null,
        executionMethodPropsed: null,
        durationFrom: null,
        durationTo: null,
        reasonQuotation: null,
        reasonManner: null,
        amtCEDApproved: 12540244.8,
        retentionBalance: 1531883.08,
        totalNetPostedCertifiedAmount: 13758447.72,
        paymentStatusText: "Interim",
        subcontractType: "Labour & Plant & Material",
        splitTerminateStatusText: "Not Submitted",
        totalProvisionAmount: 6431457.22,
        balanceToCompleteAmount: -799840.58,
        subcontractSum: 20950447.44,
        awarded: true,
        vendorNo: "400875",
        scStatus: 500,
      },
      amountSubcontract: 0,
      amountBudget: 0,
      balanceType: "",
      contraChargeSCNo: null,
      altObjectCode: null,
      corrSCLineSeqNo: null,
      projectedProvision: 0.0,
      toBeApprovedRate: 0.0,
      toBeApprovedQuantity: 0.0,
      postedWorkDoneQuantity: 0.0,
      toBeApprovedAmount: 0.0,
      totalAmount: 0.0,
      sourceType: "D",
      ivamount: 0.0,
      costRate: 0.0,
      amountCumulativeWD: 0,
      amountPostedWD: 0,
      cumWorkDoneQuantity: 0.0,
      provision: 0.0,
    },
  ];
  return (
    <div className="admin-container">
      {/* input */}
      <div className="admin-header row">
        <div className="col-lg-4 col-md-4">
          <TextBoxComponent
            placeholder="Job Number"
            floatLabelType="Auto"
            cssClass="e-outline"
          />
        </div>
        <div className="col-lg-4 col-md-4">
          <NumericTextBoxComponent
            placeholder="Subcontract Number"
            floatLabelType="Auto"
            cssClass="e-outline"
          />
        </div>
        <div className="col-lg-4 col-md-4">
          <ButtonComponent cssClass="e-info search-btn">Search</ButtonComponent>
        </div>
      </div>
      <div className="admin-content">
        <GridComponent
          dataSource={data}
          allowPaging={true}
          width="100%"
          height="100%"
          allowExcelExport
          toolbar={toolbar}
        >
          <ColumnsDirective>
            <ColumnDirective
              field="id"
              headerText="ID"
              width="120"
            ></ColumnDirective>
            <ColumnDirective
              field="jobNo"
              headerText="Job Number"
              width="150"
            ></ColumnDirective>
            <ColumnDirective
              template={(e: any) => e.subcontract.id}
              headerText="Subcontract"
              width="150"
            />
            <ColumnDirective
              field="sequenceNo"
              headerText="Sequence Number"
              width="160"
            />
            <ColumnDirective
              template={(e: any) => (
                <TooltipComponent content={e.description}>
                  <div className="nowrap">{e.description}</div>
                </TooltipComponent>
              )}
              headerText="Description"
              width="200"
            ></ColumnDirective>
            <ColumnDirective
              template={(e: any) => (
                <TooltipComponent content={e.remark}>
                  <div className="nowrap">{e.remark}</div>
                </TooltipComponent>
              )}
              headerText="Remark"
              width="200"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="120"
            ></ColumnDirective>
            <ColumnDirective
              field="subsidiaryCode"
              headerText="Subsidiary Code"
              width="150"
            ></ColumnDirective>
            <ColumnDirective
              field="billItem"
              headerText="Bill Item"
              width="150"
            ></ColumnDirective>
            <ColumnDirective
              field="unit"
              headerText="Unit"
              width="80"
            ></ColumnDirective>
            <ColumnDirective
              field="lineType"
              headerText="Line Type"
              width="120"
            ></ColumnDirective>
            <ColumnDirective
              field="approved"
              headerText="Approved"
              width="120"
            ></ColumnDirective>
            <ColumnDirective
              field="resourceNo"
              headerText="Resource Number"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              template={(e: any) => (
                <div
                  className={
                    typeof e.scRate === "number" && e.scRate < 0
                      ? "text-red"
                      : ""
                  }
                >
                  {e.scRate.toFixed(4)}
                </div>
              )}
              format="n4"
              headerText="Subcontract Rate"
              width="120"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
            <ColumnDirective
              field="objectCode"
              headerText="Object Code"
              width="100"
            ></ColumnDirective>
          </ColumnsDirective>
          <Inject services={[Page, ExcelExport, Toolbar]} />
        </GridComponent>
      </div>
    </div>
  );
};

export default SubcontractDetail;
