ALTER session SET current_schema = PCMSDATADEV;

-- 1. Create Consultancy Agreement table
CREATE TABLE CONSULTANCY_AGREEMENT
(
    ID                 NUMBER(19) NOT NULL ENABLE
        constraint CONSULTANCY_AGREEMENT_PK
        primary key,
    ID_SUBCONTRACT     NUMBER(19) NOT NULL ENABLE,
    REF                VARCHAR2(20 CHAR),
    DATE_SUBMISSION    DATE,
    FROM_LIST          VARCHAR2(200 CHAR),
    TO_LIST            VARCHAR2(200 CHAR),
    CC_LIST            VARCHAR2(200 CHAR),
    SUBJECT            VARCHAR2(500 CHAR),
    CONSULTANT_NAME    VARCHAR2(250 CHAR),
    DESCRIPTION        VARCHAR2(1000 CHAR),
    PERIOD             VARCHAR2(100 CHAR),
    FEE_ESTIMATE       NUMBER(19, 2),
    BUDGET_AMOUNT      NUMBER(19, 2),
    EXPLANATION        VARCHAR2(1000 CHAR),
    DATE_APPROVAL      DATE,
    STATUS_APPROVAL    VARCHAR2(20 char),
    LAST_MODIFIED_DATE DATE NOT NULL ENABLE,
    LAST_MODIFIED_USER VARCHAR2(50 CHAR),
    CREATED_DATE       DATE NOT NULL ENABLE,
    CREATED_USER       VARCHAR2(50 CHAR) NOT NULL ENABLE,
    SYSTEM_STATUS      VARCHAR2(20 CHAR) NOT NULL ENABLE
);

CREATE TABLE CONSULTANCY_AGREEMENT_AUDIT
(
    ID                 NUMBER(19) NOT NULL ENABLE,
    "REV"              NUMBER(10,0) NOT NULL ENABLE,
    "REVTYPE"          NUMBER(3,0),
    ID_SUBCONTRACT     NUMBER(19) NOT NULL ENABLE,
    REF                VARCHAR2(20 CHAR),
    DATE_SUBMISSION    DATE,
    FROM_LIST          VARCHAR2(200 CHAR),
    TO_LIST            VARCHAR2(200 CHAR),
    CC_LIST            VARCHAR2(200 CHAR),
    SUBJECT            VARCHAR2(500 CHAR),
    CONSULTANT_NAME    VARCHAR2(250 CHAR),
    DESCRIPTION        VARCHAR2(1000 CHAR),
    PERIOD             VARCHAR2(100 CHAR),
    FEE_ESTIMATE       NUMBER(19, 2),
    BUDGET_AMOUNT      NUMBER(19, 2),
    EXPLANATION        VARCHAR2(1000 CHAR),
    DATE_APPROVAL      DATE,
    STATUS_APPROVAL    VARCHAR2(20 char),
    LAST_MODIFIED_DATE DATE NOT NULL ENABLE,
    LAST_MODIFIED_USER VARCHAR2(50 CHAR),
    CREATED_DATE       DATE NOT NULL ENABLE,
    CREATED_USER       VARCHAR2(50 CHAR) NOT NULL ENABLE,
    SYSTEM_STATUS      VARCHAR2(20 CHAR) NOT NULL ENABLE
);

CREATE sequence CONSULTANCY_AGREEMENT_SEQ minvalue 1 nocache ;

-- 2. grant necessary privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSULTANCY_AGREEMENT TO pcmsuser_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSULTANCY_AGREEMENT_AUDIT TO pcmsuser_role;
GRANT SELECT ON CONSULTANCY_AGREEMENT_SEQ TO pcmsuser_role;

commit;
