-- SUBCONTRACT_SNAPSHOT
ALTER TABLE PCMSDATAPROD.SUBCONTRACT_SNAPSHOT
	ADD (
  	NAME_SUBCONTRACTOR VARCHAR2(500) DEFAULT ' ',
    NOTES VARCHAR2(1000) DEFAULT ' ',
    WORK_SCOPE NUMBER(19,0)
    );
    
UPDATE PCMSDATAPROD.SUBCONTRACT_SNAPSHOT ss
SET ( NAME_SUBCONTRACTOR, NOTES, WORK_SCOPE, LAST_MODIFIED_USER, LAST_MODIFIED_DATE) = 
(select NAME_SUBCONTRACTOR, NOTES, WORK_SCOPE, 'IMS' AS LAST_MODIFIED_USER, sysdate AS LAST_MODIFIED_DATE 
from PCMSDATADEV.SUBCONTRACT s where s.id = ss.SUBCONTRACT_ID);
