ALTER session SET current_schema = PCMSDATADEV;

CREATE TABLE ROC_CUTOFF_PERIOD
(
    ID                 NUMBER(19) NOT NULL ENABLE,
    CUTOFF_DATE          DATE NOT NULL ENABLE,
    PERIOD               VARCHAR2(10 CHAR) NOT NULL ENABLE,
    LAST_MODIFIED_DATE DATE NOT NULL ENABLE,
    LAST_MODIFIED_USER VARCHAR2(50),
    CREATED_DATE       DATE NOT NULL ENABLE,
    CREATED_USER       VARCHAR2(50) NOT NULL ENABLE,
    SYSTEM_STATUS      VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "ROC_CUTOFF_PERIOD_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);


CREATE TABLE ROC_CUTOFF_PERIOD_AUDIT
(
    "ID"                 NUMBER(19,0) NOT NULL ENABLE,
    "REV"                NUMBER(10,0) NOT NULL ENABLE,
    "REVTYPE"            NUMBER(3,0),
    "CUTOFF_DATE"        DATE NOT NULL ENABLE,
    "PERIOD"             VARCHAR2(10 CHAR) NOT NULL ENABLE,
    "LAST_MODIFIED_DATE" DATE NOT NULL ENABLE,
    "LAST_MODIFIED_USER" VARCHAR2(50 BYTE),
    "CREATED_DATE"       DATE NOT NULL ENABLE,
    "CREATED_USER"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SYSTEM_STATUS"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ROC_CO_AUDIT_ID_NN" CHECK ("ID"   IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_CO_AUDIT_REV_NN" CHECK ("REV" IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_CO_AUDIT_PK" PRIMARY KEY ("ID", "REV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE sequence ROC_CUTOFF_SEQ minvalue 1 nocache ;

GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_CUTOFF_PERIOD TO pcmsuser_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_CUTOFF_PERIOD_AUDIT TO pcmsuser_role;

GRANT SELECT ON ROC_CUTOFF_SEQ TO pcmsuser_role;

INSERT INTO ROC_CUTOFF_PERIOD (ID, CUTOFF_DATE, PERIOD, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS)
VALUES (ROC_CUTOFF_SEQ.nextval, TO_DATE('2021-12-07', 'YYYY-MM-DD HH24:MI:SS'), '2021-11' , sysdate, 'SYSTEM', sysdate, 'SYSTEM', 'ACTIVE');
