ALTER TABLE SUBCONTRACT 
ADD (PAYMENT_METHOD VARCHAR2(50) );

ALTER TABLE SUBCONTRACT 
ADD (PERIOD_FOR_PAYMENT VARCHAR2(100) );

ALTER TABLE SUBCONTRACT 
ADD (AMOUNT_PACKAGE_STRETCH_TARGET NUMBER );

ALTER TABLE SUBCONTRACT 
ADD (DATE_SC_EXECUTION_TARGET DATE );

ALTER TABLE SUBCONTRACT 
ADD (EXECUTION_METHOD_MAIN_CONTRACT VARCHAR2(500) );

ALTER TABLE SUBCONTRACT 
ADD (EXECUTION_METHOD_PROPOSED VARCHAR2(500) );

ALTER TABLE SUBCONTRACT 
ADD (DURATION_FROM DATE );

ALTER TABLE SUBCONTRACT 
ADD (DURATION_TO DATE );

ALTER TABLE SUBCONTRACT 
ADD (REASON_LOA VARCHAR2(500) );

ALTER TABLE SUBCONTRACT 
ADD (REASON_QUOTATION VARCHAR2(500) );

ALTER TABLE SUBCONTRACT 
ADD (REASON_MANNER VARCHAR2(500) );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (PAYMENT_METHOD VARCHAR2(50) );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (PERIOD_FOR_PAYMENT VARCHAR2(100) );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (AMOUNT_PACKAGE_STRETCH_TARGET NUMBER );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (DATE_SC_EXECUTION_TARGET DATE );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (EXECUTION_METHOD_MAIN_CONTRACT VARCHAR2(500) );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (EXECUTION_METHOD_PROPOSED VARCHAR2(500) );

ALTER TABLE SUBCONTRACT_AUDIT
ADD (DURATION_FROM DATE );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (DURATION_TO DATE );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (REASON_LOA VARCHAR2(500) );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (REASON_QUOTATION VARCHAR2(500) );

ALTER TABLE SUBCONTRACT_AUDIT 
ADD (REASON_MANNER VARCHAR2(500) );
