ALTER session SET current_schema = PCMSDATADEV;

alter table PAYMENT_CERT add VENDORNO VARCHAR2(255);
alter table PAYMENT_CERT add EXPLANATION VARCHAR2(500 char);

alter table PAYMENT_CERT_AUDIT add VENDORNO VARCHAR2(255);
alter table PAYMENT_CERT_AUDIT add EXPLANATION VARCHAR2(500 char);
