ALTER TABLE Pcmsdatauat.job_info
MODIFY PROJECT_FULL_DESCRIPTION VARCHAR2(2500 CHAR);

ALTER TABLE Pcmsdatauat.job_info
MODIFY NATURE_OF_WORK_BB VARCHAR2(50 CHAR);

ALTER TABLE Pcmsdatauat.job_info
MODIFY BEAM VARCHAR2(100 CHAR);

ALTER TABLE Pcmsdatauat.job_info
MODIFY BEAM_PLUS VARCHAR2(100 CHAR);

ALTER TABLE Pcmsdatauat.job_info
MODIFY LEED VARCHAR2(100 CHAR);

ALTER TABLE Pcmsdatauat.JOB_INFO
DROP COLUMN CLIENT_IMME;



ALTER TABLE Pcmsdatauat.job_info_audit
MODIFY PROJECT_FULL_DESCRIPTION VARCHAR2(2500 CHAR);

ALTER TABLE Pcmsdatauat.job_info_audit
MODIFY NATURE_OF_WORK_BB VARCHAR2(50 CHAR);

ALTER TABLE Pcmsdatauat.job_info_audit
MODIFY BEAM VARCHAR2(100 CHAR);

ALTER TABLE Pcmsdatauat.job_info_audit
MODIFY BEAM_PLUS VARCHAR2(100 CHAR);

ALTER TABLE Pcmsdatauat.job_info_audit
MODIFY LEED VARCHAR2(100 CHAR);

ALTER TABLE Pcmsdatauat.JOB_INFO_AUDIT 
DROP COLUMN CLIENT_IMME;

