insert into ACDATAUAT.AC_USERPROFILE(
CREATIONDATE,
EMAILADDRESS,
GAMMONUSER,
LASTMODIFYDATE,
LASTMODIFYUSER,
STAFFID,
STATUS,
TEMPLATE,
USERADACCOUNT,
USERNAME)
(select
	CREATED_DATE as CREATIONDATE,
	EMAIL as EMAILADDRESS,
	'Y' as GAMMONUSER,
	LAST_MODIFIED_DATE as LASTMODIFYDATE,
	case when LAST_MODIFIED_USER = 'SYSTEM' then LAST_MODIFIED_USER
	else 'gamska\' || LAST_MODIFIED_USER end as LASTMODIFYUSER,
	case
		when ADDRESS_BOOK_NUMBER is not null then ADDRESS_BOOK_NUMBER
		else 0 END as STAFFID,
	'A' as STATUS,
	'N' as TEMPLATE,
	'gamska\' || USERNAME as USERADACCOUNT,
	case 
		when FULLNAME is not null then FULLNAME 
		else USERNAME END as USERNAME
	from QSADMINUAT.QS_APP_USER
	where
	SYSTEM_STATUS = 'ACTIVE'
	and 'gamska\'||username not in (select useradaccount from ACDATAUAT.AC_USERPROFILE)
);
