insert into ACDATAUAT.AC_USERSECURITY(
	USERADACCOUNT,
	APPLICATIONCODE,
	LASTMODIFYDATE,
	LASTMODIFYUSER,
	ROLENAME
)
select 
	QS.USERADACCOUNT,
	MAX(QS.APPLICATIONCODE) as APPLICATIONCODE, 
	MAX(QS.LASTMODIFYDATE) as LASTMODIFYDATE, 
	MAX(QS.LASTMODIFYUSER) LASTMODIFYUSER, 
	NEW_ROLE.PCMS_ROLE as ROLENAME
from 
	(select
		'gamska\'|| u.username as USERADACCOUNT, 
		'PCMS' as APPLICATIONCODE,
		ua.name,
		ua.LAST_MODIFIED_DATE as LASTMODIFYDATE,
		case 
			when ua.LAST_MODIFIED_USER = 'SYSTEM' then ua.LAST_MODIFIED_USER
			else 'gamska\' || ua.LAST_MODIFIED_USER end as LASTMODIFYUSER
	from 
	QSADMIN.QS_APP_USER u left join QSADMIN.QS_LINK_USER_AUTHORITY lua on u.id = lua.user_id 
	left join QSADMIN.QS_APP_AUTHORITY ua on lua.AUTHORITY_ID = ua.id
	where 
	u.SYSTEM_STATUS = 'ACTIVE' and
	ua.name like 'JOB%' or
	ua.name in('ROLE_QS_ENQUIRY', 'ROLE_QS_QS', 'ROLE_QS_APPROVER', 'ROLE_QS_IMS_ADM', 'ROLE_QS_ADMIN')
	) QS
	left join (
		SELECT 'ROLE_QS_ENQUIRY' as QS_ROLE , 'ROLE_PCMS_ENQ' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_QS' as QS_ROLE , 'ROLE_PCMS_ENQ' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_QS' as QS_ROLE , 'ROLE_PCMS_QS' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_APPROVER' as QS_ROLE , 'ROLE_PCMS_ENQ' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_APPROVER' as QS_ROLE , 'ROLE_PCMS_QS_REVIEWER' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_IMS_ADM' as QS_ROLE , 'ROLE_PCMS_ENQ' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_IMS_ADM' as QS_ROLE , 'ROLE_PCMS_IMS_ENQ' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_IMS_ADM' as QS_ROLE , 'ROLE_PCMS_IMS_ADMIN' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_ADMIN' as QS_ROLE , 'ROLE_PCMS_ENQ' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_ADMIN' as QS_ROLE , 'ROLE_PCMS_QS_ENQ' as PCMS_ROLE FROM DUAL UNION
		SELECT 'ROLE_QS_ADMIN' as QS_ROLE , 'ROLE_PCMS_QS_ADMIN' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_ALL' as QS_ROLE , 'JOB_ALL' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_SGP' as QS_ROLE , 'JOB_SGP' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_TAMAR' as QS_ROLE , 'JOB_TAMAR' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_TAMAR_EM' as QS_ROLE , 'JOB_TAMAR_EM' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_EM_CLP' as QS_ROLE , 'JOB_EM_CLP' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_HKG' as QS_ROLE , 'JOB_HKG' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_CX' as QS_ROLE , 'JOB_CX' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_GLJV' as QS_ROLE , 'JOB_GLJV' as PCMS_ROLE FROM DUAL UNION
		SELECT 'JOB_SCL1111' as QS_ROLE , 'JOB_SCL1111' as PCMS_ROLE FROM DUAL
	) NEW_ROLE on QS.NAME = NEW_ROLE.QS_ROLE
	group by QS.USERADACCOUNT, NEW_ROLE.PCMS_ROLE;
	
	Insert into ACDATAUAT.AC_USERSECURITY (USERADACCOUNT,APPLICATIONCODE,ROLENAME,LASTMODIFYDATE,LASTMODIFYUSER) values ('gamska\tikywong','PCMS','ROLE_PCMS_IMS_ENQ',sysdate,'SYSTEM');
	Insert into ACDATAUAT.AC_USERSECURITY (USERADACCOUNT,APPLICATIONCODE,ROLENAME,LASTMODIFYDATE,LASTMODIFYUSER) values ('gamska\koeyyeung','PCMS','ROLE_PCMS_IMS_ENQ',sysdate,'SYSTEM');
	Insert into ACDATAUAT.AC_USERSECURITY (USERADACCOUNT,APPLICATIONCODE,ROLENAME,LASTMODIFYDATE,LASTMODIFYUSER) values ('gamska\paulnpyiu','PCMS','ROLE_PCMS_IMS_ENQ',sysdate,'SYSTEM');
	Insert into ACDATAUAT.AC_USERSECURITY (USERADACCOUNT,APPLICATIONCODE,ROLENAME,LASTMODIFYDATE,LASTMODIFYUSER) values ('gamska\vincentmok','PCMS','ROLE_PCMS_IMS_ENQ',sysdate,'SYSTEM');
	
