CREATE SEQUENCE PCMSDATADEV.QA_SEQ INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;

CREATE TABLE PCMSDATADEV.QA (
	ID NUMBER(19,0) NOT NULL,
	ID_TABLE NUMBER(19,0) NOT NULL,
	NAME_TABLE VARCHAR2(30) NOT NULL,
	FIELD VARCHAR2(100) NOT NULL,
	SENDER VARCHAR2(100) NOT NULL,
	MESSAGE VARCHAR2(4000) NOT NULL,
	DATE_SENT DATE NOT NULL,
	USERNAME_CREATED VARCHAR2(20) NOT NULL,
	DATE_CREATED DATE NOT NULL,
	USERNAME_LAST_MODIFIED VARCHAR2(20),
	DATE_LAST_MODIFIED DATE,
	CONSTRAINT QA_PK PRIMARY KEY (ID)
);

CREATE TABLE PCMSDATADEV.QA_AUDIT (
 	"REV" NUMBER(10,0) NOT NULL ENABLE, 
	"REVTYPE" NUMBER(3,0) NOT NULL ENABLE, 
	ID NUMBER(19,0) NOT NULL,
	ID_TABLE NUMBER(19,0) NOT NULL,
	NAME_TABLE VARCHAR2(30) NOT NULL,
	FIELD VARCHAR2(100) NOT NULL,
	SENDER VARCHAR2(100) NOT NULL,
	MESSAGE VARCHAR2(4000) NOT NULL,
	DATE_SENT DATE NOT NULL,
	USERNAME_CREATED VARCHAR2(20) NOT NULL,
	DATE_CREATED DATE NOT NULL,
	USERNAME_LAST_MODIFIED VARCHAR2(20),
	DATE_LAST_MODIFIED DATE
);


grant select on PCMSDATADEV.QA_SEQ to pcmsuser_role;
grant select, insert, update, delete on PCMSDATADEV.QA to pcmsuser_role;
grant select, insert, update, delete on PCMSDATADEV.QA_AUDIT to pcmsuser_role;