package com.gammon.pcms.model.adl;
// Generated Jul 25, 2016 6:30:47 PM by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DimAddressBook generated by hbm2java
 */
@Entity
@Table(name = "DIM_ADDRESS_BOOK")
public class AddressBook implements java.io.Serializable {

	private static final long serialVersionUID = -395660491296207763L;
	
	public static final String TYPE_VENDOR = "V  ";
	public static final String TYPE_CLIENT = "C  ";
	
	private BigDecimal addressBookNumber;
	private String addressBookName;
	private String businessRegistrationNumber;
	private String securityBu;
	private String vendorApprStatusCode;
	private String vendorApprovalStatus;
	private String addressBookTypeCode;
	private String addrBookType;
	private String supplierApprovalCode;
	private String supplierApproval;
	private String subcontractorApprovalCode;
	private String subcontractorApproval;
	private String vendorTypeCode;
	private String vendorType;
	private String clientGroupCode;
	private String clientGroup;
	private String vendorStatusCode;
	private String vendorStatus;
	private String holdCode;
	private String hold;
	private String vmsExemptedCode;
	private String vmsExempted;
	private String proposedVendorCode;
	private String proposedVendor;
	private String businessSectorCode;
	private String businessSector;

	public AddressBook() {
	}

	public AddressBook(BigDecimal addressBookNumber, String addressBookName, String businessRegistrationNumber,
			String securityBu, String vendorApprStatusCode, String vendorApprovalStatus, String addressBookTypeCode,
			String addrBookType, String supplierApprovalCode, String supplierApproval, String subcontractorApprovalCode,
			String subcontractorApproval, String vendorTypeCode, String vendorType, String clientGroupCode,
			String clientGroup, String vendorStatusCode, String vendorStatus, String holdCode, String hold,
			String vmsExemptedCode, String vmsExempted, String proposedVendorCode, String proposedVendor,
			String businessSectorCode, String businessSector) {
		this.addressBookNumber = addressBookNumber;
		this.addressBookName = addressBookName;
		this.businessRegistrationNumber = businessRegistrationNumber;
		this.securityBu = securityBu;
		this.vendorApprStatusCode = vendorApprStatusCode;
		this.vendorApprovalStatus = vendorApprovalStatus;
		this.addressBookTypeCode = addressBookTypeCode;
		this.addrBookType = addrBookType;
		this.supplierApprovalCode = supplierApprovalCode;
		this.supplierApproval = supplierApproval;
		this.subcontractorApprovalCode = subcontractorApprovalCode;
		this.subcontractorApproval = subcontractorApproval;
		this.vendorTypeCode = vendorTypeCode;
		this.vendorType = vendorType;
		this.clientGroupCode = clientGroupCode;
		this.clientGroup = clientGroup;
		this.vendorStatusCode = vendorStatusCode;
		this.vendorStatus = vendorStatus;
		this.holdCode = holdCode;
		this.hold = hold;
		this.vmsExemptedCode = vmsExemptedCode;
		this.vmsExempted = vmsExempted;
		this.proposedVendorCode = proposedVendorCode;
		this.proposedVendor = proposedVendor;
		this.businessSectorCode = businessSectorCode;
		this.businessSector = businessSector;
	}

	@Id
	@Column(name = "ADDRESS_BOOK_NUMBER", precision = 22, scale = 0)
	public BigDecimal getAddressBookNumber() {
		return this.addressBookNumber;
	}

	public void setAddressBookNumber(BigDecimal addressBookNumber) {
		this.addressBookNumber = addressBookNumber;
	}

	@Column(name = "ADDRESS_BOOK_NAME", length = 160)
	public String getAddressBookName() {
		return this.addressBookName;
	}

	public void setAddressBookName(String addressBookName) {
		this.addressBookName = addressBookName;
	}

	@Column(name = "BUSINESS_REGISTRATION_NUMBER", length = 80)
	public String getBusinessRegistrationNumber() {
		return this.businessRegistrationNumber;
	}

	public void setBusinessRegistrationNumber(String businessRegistrationNumber) {
		this.businessRegistrationNumber = businessRegistrationNumber;
	}

	@Column(name = "SECURITY_BU", length = 48)
	public String getSecurityBu() {
		return this.securityBu;
	}

	public void setSecurityBu(String securityBu) {
		this.securityBu = securityBu;
	}

	@Column(name = "VENDOR_APPR_STATUS_CODE", length = 40)
	public String getVendorApprStatusCode() {
		return this.vendorApprStatusCode;
	}

	public void setVendorApprStatusCode(String vendorApprStatusCode) {
		this.vendorApprStatusCode = vendorApprStatusCode;
	}

	@Column(name = "VENDOR_APPROVAL_STATUS", length = 244)
	public String getVendorApprovalStatus() {
		return this.vendorApprovalStatus;
	}

	public void setVendorApprovalStatus(String vendorApprovalStatus) {
		this.vendorApprovalStatus = vendorApprovalStatus;
	}

	@Column(name = "ADDRESS_BOOK_TYPE_CODE", length = 12)
	public String getAddressBookTypeCode() {
		return this.addressBookTypeCode;
	}

	public void setAddressBookTypeCode(String addressBookTypeCode) {
		this.addressBookTypeCode = addressBookTypeCode;
	}

	@Column(name = "ADDR_BOOK_TYPE", length = 244)
	public String getAddrBookType() {
		return this.addrBookType;
	}

	public void setAddrBookType(String addrBookType) {
		this.addrBookType = addrBookType;
	}

	@Column(name = "SUPPLIER_APPROVAL_CODE", length = 12)
	public String getSupplierApprovalCode() {
		return this.supplierApprovalCode;
	}

	public void setSupplierApprovalCode(String supplierApprovalCode) {
		this.supplierApprovalCode = supplierApprovalCode;
	}

	@Column(name = "SUPPLIER_APPROVAL", length = 244)
	public String getSupplierApproval() {
		return this.supplierApproval;
	}

	public void setSupplierApproval(String supplierApproval) {
		this.supplierApproval = supplierApproval;
	}

	@Column(name = "SUBCONTRACTOR_APPROVAL_CODE", length = 12)
	public String getSubcontractorApprovalCode() {
		return this.subcontractorApprovalCode;
	}

	public void setSubcontractorApprovalCode(String subcontractorApprovalCode) {
		this.subcontractorApprovalCode = subcontractorApprovalCode;
	}

	@Column(name = "SUBCONTRACTOR_APPROVAL", length = 244)
	public String getSubcontractorApproval() {
		return this.subcontractorApproval;
	}

	public void setSubcontractorApproval(String subcontractorApproval) {
		this.subcontractorApproval = subcontractorApproval;
	}

	@Column(name = "VENDOR_TYPE_CODE", length = 12)
	public String getVendorTypeCode() {
		return this.vendorTypeCode;
	}

	public void setVendorTypeCode(String vendorTypeCode) {
		this.vendorTypeCode = vendorTypeCode;
	}

	@Column(name = "VENDOR_TYPE", length = 244)
	public String getVendorType() {
		return this.vendorType;
	}

	public void setVendorType(String vendorType) {
		this.vendorType = vendorType;
	}

	@Column(name = "CLIENT_GROUP_CODE", length = 12)
	public String getClientGroupCode() {
		return this.clientGroupCode;
	}

	public void setClientGroupCode(String clientGroupCode) {
		this.clientGroupCode = clientGroupCode;
	}

	@Column(name = "CLIENT_GROUP", length = 244)
	public String getClientGroup() {
		return this.clientGroup;
	}

	public void setClientGroup(String clientGroup) {
		this.clientGroup = clientGroup;
	}

	@Column(name = "VENDOR_STATUS_CODE", length = 12)
	public String getVendorStatusCode() {
		return this.vendorStatusCode;
	}

	public void setVendorStatusCode(String vendorStatusCode) {
		this.vendorStatusCode = vendorStatusCode;
	}

	@Column(name = "VENDOR_STATUS", length = 244)
	public String getVendorStatus() {
		return this.vendorStatus;
	}

	public void setVendorStatus(String vendorStatus) {
		this.vendorStatus = vendorStatus;
	}

	@Column(name = "HOLD_CODE", length = 12)
	public String getHoldCode() {
		return this.holdCode;
	}

	public void setHoldCode(String holdCode) {
		this.holdCode = holdCode;
	}

	@Column(name = "HOLD", length = 244)
	public String getHold() {
		return this.hold;
	}

	public void setHold(String hold) {
		this.hold = hold;
	}

	@Column(name = "VMS_EXEMPTED_CODE", length = 12)
	public String getVmsExemptedCode() {
		return this.vmsExemptedCode;
	}

	public void setVmsExemptedCode(String vmsExemptedCode) {
		this.vmsExemptedCode = vmsExemptedCode;
	}

	@Column(name = "VMS_EXEMPTED", length = 244)
	public String getVmsExempted() {
		return this.vmsExempted;
	}

	public void setVmsExempted(String vmsExempted) {
		this.vmsExempted = vmsExempted;
	}

	@Column(name = "PROPOSED_VENDOR_CODE", length = 12)
	public String getProposedVendorCode() {
		return this.proposedVendorCode;
	}

	public void setProposedVendorCode(String proposedVendorCode) {
		this.proposedVendorCode = proposedVendorCode;
	}

	@Column(name = "PROPOSED_VENDOR", length = 244)
	public String getProposedVendor() {
		return this.proposedVendor;
	}

	public void setProposedVendor(String proposedVendor) {
		this.proposedVendor = proposedVendor;
	}

	@Column(name = "BUSINESS_SECTOR_CODE", length = 12)
	public String getBusinessSectorCode() {
		return this.businessSectorCode;
	}

	public void setBusinessSectorCode(String businessSectorCode) {
		this.businessSectorCode = businessSectorCode;
	}

	@Column(name = "BUSINESS_SECTOR", length = 244)
	public String getBusinessSector() {
		return this.businessSector;
	}

	public void setBusinessSector(String businessSector) {
		this.businessSector = businessSector;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressBook))
			return false;
		AddressBook castOther = (AddressBook) other;

		return ((this.getAddressBookNumber() == castOther.getAddressBookNumber())
				|| (this.getAddressBookNumber() != null && castOther.getAddressBookNumber() != null
						&& this.getAddressBookNumber().equals(castOther.getAddressBookNumber())))
				&& ((this.getAddressBookName() == castOther.getAddressBookName())
						|| (this.getAddressBookName() != null && castOther.getAddressBookName() != null
								&& this.getAddressBookName().equals(castOther.getAddressBookName())))
				&& ((this.getBusinessRegistrationNumber() == castOther.getBusinessRegistrationNumber())
						|| (this.getBusinessRegistrationNumber() != null
								&& castOther.getBusinessRegistrationNumber() != null
								&& this.getBusinessRegistrationNumber()
										.equals(castOther.getBusinessRegistrationNumber())))
				&& ((this.getSecurityBu() == castOther.getSecurityBu()) || (this.getSecurityBu() != null
						&& castOther.getSecurityBu() != null && this.getSecurityBu().equals(castOther.getSecurityBu())))
				&& ((this.getVendorApprStatusCode() == castOther.getVendorApprStatusCode())
						|| (this.getVendorApprStatusCode() != null && castOther.getVendorApprStatusCode() != null
								&& this.getVendorApprStatusCode().equals(castOther.getVendorApprStatusCode())))
				&& ((this.getVendorApprovalStatus() == castOther.getVendorApprovalStatus())
						|| (this.getVendorApprovalStatus() != null && castOther.getVendorApprovalStatus() != null
								&& this.getVendorApprovalStatus().equals(castOther.getVendorApprovalStatus())))
				&& ((this.getAddressBookTypeCode() == castOther.getAddressBookTypeCode())
						|| (this.getAddressBookTypeCode() != null && castOther.getAddressBookTypeCode() != null
								&& this.getAddressBookTypeCode().equals(castOther.getAddressBookTypeCode())))
				&& ((this.getAddrBookType() == castOther.getAddrBookType())
						|| (this.getAddrBookType() != null && castOther.getAddrBookType() != null
								&& this.getAddrBookType().equals(castOther.getAddrBookType())))
				&& ((this.getSupplierApprovalCode() == castOther.getSupplierApprovalCode())
						|| (this.getSupplierApprovalCode() != null && castOther.getSupplierApprovalCode() != null
								&& this.getSupplierApprovalCode().equals(castOther.getSupplierApprovalCode())))
				&& ((this.getSupplierApproval() == castOther.getSupplierApproval())
						|| (this.getSupplierApproval() != null && castOther.getSupplierApproval() != null
								&& this.getSupplierApproval().equals(castOther.getSupplierApproval())))
				&& ((this.getSubcontractorApprovalCode() == castOther.getSubcontractorApprovalCode())
						|| (this.getSubcontractorApprovalCode() != null
								&& castOther.getSubcontractorApprovalCode() != null
								&& this.getSubcontractorApprovalCode()
										.equals(castOther.getSubcontractorApprovalCode())))
				&& ((this.getSubcontractorApproval() == castOther.getSubcontractorApproval())
						|| (this.getSubcontractorApproval() != null && castOther.getSubcontractorApproval() != null
								&& this.getSubcontractorApproval().equals(castOther.getSubcontractorApproval())))
				&& ((this.getVendorTypeCode() == castOther.getVendorTypeCode())
						|| (this.getVendorTypeCode() != null && castOther.getVendorTypeCode() != null
								&& this.getVendorTypeCode().equals(castOther.getVendorTypeCode())))
				&& ((this.getVendorType() == castOther.getVendorType()) || (this.getVendorType() != null
						&& castOther.getVendorType() != null && this.getVendorType().equals(castOther.getVendorType())))
				&& ((this.getClientGroupCode() == castOther.getClientGroupCode())
						|| (this.getClientGroupCode() != null && castOther.getClientGroupCode() != null
								&& this.getClientGroupCode().equals(castOther.getClientGroupCode())))
				&& ((this.getClientGroup() == castOther.getClientGroup())
						|| (this.getClientGroup() != null && castOther.getClientGroup() != null
								&& this.getClientGroup().equals(castOther.getClientGroup())))
				&& ((this.getVendorStatusCode() == castOther.getVendorStatusCode())
						|| (this.getVendorStatusCode() != null && castOther.getVendorStatusCode() != null
								&& this.getVendorStatusCode().equals(castOther.getVendorStatusCode())))
				&& ((this.getVendorStatus() == castOther.getVendorStatus())
						|| (this.getVendorStatus() != null && castOther.getVendorStatus() != null
								&& this.getVendorStatus().equals(castOther.getVendorStatus())))
				&& ((this.getHoldCode() == castOther.getHoldCode()) || (this.getHoldCode() != null
						&& castOther.getHoldCode() != null && this.getHoldCode().equals(castOther.getHoldCode())))
				&& ((this.getHold() == castOther.getHold()) || (this.getHold() != null && castOther.getHold() != null
						&& this.getHold().equals(castOther.getHold())))
				&& ((this.getVmsExemptedCode() == castOther.getVmsExemptedCode())
						|| (this.getVmsExemptedCode() != null && castOther.getVmsExemptedCode() != null
								&& this.getVmsExemptedCode().equals(castOther.getVmsExemptedCode())))
				&& ((this.getVmsExempted() == castOther.getVmsExempted())
						|| (this.getVmsExempted() != null && castOther.getVmsExempted() != null
								&& this.getVmsExempted().equals(castOther.getVmsExempted())))
				&& ((this.getProposedVendorCode() == castOther.getProposedVendorCode())
						|| (this.getProposedVendorCode() != null && castOther.getProposedVendorCode() != null
								&& this.getProposedVendorCode().equals(castOther.getProposedVendorCode())))
				&& ((this.getProposedVendor() == castOther.getProposedVendor())
						|| (this.getProposedVendor() != null && castOther.getProposedVendor() != null
								&& this.getProposedVendor().equals(castOther.getProposedVendor())))
				&& ((this.getBusinessSectorCode() == castOther.getBusinessSectorCode())
						|| (this.getBusinessSectorCode() != null && castOther.getBusinessSectorCode() != null
								&& this.getBusinessSectorCode().equals(castOther.getBusinessSectorCode())))
				&& ((this.getBusinessSector() == castOther.getBusinessSector())
						|| (this.getBusinessSector() != null && castOther.getBusinessSector() != null
								&& this.getBusinessSector().equals(castOther.getBusinessSector())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAddressBookNumber() == null ? 0 : this.getAddressBookNumber().hashCode());
		result = 37 * result + (getAddressBookName() == null ? 0 : this.getAddressBookName().hashCode());
		result = 37 * result
				+ (getBusinessRegistrationNumber() == null ? 0 : this.getBusinessRegistrationNumber().hashCode());
		result = 37 * result + (getSecurityBu() == null ? 0 : this.getSecurityBu().hashCode());
		result = 37 * result + (getVendorApprStatusCode() == null ? 0 : this.getVendorApprStatusCode().hashCode());
		result = 37 * result + (getVendorApprovalStatus() == null ? 0 : this.getVendorApprovalStatus().hashCode());
		result = 37 * result + (getAddressBookTypeCode() == null ? 0 : this.getAddressBookTypeCode().hashCode());
		result = 37 * result + (getAddrBookType() == null ? 0 : this.getAddrBookType().hashCode());
		result = 37 * result + (getSupplierApprovalCode() == null ? 0 : this.getSupplierApprovalCode().hashCode());
		result = 37 * result + (getSupplierApproval() == null ? 0 : this.getSupplierApproval().hashCode());
		result = 37 * result
				+ (getSubcontractorApprovalCode() == null ? 0 : this.getSubcontractorApprovalCode().hashCode());
		result = 37 * result + (getSubcontractorApproval() == null ? 0 : this.getSubcontractorApproval().hashCode());
		result = 37 * result + (getVendorTypeCode() == null ? 0 : this.getVendorTypeCode().hashCode());
		result = 37 * result + (getVendorType() == null ? 0 : this.getVendorType().hashCode());
		result = 37 * result + (getClientGroupCode() == null ? 0 : this.getClientGroupCode().hashCode());
		result = 37 * result + (getClientGroup() == null ? 0 : this.getClientGroup().hashCode());
		result = 37 * result + (getVendorStatusCode() == null ? 0 : this.getVendorStatusCode().hashCode());
		result = 37 * result + (getVendorStatus() == null ? 0 : this.getVendorStatus().hashCode());
		result = 37 * result + (getHoldCode() == null ? 0 : this.getHoldCode().hashCode());
		result = 37 * result + (getHold() == null ? 0 : this.getHold().hashCode());
		result = 37 * result + (getVmsExemptedCode() == null ? 0 : this.getVmsExemptedCode().hashCode());
		result = 37 * result + (getVmsExempted() == null ? 0 : this.getVmsExempted().hashCode());
		result = 37 * result + (getProposedVendorCode() == null ? 0 : this.getProposedVendorCode().hashCode());
		result = 37 * result + (getProposedVendor() == null ? 0 : this.getProposedVendor().hashCode());
		result = 37 * result + (getBusinessSectorCode() == null ? 0 : this.getBusinessSectorCode().hashCode());
		result = 37 * result + (getBusinessSector() == null ? 0 : this.getBusinessSector().hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AddressBook [addressBookNumber=" + addressBookNumber + ", addressBookName=" + addressBookName
				+ ", businessRegistrationNumber=" + businessRegistrationNumber + ", securityBu=" + securityBu
				+ ", vendorApprStatusCode=" + vendorApprStatusCode + ", vendorApprovalStatus=" + vendorApprovalStatus
				+ ", addressBookTypeCode=" + addressBookTypeCode + ", addrBookType=" + addrBookType
				+ ", supplierApprovalCode=" + supplierApprovalCode + ", supplierApproval=" + supplierApproval
				+ ", subcontractorApprovalCode=" + subcontractorApprovalCode + ", subcontractorApproval="
				+ subcontractorApproval + ", vendorTypeCode=" + vendorTypeCode + ", vendorType=" + vendorType
				+ ", clientGroupCode=" + clientGroupCode + ", clientGroup=" + clientGroup + ", vendorStatusCode="
				+ vendorStatusCode + ", vendorStatus=" + vendorStatus + ", holdCode=" + holdCode + ", hold=" + hold
				+ ", vmsExemptedCode=" + vmsExemptedCode + ", vmsExempted=" + vmsExempted + ", proposedVendorCode="
				+ proposedVendorCode + ", proposedVendor=" + proposedVendor + ", businessSectorCode="
				+ businessSectorCode + ", businessSector=" + businessSector + "]";
	}

}
