package com.gammon.pcms.model.adl;
// Generated Jul 14, 2016 10:01:24 AM by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ApprovalHeader generated by hbm2java
 */
@Entity
@Table(name = "FACT_APPR_INSTANCE_HEADER")
public class ApprovalHeader implements java.io.Serializable {

	private static final long serialVersionUID = -6274539270768673975L;
	
	private String recordKeyDocument;
	private BigDecimal recordKeyInstance;
	private String typeDocument;
	private String typeApprovalCategory;
	private String entityBusinessUnitKey;
	private Long entityVendorId;
	private String dateModified;
	private String dateCreated;
	private String approvalRouteVendor;
	private long approvalRouteVersion;
	private String statusApproval;
	private String statusApprovalCode;
	private String currenyLocal;
	private BigDecimal amountInLocalCurr;
	private String currencyDocument;
	private double amountInForeignCurr;

	public ApprovalHeader() {
	}

	public ApprovalHeader(BigDecimal recordKeyInstance, String typeDocument, String typeApprovalCategory,
			String approvalRouteVendor, long approvalRouteVersion, double amountInForeignCurr) {
		this.recordKeyInstance = recordKeyInstance;
		this.typeDocument = typeDocument;
		this.typeApprovalCategory = typeApprovalCategory;
		this.approvalRouteVendor = approvalRouteVendor;
		this.approvalRouteVersion = approvalRouteVersion;
		this.amountInForeignCurr = amountInForeignCurr;
	}

	public ApprovalHeader(String recordKeyDocument, BigDecimal recordKeyInstance, String typeDocument,
			String typeApprovalCategory, String entityBusinessUnitKey, Long entityVendorId, String dateModified,
			String dateCreated, String approvalRouteVendor, long approvalRouteVersion, String statusApproval,
			String statusApprovalCode, String currenyLocal, BigDecimal amountInLocalCurr, String currencyDocument,
			double amountInForeignCurr) {
		this.recordKeyDocument = recordKeyDocument;
		this.recordKeyInstance = recordKeyInstance;
		this.typeDocument = typeDocument;
		this.typeApprovalCategory = typeApprovalCategory;
		this.entityBusinessUnitKey = entityBusinessUnitKey;
		this.entityVendorId = entityVendorId;
		this.dateModified = dateModified;
		this.dateCreated = dateCreated;
		this.approvalRouteVendor = approvalRouteVendor;
		this.approvalRouteVersion = approvalRouteVersion;
		this.statusApproval = statusApproval;
		this.statusApprovalCode = statusApprovalCode;
		this.currenyLocal = currenyLocal;
		this.amountInLocalCurr = amountInLocalCurr;
		this.currencyDocument = currencyDocument;
		this.amountInForeignCurr = amountInForeignCurr;
	}

	
	@Column(name = "RECORD_KEY_DOCUMENT", length = 1472)
	public String getRecordKeyDocument() {
		return this.recordKeyDocument;
	}

	public void setRecordKeyDocument(String recordKeyDocument) {
		this.recordKeyDocument = recordKeyDocument;
	}

	@Id
	@Column(name = "RECORD_KEY_INSTANCE", nullable = false, scale = 0)
	public BigDecimal getRecordKeyInstance() {
		return this.recordKeyInstance;
	}

	public void setRecordKeyInstance (BigDecimal recordKeyInstance) {
		this.recordKeyInstance = recordKeyInstance;
	}

	@Column(name = "TYPE_DOCUMENT", nullable = false, length = 200)
	public String getTypeDocument() {
		return this.typeDocument;
	}

	public void setTypeDocument(String typeDocument) {
		this.typeDocument = typeDocument;
	}

	@Column(name = "TYPE_APPROVAL_CATEGORY", nullable = false, length = 40)
	public String getTypeApprovalCategory() {
		return this.typeApprovalCategory;
	}

	public void setTypeApprovalCategory(String typeApprovalCategory) {
		this.typeApprovalCategory = typeApprovalCategory;
	}

	@Column(name = "ENTITY_BUSINESS_UNIT_KEY", length = 48)
	public String getEntityBusinessUnitKey() {
		return this.entityBusinessUnitKey;
	}

	public void setEntityBusinessUnitKey(String entityBusinessUnitKey) {
		this.entityBusinessUnitKey = entityBusinessUnitKey;
	}

	@Column(name = "ENTITY_VENDOR_ID", precision = 10, scale = 0)
	public Long getEntityVendorId() {
		return this.entityVendorId;
	}

	public void setEntityVendorId(Long entityVendorId) {
		this.entityVendorId = entityVendorId;
	}

	@Column(name = "DATE_MODIFIED", length = 29)
	public String getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(String dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "DATE_CREATED", length = 29)
	public String getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(String dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "APPROVAL_ROUTE_VENDOR", nullable = false, length = 200)
	public String getApprovalRouteVendor() {
		return this.approvalRouteVendor;
	}

	public void setApprovalRouteVendor(String approvalRouteVendor) {
		this.approvalRouteVendor = approvalRouteVendor;
	}

	@Column(name = "APPROVAL_ROUTE_VERSION", nullable = false, precision = 10, scale = 0)
	public long getApprovalRouteVersion() {
		return this.approvalRouteVersion;
	}

	public void setApprovalRouteVersion(long approvalRouteVersion) {
		this.approvalRouteVersion = approvalRouteVersion;
	}

	@Column(name = "STATUS_APPROVAL", length = 200)
	public String getStatusApproval() {
		return this.statusApproval;
	}

	public void setStatusApproval(String statusApproval) {
		this.statusApproval = statusApproval;
	}

	@Column(name = "STATUS_APPROVAL_CODE", length = 4)
	public String getStatusApprovalCode() {
		return this.statusApprovalCode;
	}

	public void setStatusApprovalCode(String statusApprovalCode) {
		this.statusApprovalCode = statusApprovalCode;
	}

	@Column(name = "CURRENY_LOCAL", length = 12)
	public String getCurrenyLocal() {
		return this.currenyLocal;
	}

	public void setCurrenyLocal(String currenyLocal) {
		this.currenyLocal = currenyLocal;
	}

	@Column(name = "AMOUNT_IN_LOCAL_CURR", precision = 22, scale = 0)
	public BigDecimal getAmountInLocalCurr() {
		return this.amountInLocalCurr;
	}

	public void setAmountInLocalCurr(BigDecimal amountInLocalCurr) {
		this.amountInLocalCurr = amountInLocalCurr;
	}

	@Column(name = "CURRENCY_DOCUMENT", length = 12)
	public String getCurrencyDocument() {
		return this.currencyDocument;
	}

	public void setCurrencyDocument(String currencyDocument) {
		this.currencyDocument = currencyDocument;
	}

	@Column(name = "AMOUNT_IN_FOREIGN_CURR", nullable = false, precision = 126, scale = 0)
	public double getAmountInForeignCurr() {
		return this.amountInForeignCurr;
	}

	public void setAmountInForeignCurr(double amountInForeignCurr) {
		this.amountInForeignCurr = amountInForeignCurr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApprovalHeader))
			return false;
		ApprovalHeader castOther = (ApprovalHeader) other;

		return ((this.getRecordKeyDocument() == castOther.getRecordKeyDocument())
				|| (this.getRecordKeyDocument() != null && castOther.getRecordKeyDocument() != null
						&& this.getRecordKeyDocument().equals(castOther.getRecordKeyDocument())))
				&& ((this.getRecordKeyInstance() == castOther.getRecordKeyInstance())
						|| (this.getRecordKeyInstance() != null && castOther.getRecordKeyInstance() != null
								&& this.getRecordKeyInstance().equals(castOther.getRecordKeyInstance())))
				&& ((this.getTypeDocument() == castOther.getTypeDocument())
						|| (this.getTypeDocument() != null && castOther.getTypeDocument() != null
								&& this.getTypeDocument().equals(castOther.getTypeDocument())))
				&& ((this.getTypeApprovalCategory() == castOther.getTypeApprovalCategory())
						|| (this.getTypeApprovalCategory() != null && castOther.getTypeApprovalCategory() != null
								&& this.getTypeApprovalCategory().equals(castOther.getTypeApprovalCategory())))
				&& ((this.getEntityBusinessUnitKey() == castOther.getEntityBusinessUnitKey())
						|| (this.getEntityBusinessUnitKey() != null && castOther.getEntityBusinessUnitKey() != null
								&& this.getEntityBusinessUnitKey().equals(castOther.getEntityBusinessUnitKey())))
				&& ((this.getEntityVendorId() == castOther.getEntityVendorId())
						|| (this.getEntityVendorId() != null && castOther.getEntityVendorId() != null
								&& this.getEntityVendorId().equals(castOther.getEntityVendorId())))
				&& ((this.getDateModified() == castOther.getDateModified())
						|| (this.getDateModified() != null && castOther.getDateModified() != null
								&& this.getDateModified().equals(castOther.getDateModified())))
				&& ((this.getDateCreated() == castOther.getDateCreated())
						|| (this.getDateCreated() != null && castOther.getDateCreated() != null
								&& this.getDateCreated().equals(castOther.getDateCreated())))
				&& ((this.getApprovalRouteVendor() == castOther.getApprovalRouteVendor())
						|| (this.getApprovalRouteVendor() != null && castOther.getApprovalRouteVendor() != null
								&& this.getApprovalRouteVendor().equals(castOther.getApprovalRouteVendor())))
				&& (this.getApprovalRouteVersion() == castOther.getApprovalRouteVersion())
				&& ((this.getStatusApproval() == castOther.getStatusApproval())
						|| (this.getStatusApproval() != null && castOther.getStatusApproval() != null
								&& this.getStatusApproval().equals(castOther.getStatusApproval())))
				&& ((this.getStatusApprovalCode() == castOther.getStatusApprovalCode())
						|| (this.getStatusApprovalCode() != null && castOther.getStatusApprovalCode() != null
								&& this.getStatusApprovalCode().equals(castOther.getStatusApprovalCode())))
				&& ((this.getCurrenyLocal() == castOther.getCurrenyLocal())
						|| (this.getCurrenyLocal() != null && castOther.getCurrenyLocal() != null
								&& this.getCurrenyLocal().equals(castOther.getCurrenyLocal())))
				&& ((this.getAmountInLocalCurr() == castOther.getAmountInLocalCurr())
						|| (this.getAmountInLocalCurr() != null && castOther.getAmountInLocalCurr() != null
								&& this.getAmountInLocalCurr().equals(castOther.getAmountInLocalCurr())))
				&& ((this.getCurrencyDocument() == castOther.getCurrencyDocument())
						|| (this.getCurrencyDocument() != null && castOther.getCurrencyDocument() != null
								&& this.getCurrencyDocument().equals(castOther.getCurrencyDocument())))
				&& (this.getAmountInForeignCurr() == castOther.getAmountInForeignCurr());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRecordKeyDocument() == null ? 0 : this.getRecordKeyDocument().hashCode());
		result = 37 * result + (getRecordKeyInstance() == null ? 0 : this.getRecordKeyInstance().hashCode());
		result = 37 * result + (getTypeDocument() == null ? 0 : this.getTypeDocument().hashCode());
		result = 37 * result + (getTypeApprovalCategory() == null ? 0 : this.getTypeApprovalCategory().hashCode());
		result = 37 * result + (getEntityBusinessUnitKey() == null ? 0 : this.getEntityBusinessUnitKey().hashCode());
		result = 37 * result + (getEntityVendorId() == null ? 0 : this.getEntityVendorId().hashCode());
		result = 37 * result + (getDateModified() == null ? 0 : this.getDateModified().hashCode());
		result = 37 * result + (getDateCreated() == null ? 0 : this.getDateCreated().hashCode());
		result = 37 * result + (getApprovalRouteVendor() == null ? 0 : this.getApprovalRouteVendor().hashCode());
		result = 37 * result + (int) this.getApprovalRouteVersion();
		result = 37 * result + (getStatusApproval() == null ? 0 : this.getStatusApproval().hashCode());
		result = 37 * result + (getStatusApprovalCode() == null ? 0 : this.getStatusApprovalCode().hashCode());
		result = 37 * result + (getCurrenyLocal() == null ? 0 : this.getCurrenyLocal().hashCode());
		result = 37 * result + (getAmountInLocalCurr() == null ? 0 : this.getAmountInLocalCurr().hashCode());
		result = 37 * result + (getCurrencyDocument() == null ? 0 : this.getCurrencyDocument().hashCode());
		result = 37 * result + (int) this.getAmountInForeignCurr();
		return result;
	}

}
