package com.gammon.pcms.model.adl;
// Generated Jul 25, 2016 6:30:47 PM by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DimBusinessUnitId generated by hbm2java
 */
@Entity
@Table(name = "DIM_BUSINESS_UNIT")
public class BusinessUnit implements java.io.Serializable {

	private static final long serialVersionUID = -7876286865022951331L;
	
	private String businessUnitCode;
	private String businessUnitDescription;
	private String companyCode;
	private String companyName;
	private String businessType;
	private String jobType;
	private String contractTypeCode;
	private String contractType;
	private BigDecimal immediateCustomerNo;
	private String immediateCustomer;
	private String icustomerGroup;
	private BigDecimal ultimateCustomerNo;
	private String ultimateCustomer;
	private String ucustomerGroup;
	private String regionCode;
	private String sectionCode;
	private String section;
	private String divisionCode;
	private String division;
	private String departmentCode;
	private String department;
	private String internalJobCode;
	private String internalJob;
	private String soloJvCode;
	private String soloJv;
	private String contractSignedCode;
	private String profitLossCode;
	private String profitAndLossStatus;
	private String balanceSheetCode;
	private String balanceSheetStatus;
	private String bondRqmtCode;
	private String bondRequirement;
	private String soloJvJoCode;
	private String soloJvJo;
	private Date datePlannedStart;
	private Date dateActualStart;
	private Date datePlannedEnd;
	private Date dateActualEnd;
	private Date dateAnticipatedCompletion;
	private Date dateRevisedCompletion;
	private String entityJobKey;
	private String numberClientContract;
	private Double percentageJv;
	private Double amountOriginalContract;
	private Double amountProjectedContract;
	private Double tenderGp;
	private Long dateForecastEndPeriod;
	private Long dateForecastEndYear;
	private Long dateYearOfCompletion;
	private Double percentageRetentionMaximum;
	private Double percentageRetentionInterim;
	private Double percentageDefectProvision;
	private Character cpfApplicable;
	private String cpfIndexName;
	private Long cpfBasePeriod;
	private Long cpfBaseYear;
	private Character levyApplicable;
	private Double percentageLevyCita;
	private Double percentageLevyPcfb;
	private String currencyCode;
	private String currencyDecimal;

	public BusinessUnit() {
	}

	public BusinessUnit(String businessUnitCode, String businessUnitDescription, String companyCode,
			String companyName, String businessType, String jobType, String contractTypeCode, String contractType,
			BigDecimal immediateCustomerNo, String immediateCustomer, String icustomerGroup,
			BigDecimal ultimateCustomerNo, String ultimateCustomer, String ucustomerGroup, String regionCode,
			String sectionCode, String section, String divisionCode, String division, String departmentCode,
			String department, String internalJobCode, String internalJob, String soloJvCode, String soloJv,
			String contractSignedCode, String profitLossCode, String profitAndLossStatus, String balanceSheetCode,
			String balanceSheetStatus, String bondRqmtCode, String bondRequirement, String soloJvJoCode,
			String soloJvJo, Date datePlannedStart, Date dateActualStart, Date datePlannedEnd, Date dateActualEnd,
			Date dateAnticipatedCompletion, Date dateRevisedCompletion, String entityJobKey,
			String numberClientContract, Double percentageJv, Double amountOriginalContract,
			Double amountProjectedContract, Double tenderGp, Long dateForecastEndPeriod, Long dateForecastEndYear,
			Long dateYearOfCompletion, Double percentageRetentionMaximum, Double percentageRetentionInterim,
			Double percentageDefectProvision, Character cpfApplicable, String cpfIndexName, Long cpfBasePeriod,
			Long cpfBaseYear, Character levyApplicable, Double percentageLevyCita, Double percentageLevyPcfb,
			String currencyCode, String currencyDecimal) {
		this.businessUnitCode = businessUnitCode;
		this.businessUnitDescription = businessUnitDescription;
		this.companyCode = companyCode;
		this.companyName = companyName;
		this.businessType = businessType;
		this.jobType = jobType;
		this.contractTypeCode = contractTypeCode;
		this.contractType = contractType;
		this.immediateCustomerNo = immediateCustomerNo;
		this.immediateCustomer = immediateCustomer;
		this.icustomerGroup = icustomerGroup;
		this.ultimateCustomerNo = ultimateCustomerNo;
		this.ultimateCustomer = ultimateCustomer;
		this.ucustomerGroup = ucustomerGroup;
		this.regionCode = regionCode;
		this.sectionCode = sectionCode;
		this.section = section;
		this.divisionCode = divisionCode;
		this.division = division;
		this.departmentCode = departmentCode;
		this.department = department;
		this.internalJobCode = internalJobCode;
		this.internalJob = internalJob;
		this.soloJvCode = soloJvCode;
		this.soloJv = soloJv;
		this.contractSignedCode = contractSignedCode;
		this.profitLossCode = profitLossCode;
		this.profitAndLossStatus = profitAndLossStatus;
		this.balanceSheetCode = balanceSheetCode;
		this.balanceSheetStatus = balanceSheetStatus;
		this.bondRqmtCode = bondRqmtCode;
		this.bondRequirement = bondRequirement;
		this.soloJvJoCode = soloJvJoCode;
		this.soloJvJo = soloJvJo;
		this.datePlannedStart = datePlannedStart;
		this.dateActualStart = dateActualStart;
		this.datePlannedEnd = datePlannedEnd;
		this.dateActualEnd = dateActualEnd;
		this.dateAnticipatedCompletion = dateAnticipatedCompletion;
		this.dateRevisedCompletion = dateRevisedCompletion;
		this.entityJobKey = entityJobKey;
		this.numberClientContract = numberClientContract;
		this.percentageJv = percentageJv;
		this.amountOriginalContract = amountOriginalContract;
		this.amountProjectedContract = amountProjectedContract;
		this.tenderGp = tenderGp;
		this.dateForecastEndPeriod = dateForecastEndPeriod;
		this.dateForecastEndYear = dateForecastEndYear;
		this.dateYearOfCompletion = dateYearOfCompletion;
		this.percentageRetentionMaximum = percentageRetentionMaximum;
		this.percentageRetentionInterim = percentageRetentionInterim;
		this.percentageDefectProvision = percentageDefectProvision;
		this.cpfApplicable = cpfApplicable;
		this.cpfIndexName = cpfIndexName;
		this.cpfBasePeriod = cpfBasePeriod;
		this.cpfBaseYear = cpfBaseYear;
		this.levyApplicable = levyApplicable;
		this.percentageLevyCita = percentageLevyCita;
		this.percentageLevyPcfb = percentageLevyPcfb;
		this.currencyCode = currencyCode;
		this.currencyDecimal = currencyDecimal;
	}

	@Id
	@Column(name = "BUSINESS_UNIT_CODE", length = 48)
	public String getBusinessUnitCode() {
		return this.businessUnitCode;
	}

	public void setBusinessUnitCode(String businessUnitCode) {
		this.businessUnitCode = businessUnitCode;
	}

	@Column(name = "BUSINESS_UNIT_DESCRIPTION", length = 120)
	public String getBusinessUnitDescription() {
		return this.businessUnitDescription;
	}

	public void setBusinessUnitDescription(String businessUnitDescription) {
		this.businessUnitDescription = businessUnitDescription;
	}

	@Column(name = "COMPANY_CODE", length = 20)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "COMPANY_NAME", length = 120)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "BUSINESS_TYPE", length = 8)
	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	@Column(name = "JOB_TYPE", length = 244)
	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	@Column(name = "CONTRACT_TYPE_CODE", length = 16)
	public String getContractTypeCode() {
		return this.contractTypeCode;
	}

	public void setContractTypeCode(String contractTypeCode) {
		this.contractTypeCode = contractTypeCode;
	}

	@Column(name = "CONTRACT_TYPE", length = 244)
	public String getContractType() {
		return this.contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	@Column(name = "IMMEDIATE_CUSTOMER_NO", precision = 22, scale = 0)
	public BigDecimal getImmediateCustomerNo() {
		return this.immediateCustomerNo;
	}

	public void setImmediateCustomerNo(BigDecimal immediateCustomerNo) {
		this.immediateCustomerNo = immediateCustomerNo;
	}

	@Column(name = "IMMEDIATE_CUSTOMER", length = 160)
	public String getImmediateCustomer() {
		return this.immediateCustomer;
	}

	public void setImmediateCustomer(String immediateCustomer) {
		this.immediateCustomer = immediateCustomer;
	}

	@Column(name = "ICUSTOMER_GROUP", length = 244)
	public String getIcustomerGroup() {
		return this.icustomerGroup;
	}

	public void setIcustomerGroup(String icustomerGroup) {
		this.icustomerGroup = icustomerGroup;
	}

	@Column(name = "ULTIMATE_CUSTOMER_NO", precision = 22, scale = 0)
	public BigDecimal getUltimateCustomerNo() {
		return this.ultimateCustomerNo;
	}

	public void setUltimateCustomerNo(BigDecimal ultimateCustomerNo) {
		this.ultimateCustomerNo = ultimateCustomerNo;
	}

	@Column(name = "ULTIMATE_CUSTOMER", length = 160)
	public String getUltimateCustomer() {
		return this.ultimateCustomer;
	}

	public void setUltimateCustomer(String ultimateCustomer) {
		this.ultimateCustomer = ultimateCustomer;
	}

	@Column(name = "UCUSTOMER_GROUP", length = 244)
	public String getUcustomerGroup() {
		return this.ucustomerGroup;
	}

	public void setUcustomerGroup(String ucustomerGroup) {
		this.ucustomerGroup = ucustomerGroup;
	}

	@Column(name = "REGION_CODE", length = 12)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "SECTION_CODE", length = 12)
	public String getSectionCode() {
		return this.sectionCode;
	}

	public void setSectionCode(String sectionCode) {
		this.sectionCode = sectionCode;
	}

	@Column(name = "SECTION", length = 244)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Column(name = "DIVISION_CODE", length = 12)
	public String getDivisionCode() {
		return this.divisionCode;
	}

	public void setDivisionCode(String divisionCode) {
		this.divisionCode = divisionCode;
	}

	@Column(name = "DIVISION", length = 120)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "DEPARTMENT_CODE", length = 12)
	public String getDepartmentCode() {
		return this.departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	@Column(name = "DEPARTMENT", length = 244)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "INTERNAL_JOB_CODE", length = 12)
	public String getInternalJobCode() {
		return this.internalJobCode;
	}

	public void setInternalJobCode(String internalJobCode) {
		this.internalJobCode = internalJobCode;
	}

	@Column(name = "INTERNAL_JOB", length = 244)
	public String getInternalJob() {
		return this.internalJob;
	}

	public void setInternalJob(String internalJob) {
		this.internalJob = internalJob;
	}

	@Column(name = "SOLO_JV_CODE", length = 12)
	public String getSoloJvCode() {
		return this.soloJvCode;
	}

	public void setSoloJvCode(String soloJvCode) {
		this.soloJvCode = soloJvCode;
	}

	@Column(name = "SOLO_JV", length = 244)
	public String getSoloJv() {
		return this.soloJv;
	}

	public void setSoloJv(String soloJv) {
		this.soloJv = soloJv;
	}

	@Column(name = "CONTRACT_SIGNED_CODE", length = 12)
	public String getContractSignedCode() {
		return this.contractSignedCode;
	}

	public void setContractSignedCode(String contractSignedCode) {
		this.contractSignedCode = contractSignedCode;
	}

	@Column(name = "PROFIT_LOSS_CODE", length = 12)
	public String getProfitLossCode() {
		return this.profitLossCode;
	}

	public void setProfitLossCode(String profitLossCode) {
		this.profitLossCode = profitLossCode;
	}

	@Column(name = "PROFIT_AND_LOSS_STATUS", length = 244)
	public String getProfitAndLossStatus() {
		return this.profitAndLossStatus;
	}

	public void setProfitAndLossStatus(String profitAndLossStatus) {
		this.profitAndLossStatus = profitAndLossStatus;
	}

	@Column(name = "BALANCE_SHEET_CODE", length = 12)
	public String getBalanceSheetCode() {
		return this.balanceSheetCode;
	}

	public void setBalanceSheetCode(String balanceSheetCode) {
		this.balanceSheetCode = balanceSheetCode;
	}

	@Column(name = "BALANCE_SHEET_STATUS", length = 244)
	public String getBalanceSheetStatus() {
		return this.balanceSheetStatus;
	}

	public void setBalanceSheetStatus(String balanceSheetStatus) {
		this.balanceSheetStatus = balanceSheetStatus;
	}

	@Column(name = "BOND_RQMT_CODE", length = 40)
	public String getBondRqmtCode() {
		return this.bondRqmtCode;
	}

	public void setBondRqmtCode(String bondRqmtCode) {
		this.bondRqmtCode = bondRqmtCode;
	}

	@Column(name = "BOND_REQUIREMENT", length = 244)
	public String getBondRequirement() {
		return this.bondRequirement;
	}

	public void setBondRequirement(String bondRequirement) {
		this.bondRequirement = bondRequirement;
	}

	@Column(name = "SOLO_JV_JO_CODE", length = 40)
	public String getSoloJvJoCode() {
		return this.soloJvJoCode;
	}

	public void setSoloJvJoCode(String soloJvJoCode) {
		this.soloJvJoCode = soloJvJoCode;
	}

	@Column(name = "SOLO_JV_JO", length = 244)
	public String getSoloJvJo() {
		return this.soloJvJo;
	}

	public void setSoloJvJo(String soloJvJo) {
		this.soloJvJo = soloJvJo;
	}

	@Column(name = "DATE_PLANNED_START", length = 7)
	public Date getDatePlannedStart() {
		return this.datePlannedStart;
	}

	public void setDatePlannedStart(Date datePlannedStart) {
		this.datePlannedStart = datePlannedStart;
	}

	@Column(name = "DATE_ACTUAL_START", length = 7)
	public Date getDateActualStart() {
		return this.dateActualStart;
	}

	public void setDateActualStart(Date dateActualStart) {
		this.dateActualStart = dateActualStart;
	}

	@Column(name = "DATE_PLANNED_END", length = 7)
	public Date getDatePlannedEnd() {
		return this.datePlannedEnd;
	}

	public void setDatePlannedEnd(Date datePlannedEnd) {
		this.datePlannedEnd = datePlannedEnd;
	}

	@Column(name = "DATE_ACTUAL_END", length = 7)
	public Date getDateActualEnd() {
		return this.dateActualEnd;
	}

	public void setDateActualEnd(Date dateActualEnd) {
		this.dateActualEnd = dateActualEnd;
	}

	@Column(name = "DATE_ANTICIPATED_COMPLETION", length = 7)
	public Date getDateAnticipatedCompletion() {
		return this.dateAnticipatedCompletion;
	}

	public void setDateAnticipatedCompletion(Date dateAnticipatedCompletion) {
		this.dateAnticipatedCompletion = dateAnticipatedCompletion;
	}

	@Column(name = "DATE_REVISED_COMPLETION", length = 7)
	public Date getDateRevisedCompletion() {
		return this.dateRevisedCompletion;
	}

	public void setDateRevisedCompletion(Date dateRevisedCompletion) {
		this.dateRevisedCompletion = dateRevisedCompletion;
	}

	@Column(name = "ENTITY_JOB_KEY", length = 48)
	public String getEntityJobKey() {
		return this.entityJobKey;
	}

	public void setEntityJobKey(String entityJobKey) {
		this.entityJobKey = entityJobKey;
	}

	@Column(name = "NUMBER_CLIENT_CONTRACT", length = 80)
	public String getNumberClientContract() {
		return this.numberClientContract;
	}

	public void setNumberClientContract(String numberClientContract) {
		this.numberClientContract = numberClientContract;
	}

	@Column(name = "PERCENTAGE_JV", precision = 126, scale = 0)
	public Double getPercentageJv() {
		return this.percentageJv;
	}

	public void setPercentageJv(Double percentageJv) {
		this.percentageJv = percentageJv;
	}

	@Column(name = "AMOUNT_ORIGINAL_CONTRACT", precision = 126, scale = 0)
	public Double getAmountOriginalContract() {
		return this.amountOriginalContract;
	}

	public void setAmountOriginalContract(Double amountOriginalContract) {
		this.amountOriginalContract = amountOriginalContract;
	}

	@Column(name = "AMOUNT_PROJECTED_CONTRACT", precision = 126, scale = 0)
	public Double getAmountProjectedContract() {
		return this.amountProjectedContract;
	}

	public void setAmountProjectedContract(Double amountProjectedContract) {
		this.amountProjectedContract = amountProjectedContract;
	}

	@Column(name = "TENDER_GP", precision = 126, scale = 0)
	public Double getTenderGp() {
		return this.tenderGp;
	}

	public void setTenderGp(Double tenderGp) {
		this.tenderGp = tenderGp;
	}

	@Column(name = "DATE_FORECAST_END_PERIOD", precision = 10, scale = 0)
	public Long getDateForecastEndPeriod() {
		return this.dateForecastEndPeriod;
	}

	public void setDateForecastEndPeriod(Long dateForecastEndPeriod) {
		this.dateForecastEndPeriod = dateForecastEndPeriod;
	}

	@Column(name = "DATE_FORECAST_END_YEAR", precision = 10, scale = 0)
	public Long getDateForecastEndYear() {
		return this.dateForecastEndYear;
	}

	public void setDateForecastEndYear(Long dateForecastEndYear) {
		this.dateForecastEndYear = dateForecastEndYear;
	}

	@Column(name = "DATE_YEAR_OF_COMPLETION", precision = 10, scale = 0)
	public Long getDateYearOfCompletion() {
		return this.dateYearOfCompletion;
	}

	public void setDateYearOfCompletion(Long dateYearOfCompletion) {
		this.dateYearOfCompletion = dateYearOfCompletion;
	}

	@Column(name = "PERCENTAGE_RETENTION_MAXIMUM", precision = 126, scale = 0)
	public Double getPercentageRetentionMaximum() {
		return this.percentageRetentionMaximum;
	}

	public void setPercentageRetentionMaximum(Double percentageRetentionMaximum) {
		this.percentageRetentionMaximum = percentageRetentionMaximum;
	}

	@Column(name = "PERCENTAGE_RETENTION_INTERIM", precision = 126, scale = 0)
	public Double getPercentageRetentionInterim() {
		return this.percentageRetentionInterim;
	}

	public void setPercentageRetentionInterim(Double percentageRetentionInterim) {
		this.percentageRetentionInterim = percentageRetentionInterim;
	}

	@Column(name = "PERCENTAGE_DEFECT_PROVISION", precision = 126, scale = 0)
	public Double getPercentageDefectProvision() {
		return this.percentageDefectProvision;
	}

	public void setPercentageDefectProvision(Double percentageDefectProvision) {
		this.percentageDefectProvision = percentageDefectProvision;
	}

	@Column(name = "CPF_APPLICABLE", length = 1)
	public Character getCpfApplicable() {
		return this.cpfApplicable;
	}

	public void setCpfApplicable(Character cpfApplicable) {
		this.cpfApplicable = cpfApplicable;
	}

	@Column(name = "CPF_INDEX_NAME", length = 48)
	public String getCpfIndexName() {
		return this.cpfIndexName;
	}

	public void setCpfIndexName(String cpfIndexName) {
		this.cpfIndexName = cpfIndexName;
	}

	@Column(name = "CPF_BASE_PERIOD", precision = 10, scale = 0)
	public Long getCpfBasePeriod() {
		return this.cpfBasePeriod;
	}

	public void setCpfBasePeriod(Long cpfBasePeriod) {
		this.cpfBasePeriod = cpfBasePeriod;
	}

	@Column(name = "CPF_BASE_YEAR", precision = 10, scale = 0)
	public Long getCpfBaseYear() {
		return this.cpfBaseYear;
	}

	public void setCpfBaseYear(Long cpfBaseYear) {
		this.cpfBaseYear = cpfBaseYear;
	}

	@Column(name = "LEVY_APPLICABLE", length = 1)
	public Character getLevyApplicable() {
		return this.levyApplicable;
	}

	public void setLevyApplicable(Character levyApplicable) {
		this.levyApplicable = levyApplicable;
	}

	@Column(name = "PERCENTAGE_LEVY_CITA", precision = 126, scale = 0)
	public Double getPercentageLevyCita() {
		return this.percentageLevyCita;
	}

	public void setPercentageLevyCita(Double percentageLevyCita) {
		this.percentageLevyCita = percentageLevyCita;
	}

	@Column(name = "PERCENTAGE_LEVY_PCFB", precision = 126, scale = 0)
	public Double getPercentageLevyPcfb() {
		return this.percentageLevyPcfb;
	}

	public void setPercentageLevyPcfb(Double percentageLevyPcfb) {
		this.percentageLevyPcfb = percentageLevyPcfb;
	}

	@Column(name = "CURRENCY_CODE", length = 12)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	@Column(name = "CURRENCY_DECIMAL", length = 4)
	public String getCurrencyDecimal() {
		return this.currencyDecimal;
	}

	public void setCurrencyDecimal(String currencyDecimal) {
		this.currencyDecimal = currencyDecimal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BusinessUnit))
			return false;
		BusinessUnit castOther = (BusinessUnit) other;

		return ((this.getBusinessUnitCode() == castOther.getBusinessUnitCode())
				|| (this.getBusinessUnitCode() != null && castOther.getBusinessUnitCode() != null
						&& this.getBusinessUnitCode().equals(castOther.getBusinessUnitCode())))
				&& ((this.getBusinessUnitDescription() == castOther.getBusinessUnitDescription())
						|| (this.getBusinessUnitDescription() != null && castOther.getBusinessUnitDescription() != null
								&& this.getBusinessUnitDescription().equals(castOther.getBusinessUnitDescription())))
				&& ((this.getCompanyCode() == castOther.getCompanyCode())
						|| (this.getCompanyCode() != null && castOther.getCompanyCode() != null
								&& this.getCompanyCode().equals(castOther.getCompanyCode())))
				&& ((this.getCompanyName() == castOther.getCompanyName())
						|| (this.getCompanyName() != null && castOther.getCompanyName() != null
								&& this.getCompanyName().equals(castOther.getCompanyName())))
				&& ((this.getBusinessType() == castOther.getBusinessType())
						|| (this.getBusinessType() != null && castOther.getBusinessType() != null
								&& this.getBusinessType().equals(castOther.getBusinessType())))
				&& ((this.getJobType() == castOther.getJobType()) || (this.getJobType() != null
						&& castOther.getJobType() != null && this.getJobType().equals(castOther.getJobType())))
				&& ((this.getContractTypeCode() == castOther.getContractTypeCode())
						|| (this.getContractTypeCode() != null && castOther.getContractTypeCode() != null
								&& this.getContractTypeCode().equals(castOther.getContractTypeCode())))
				&& ((this.getContractType() == castOther.getContractType())
						|| (this.getContractType() != null && castOther.getContractType() != null
								&& this.getContractType().equals(castOther.getContractType())))
				&& ((this.getImmediateCustomerNo() == castOther.getImmediateCustomerNo())
						|| (this.getImmediateCustomerNo() != null && castOther.getImmediateCustomerNo() != null
								&& this.getImmediateCustomerNo().equals(castOther.getImmediateCustomerNo())))
				&& ((this.getImmediateCustomer() == castOther.getImmediateCustomer())
						|| (this.getImmediateCustomer() != null && castOther.getImmediateCustomer() != null
								&& this.getImmediateCustomer().equals(castOther.getImmediateCustomer())))
				&& ((this.getIcustomerGroup() == castOther.getIcustomerGroup())
						|| (this.getIcustomerGroup() != null && castOther.getIcustomerGroup() != null
								&& this.getIcustomerGroup().equals(castOther.getIcustomerGroup())))
				&& ((this.getUltimateCustomerNo() == castOther.getUltimateCustomerNo())
						|| (this.getUltimateCustomerNo() != null && castOther.getUltimateCustomerNo() != null
								&& this.getUltimateCustomerNo().equals(castOther.getUltimateCustomerNo())))
				&& ((this.getUltimateCustomer() == castOther.getUltimateCustomer())
						|| (this.getUltimateCustomer() != null && castOther.getUltimateCustomer() != null
								&& this.getUltimateCustomer().equals(castOther.getUltimateCustomer())))
				&& ((this.getUcustomerGroup() == castOther.getUcustomerGroup())
						|| (this.getUcustomerGroup() != null && castOther.getUcustomerGroup() != null
								&& this.getUcustomerGroup().equals(castOther.getUcustomerGroup())))
				&& ((this.getRegionCode() == castOther.getRegionCode()) || (this.getRegionCode() != null
						&& castOther.getRegionCode() != null && this.getRegionCode().equals(castOther.getRegionCode())))
				&& ((this.getSectionCode() == castOther.getSectionCode())
						|| (this.getSectionCode() != null && castOther.getSectionCode() != null
								&& this.getSectionCode().equals(castOther.getSectionCode())))
				&& ((this.getSection() == castOther.getSection()) || (this.getSection() != null
						&& castOther.getSection() != null && this.getSection().equals(castOther.getSection())))
				&& ((this.getDivisionCode() == castOther.getDivisionCode())
						|| (this.getDivisionCode() != null && castOther.getDivisionCode() != null
								&& this.getDivisionCode().equals(castOther.getDivisionCode())))
				&& ((this.getDivision() == castOther.getDivision()) || (this.getDivision() != null
						&& castOther.getDivision() != null && this.getDivision().equals(castOther.getDivision())))
				&& ((this.getDepartmentCode() == castOther.getDepartmentCode())
						|| (this.getDepartmentCode() != null && castOther.getDepartmentCode() != null
								&& this.getDepartmentCode().equals(castOther.getDepartmentCode())))
				&& ((this.getDepartment() == castOther.getDepartment()) || (this.getDepartment() != null
						&& castOther.getDepartment() != null && this.getDepartment().equals(castOther.getDepartment())))
				&& ((this.getInternalJobCode() == castOther.getInternalJobCode())
						|| (this.getInternalJobCode() != null && castOther.getInternalJobCode() != null
								&& this.getInternalJobCode().equals(castOther.getInternalJobCode())))
				&& ((this.getInternalJob() == castOther.getInternalJob())
						|| (this.getInternalJob() != null && castOther.getInternalJob() != null
								&& this.getInternalJob().equals(castOther.getInternalJob())))
				&& ((this.getSoloJvCode() == castOther.getSoloJvCode()) || (this.getSoloJvCode() != null
						&& castOther.getSoloJvCode() != null && this.getSoloJvCode().equals(castOther.getSoloJvCode())))
				&& ((this.getSoloJv() == castOther.getSoloJv()) || (this.getSoloJv() != null
						&& castOther.getSoloJv() != null && this.getSoloJv().equals(castOther.getSoloJv())))
				&& ((this.getContractSignedCode() == castOther.getContractSignedCode())
						|| (this.getContractSignedCode() != null && castOther.getContractSignedCode() != null
								&& this.getContractSignedCode().equals(castOther.getContractSignedCode())))
				&& ((this.getProfitLossCode() == castOther.getProfitLossCode())
						|| (this.getProfitLossCode() != null && castOther.getProfitLossCode() != null
								&& this.getProfitLossCode().equals(castOther.getProfitLossCode())))
				&& ((this.getProfitAndLossStatus() == castOther.getProfitAndLossStatus())
						|| (this.getProfitAndLossStatus() != null && castOther.getProfitAndLossStatus() != null
								&& this.getProfitAndLossStatus().equals(castOther.getProfitAndLossStatus())))
				&& ((this.getBalanceSheetCode() == castOther.getBalanceSheetCode())
						|| (this.getBalanceSheetCode() != null && castOther.getBalanceSheetCode() != null
								&& this.getBalanceSheetCode().equals(castOther.getBalanceSheetCode())))
				&& ((this.getBalanceSheetStatus() == castOther.getBalanceSheetStatus())
						|| (this.getBalanceSheetStatus() != null && castOther.getBalanceSheetStatus() != null
								&& this.getBalanceSheetStatus().equals(castOther.getBalanceSheetStatus())))
				&& ((this.getBondRqmtCode() == castOther.getBondRqmtCode())
						|| (this.getBondRqmtCode() != null && castOther.getBondRqmtCode() != null
								&& this.getBondRqmtCode().equals(castOther.getBondRqmtCode())))
				&& ((this.getBondRequirement() == castOther.getBondRequirement())
						|| (this.getBondRequirement() != null && castOther.getBondRequirement() != null
								&& this.getBondRequirement().equals(castOther.getBondRequirement())))
				&& ((this.getSoloJvJoCode() == castOther.getSoloJvJoCode())
						|| (this.getSoloJvJoCode() != null && castOther.getSoloJvJoCode() != null
								&& this.getSoloJvJoCode().equals(castOther.getSoloJvJoCode())))
				&& ((this.getSoloJvJo() == castOther.getSoloJvJo()) || (this.getSoloJvJo() != null
						&& castOther.getSoloJvJo() != null && this.getSoloJvJo().equals(castOther.getSoloJvJo())))
				&& ((this.getDatePlannedStart() == castOther.getDatePlannedStart())
						|| (this.getDatePlannedStart() != null && castOther.getDatePlannedStart() != null
								&& this.getDatePlannedStart().equals(castOther.getDatePlannedStart())))
				&& ((this.getDateActualStart() == castOther.getDateActualStart())
						|| (this.getDateActualStart() != null && castOther.getDateActualStart() != null
								&& this.getDateActualStart().equals(castOther.getDateActualStart())))
				&& ((this.getDatePlannedEnd() == castOther.getDatePlannedEnd())
						|| (this.getDatePlannedEnd() != null && castOther.getDatePlannedEnd() != null
								&& this.getDatePlannedEnd().equals(castOther.getDatePlannedEnd())))
				&& ((this.getDateActualEnd() == castOther.getDateActualEnd())
						|| (this.getDateActualEnd() != null && castOther.getDateActualEnd() != null
								&& this.getDateActualEnd().equals(castOther.getDateActualEnd())))
				&& ((this.getDateAnticipatedCompletion() == castOther.getDateAnticipatedCompletion())
						|| (this.getDateAnticipatedCompletion() != null
								&& castOther.getDateAnticipatedCompletion() != null
								&& this.getDateAnticipatedCompletion()
										.equals(castOther.getDateAnticipatedCompletion())))
				&& ((this.getDateRevisedCompletion() == castOther.getDateRevisedCompletion())
						|| (this.getDateRevisedCompletion() != null && castOther.getDateRevisedCompletion() != null
								&& this.getDateRevisedCompletion().equals(castOther.getDateRevisedCompletion())))
				&& ((this.getEntityJobKey() == castOther.getEntityJobKey())
						|| (this.getEntityJobKey() != null && castOther.getEntityJobKey() != null
								&& this.getEntityJobKey().equals(castOther.getEntityJobKey())))
				&& ((this.getNumberClientContract() == castOther.getNumberClientContract())
						|| (this.getNumberClientContract() != null && castOther.getNumberClientContract() != null
								&& this.getNumberClientContract().equals(castOther.getNumberClientContract())))
				&& ((this.getPercentageJv() == castOther.getPercentageJv())
						|| (this.getPercentageJv() != null && castOther.getPercentageJv() != null
								&& this.getPercentageJv().equals(castOther.getPercentageJv())))
				&& ((this.getAmountOriginalContract() == castOther.getAmountOriginalContract())
						|| (this.getAmountOriginalContract() != null && castOther.getAmountOriginalContract() != null
								&& this.getAmountOriginalContract().equals(castOther.getAmountOriginalContract())))
				&& ((this.getAmountProjectedContract() == castOther.getAmountProjectedContract())
						|| (this.getAmountProjectedContract() != null && castOther.getAmountProjectedContract() != null
								&& this.getAmountProjectedContract().equals(castOther.getAmountProjectedContract())))
				&& ((this.getTenderGp() == castOther.getTenderGp()) || (this.getTenderGp() != null
						&& castOther.getTenderGp() != null && this.getTenderGp().equals(castOther.getTenderGp())))
				&& ((this.getDateForecastEndPeriod() == castOther.getDateForecastEndPeriod())
						|| (this.getDateForecastEndPeriod() != null && castOther.getDateForecastEndPeriod() != null
								&& this.getDateForecastEndPeriod().equals(castOther.getDateForecastEndPeriod())))
				&& ((this.getDateForecastEndYear() == castOther.getDateForecastEndYear())
						|| (this.getDateForecastEndYear() != null && castOther.getDateForecastEndYear() != null
								&& this.getDateForecastEndYear().equals(castOther.getDateForecastEndYear())))
				&& ((this.getDateYearOfCompletion() == castOther.getDateYearOfCompletion())
						|| (this.getDateYearOfCompletion() != null && castOther.getDateYearOfCompletion() != null
								&& this.getDateYearOfCompletion().equals(castOther.getDateYearOfCompletion())))
				&& ((this.getPercentageRetentionMaximum() == castOther.getPercentageRetentionMaximum())
						|| (this.getPercentageRetentionMaximum() != null
								&& castOther.getPercentageRetentionMaximum() != null
								&& this.getPercentageRetentionMaximum()
										.equals(castOther.getPercentageRetentionMaximum())))
				&& ((this.getPercentageRetentionInterim() == castOther.getPercentageRetentionInterim())
						|| (this.getPercentageRetentionInterim() != null
								&& castOther.getPercentageRetentionInterim() != null
								&& this.getPercentageRetentionInterim()
										.equals(castOther.getPercentageRetentionInterim())))
				&& ((this.getPercentageDefectProvision() == castOther.getPercentageDefectProvision())
						|| (this.getPercentageDefectProvision() != null
								&& castOther.getPercentageDefectProvision() != null
								&& this.getPercentageDefectProvision()
										.equals(castOther.getPercentageDefectProvision())))
				&& ((this.getCpfApplicable() == castOther.getCpfApplicable())
						|| (this.getCpfApplicable() != null && castOther.getCpfApplicable() != null
								&& this.getCpfApplicable().equals(castOther.getCpfApplicable())))
				&& ((this.getCpfIndexName() == castOther.getCpfIndexName())
						|| (this.getCpfIndexName() != null && castOther.getCpfIndexName() != null
								&& this.getCpfIndexName().equals(castOther.getCpfIndexName())))
				&& ((this.getCpfBasePeriod() == castOther.getCpfBasePeriod())
						|| (this.getCpfBasePeriod() != null && castOther.getCpfBasePeriod() != null
								&& this.getCpfBasePeriod().equals(castOther.getCpfBasePeriod())))
				&& ((this.getCpfBaseYear() == castOther.getCpfBaseYear())
						|| (this.getCpfBaseYear() != null && castOther.getCpfBaseYear() != null
								&& this.getCpfBaseYear().equals(castOther.getCpfBaseYear())))
				&& ((this.getLevyApplicable() == castOther.getLevyApplicable())
						|| (this.getLevyApplicable() != null && castOther.getLevyApplicable() != null
								&& this.getLevyApplicable().equals(castOther.getLevyApplicable())))
				&& ((this.getPercentageLevyCita() == castOther.getPercentageLevyCita())
						|| (this.getPercentageLevyCita() != null && castOther.getPercentageLevyCita() != null
								&& this.getPercentageLevyCita().equals(castOther.getPercentageLevyCita())))
				&& ((this.getPercentageLevyPcfb() == castOther.getPercentageLevyPcfb())
						|| (this.getPercentageLevyPcfb() != null && castOther.getPercentageLevyPcfb() != null
								&& this.getPercentageLevyPcfb().equals(castOther.getPercentageLevyPcfb())))
				&& ((this.getCurrencyCode() == castOther.getCurrencyCode())
						|| (this.getCurrencyCode() != null && castOther.getCurrencyCode() != null
								&& this.getCurrencyCode().equals(castOther.getCurrencyCode())))
				&& ((this.getCurrencyDecimal() == castOther.getCurrencyDecimal())
						|| (this.getCurrencyDecimal() != null && castOther.getCurrencyDecimal() != null
								&& this.getCurrencyDecimal().equals(castOther.getCurrencyDecimal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBusinessUnitCode() == null ? 0 : this.getBusinessUnitCode().hashCode());
		result = 37 * result
				+ (getBusinessUnitDescription() == null ? 0 : this.getBusinessUnitDescription().hashCode());
		result = 37 * result + (getCompanyCode() == null ? 0 : this.getCompanyCode().hashCode());
		result = 37 * result + (getCompanyName() == null ? 0 : this.getCompanyName().hashCode());
		result = 37 * result + (getBusinessType() == null ? 0 : this.getBusinessType().hashCode());
		result = 37 * result + (getJobType() == null ? 0 : this.getJobType().hashCode());
		result = 37 * result + (getContractTypeCode() == null ? 0 : this.getContractTypeCode().hashCode());
		result = 37 * result + (getContractType() == null ? 0 : this.getContractType().hashCode());
		result = 37 * result + (getImmediateCustomerNo() == null ? 0 : this.getImmediateCustomerNo().hashCode());
		result = 37 * result + (getImmediateCustomer() == null ? 0 : this.getImmediateCustomer().hashCode());
		result = 37 * result + (getIcustomerGroup() == null ? 0 : this.getIcustomerGroup().hashCode());
		result = 37 * result + (getUltimateCustomerNo() == null ? 0 : this.getUltimateCustomerNo().hashCode());
		result = 37 * result + (getUltimateCustomer() == null ? 0 : this.getUltimateCustomer().hashCode());
		result = 37 * result + (getUcustomerGroup() == null ? 0 : this.getUcustomerGroup().hashCode());
		result = 37 * result + (getRegionCode() == null ? 0 : this.getRegionCode().hashCode());
		result = 37 * result + (getSectionCode() == null ? 0 : this.getSectionCode().hashCode());
		result = 37 * result + (getSection() == null ? 0 : this.getSection().hashCode());
		result = 37 * result + (getDivisionCode() == null ? 0 : this.getDivisionCode().hashCode());
		result = 37 * result + (getDivision() == null ? 0 : this.getDivision().hashCode());
		result = 37 * result + (getDepartmentCode() == null ? 0 : this.getDepartmentCode().hashCode());
		result = 37 * result + (getDepartment() == null ? 0 : this.getDepartment().hashCode());
		result = 37 * result + (getInternalJobCode() == null ? 0 : this.getInternalJobCode().hashCode());
		result = 37 * result + (getInternalJob() == null ? 0 : this.getInternalJob().hashCode());
		result = 37 * result + (getSoloJvCode() == null ? 0 : this.getSoloJvCode().hashCode());
		result = 37 * result + (getSoloJv() == null ? 0 : this.getSoloJv().hashCode());
		result = 37 * result + (getContractSignedCode() == null ? 0 : this.getContractSignedCode().hashCode());
		result = 37 * result + (getProfitLossCode() == null ? 0 : this.getProfitLossCode().hashCode());
		result = 37 * result + (getProfitAndLossStatus() == null ? 0 : this.getProfitAndLossStatus().hashCode());
		result = 37 * result + (getBalanceSheetCode() == null ? 0 : this.getBalanceSheetCode().hashCode());
		result = 37 * result + (getBalanceSheetStatus() == null ? 0 : this.getBalanceSheetStatus().hashCode());
		result = 37 * result + (getBondRqmtCode() == null ? 0 : this.getBondRqmtCode().hashCode());
		result = 37 * result + (getBondRequirement() == null ? 0 : this.getBondRequirement().hashCode());
		result = 37 * result + (getSoloJvJoCode() == null ? 0 : this.getSoloJvJoCode().hashCode());
		result = 37 * result + (getSoloJvJo() == null ? 0 : this.getSoloJvJo().hashCode());
		result = 37 * result + (getDatePlannedStart() == null ? 0 : this.getDatePlannedStart().hashCode());
		result = 37 * result + (getDateActualStart() == null ? 0 : this.getDateActualStart().hashCode());
		result = 37 * result + (getDatePlannedEnd() == null ? 0 : this.getDatePlannedEnd().hashCode());
		result = 37 * result + (getDateActualEnd() == null ? 0 : this.getDateActualEnd().hashCode());
		result = 37 * result
				+ (getDateAnticipatedCompletion() == null ? 0 : this.getDateAnticipatedCompletion().hashCode());
		result = 37 * result + (getDateRevisedCompletion() == null ? 0 : this.getDateRevisedCompletion().hashCode());
		result = 37 * result + (getEntityJobKey() == null ? 0 : this.getEntityJobKey().hashCode());
		result = 37 * result + (getNumberClientContract() == null ? 0 : this.getNumberClientContract().hashCode());
		result = 37 * result + (getPercentageJv() == null ? 0 : this.getPercentageJv().hashCode());
		result = 37 * result + (getAmountOriginalContract() == null ? 0 : this.getAmountOriginalContract().hashCode());
		result = 37 * result
				+ (getAmountProjectedContract() == null ? 0 : this.getAmountProjectedContract().hashCode());
		result = 37 * result + (getTenderGp() == null ? 0 : this.getTenderGp().hashCode());
		result = 37 * result + (getDateForecastEndPeriod() == null ? 0 : this.getDateForecastEndPeriod().hashCode());
		result = 37 * result + (getDateForecastEndYear() == null ? 0 : this.getDateForecastEndYear().hashCode());
		result = 37 * result + (getDateYearOfCompletion() == null ? 0 : this.getDateYearOfCompletion().hashCode());
		result = 37 * result
				+ (getPercentageRetentionMaximum() == null ? 0 : this.getPercentageRetentionMaximum().hashCode());
		result = 37 * result
				+ (getPercentageRetentionInterim() == null ? 0 : this.getPercentageRetentionInterim().hashCode());
		result = 37 * result
				+ (getPercentageDefectProvision() == null ? 0 : this.getPercentageDefectProvision().hashCode());
		result = 37 * result + (getCpfApplicable() == null ? 0 : this.getCpfApplicable().hashCode());
		result = 37 * result + (getCpfIndexName() == null ? 0 : this.getCpfIndexName().hashCode());
		result = 37 * result + (getCpfBasePeriod() == null ? 0 : this.getCpfBasePeriod().hashCode());
		result = 37 * result + (getCpfBaseYear() == null ? 0 : this.getCpfBaseYear().hashCode());
		result = 37 * result + (getLevyApplicable() == null ? 0 : this.getLevyApplicable().hashCode());
		result = 37 * result + (getPercentageLevyCita() == null ? 0 : this.getPercentageLevyCita().hashCode());
		result = 37 * result + (getPercentageLevyPcfb() == null ? 0 : this.getPercentageLevyPcfb().hashCode());
		result = 37 * result + (getCurrencyCode() == null ? 0 : this.getCurrencyCode().hashCode());
		result = 37 * result + (getCurrencyDecimal() == null ? 0 : this.getCurrencyDecimal().hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "BusinessUnit [businessUnitCode=" + businessUnitCode + ", businessUnitDescription="
				+ businessUnitDescription + ", companyCode=" + companyCode + ", companyName=" + companyName
				+ ", businessType=" + businessType + ", jobType=" + jobType + ", contractTypeCode=" + contractTypeCode
				+ ", contractType=" + contractType + ", immediateCustomerNo=" + immediateCustomerNo
				+ ", immediateCustomer=" + immediateCustomer + ", icustomerGroup=" + icustomerGroup
				+ ", ultimateCustomerNo=" + ultimateCustomerNo + ", ultimateCustomer=" + ultimateCustomer
				+ ", ucustomerGroup=" + ucustomerGroup + ", regionCode=" + regionCode + ", sectionCode=" + sectionCode
				+ ", section=" + section + ", divisionCode=" + divisionCode + ", division=" + division
				+ ", departmentCode=" + departmentCode + ", department=" + department + ", internalJobCode="
				+ internalJobCode + ", internalJob=" + internalJob + ", soloJvCode=" + soloJvCode + ", soloJv=" + soloJv
				+ ", contractSignedCode=" + contractSignedCode + ", profitLossCode=" + profitLossCode
				+ ", profitAndLossStatus=" + profitAndLossStatus + ", balanceSheetCode=" + balanceSheetCode
				+ ", balanceSheetStatus=" + balanceSheetStatus + ", bondRqmtCode=" + bondRqmtCode + ", bondRequirement="
				+ bondRequirement + ", soloJvJoCode=" + soloJvJoCode + ", soloJvJo=" + soloJvJo + ", datePlannedStart="
				+ datePlannedStart + ", dateActualStart=" + dateActualStart + ", datePlannedEnd=" + datePlannedEnd
				+ ", dateActualEnd=" + dateActualEnd + ", dateAnticipatedCompletion=" + dateAnticipatedCompletion
				+ ", dateRevisedCompletion=" + dateRevisedCompletion + ", entityJobKey=" + entityJobKey
				+ ", numberClientContract=" + numberClientContract + ", percentageJv=" + percentageJv
				+ ", amountOriginalContract=" + amountOriginalContract + ", amountProjectedContract="
				+ amountProjectedContract + ", tenderGp=" + tenderGp + ", dateForecastEndPeriod="
				+ dateForecastEndPeriod + ", dateForecastEndYear=" + dateForecastEndYear + ", dateYearOfCompletion="
				+ dateYearOfCompletion + ", percentageRetentionMaximum=" + percentageRetentionMaximum
				+ ", percentageRetentionInterim=" + percentageRetentionInterim + ", percentageDefectProvision="
				+ percentageDefectProvision + ", cpfApplicable=" + cpfApplicable + ", cpfIndexName=" + cpfIndexName
				+ ", cpfBasePeriod=" + cpfBasePeriod + ", cpfBaseYear=" + cpfBaseYear + ", levyApplicable="
				+ levyApplicable + ", percentageLevyCita=" + percentageLevyCita + ", percentageLevyPcfb="
				+ percentageLevyPcfb + ", currencyCode=" + currencyCode + ", currencyDecimal=" + currencyDecimal + "]";
	}

}
