package com.gammon.pcms.model.adl;
// Generated Jun 21, 2016 2:04:43 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * FactAccountBalance generated by hbm2java
 */
@Entity
@Table(name = "FACT_ACCOUNT_BALANCE")
@IdClass(FactAccountBalanceId.class)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class FactAccountBalance implements Serializable {

	private static final long serialVersionUID = -9074679324371187968L;
	private DimAccountMaster dimAccountMaster;
	private BigDecimal fiscalYear;
	private String accountTypeLedger;
	private String entityBusinessUnitKey;
	private String accountObject;
	private String accountSubsidiary;
	private String accountTypeSubLedger;
	private String accountSubLedger;
	private String entityCompanyKey;
	private String currencyLocal;
	private BigDecimal amountPriorYearNetPost;
	private BigDecimal amountBeginningBalance;
	private BigDecimal amountPeriod01;
	private BigDecimal amountPeriod02;
	private BigDecimal amountPeriod03;
	private BigDecimal amountPeriod04;
	private BigDecimal amountPeriod05;
	private BigDecimal amountPeriod06;
	private BigDecimal amountPeriod07;
	private BigDecimal amountPeriod08;
	private BigDecimal amountPeriod09;
	private BigDecimal amountPeriod10;
	private BigDecimal amountPeriod11;
	private BigDecimal amountPeriod12;
	private BigDecimal amountPeriod13;
	private BigDecimal amountPeriod14;
	private BigDecimal amountAccumPeriod01;
	private BigDecimal amountAccumPeriod02;
	private BigDecimal amountAccumPeriod03;
	private BigDecimal amountAccumPeriod04;
	private BigDecimal amountAccumPeriod05;
	private BigDecimal amountAccumPeriod06;
	private BigDecimal amountAccumPeriod07;
	private BigDecimal amountAccumPeriod08;
	private BigDecimal amountAccumPeriod09;
	private BigDecimal amountAccumPeriod10;
	private BigDecimal amountAccumPeriod11;
	private BigDecimal amountAccumPeriod12;
	private BigDecimal amountAccumPeriod13;
	private BigDecimal amountAccumPeriod14;

	public FactAccountBalance() {}

	public FactAccountBalance(DimAccountMaster dimAccountMaster, BigDecimal fiscalYear, String accountTypeLedger, String accountTypeSubLedger, String accountSubLedger) {
		this.dimAccountMaster = dimAccountMaster;
		this.fiscalYear = fiscalYear;
		this.accountTypeLedger = accountTypeLedger;
		this.accountTypeSubLedger = accountTypeSubLedger;
		this.accountSubLedger = accountSubLedger;
	}

	@Id
	public DimAccountMaster getDimAccountMaster() {
		return this.dimAccountMaster;
	}

	public void setDimAccountMaster(DimAccountMaster dimAccountMaster) {
		this.dimAccountMaster = dimAccountMaster;
	}

	@Id
	public BigDecimal getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(BigDecimal fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Id
	public String getAccountTypeLedger() {
		return this.accountTypeLedger;
	}

	public void setAccountTypeLedger(String accountTypeLedger) {
		this.accountTypeLedger = accountTypeLedger;
	}

	@Id
	public String getAccountSubLedger() {
		return this.accountSubLedger;
	}

	public void setAccountSubLedger(String accountSubLedger) {
		this.accountSubLedger = accountSubLedger;
	}

	@Column(name = "ENTITY_BUSINESS_UNIT_KEY",
			length = 48)
	public String getEntityBusinessUnitKey() {
		return this.entityBusinessUnitKey;
	}

	public void setEntityBusinessUnitKey(String entityBusinessUnitKey) {
		this.entityBusinessUnitKey = entityBusinessUnitKey;
	}

	@Column(name = "ACCOUNT_OBJECT",
			length = 24)
	public String getAccountObject() {
		return this.accountObject;
	}

	public void setAccountObject(String accountObject) {
		this.accountObject = accountObject;
	}

	@Column(name = "ACCOUNT_SUBSIDIARY",
			length = 32)
	public String getAccountSubsidiary() {
		return this.accountSubsidiary;
	}

	public void setAccountSubsidiary(String accountSubsidiary) {
		this.accountSubsidiary = accountSubsidiary;
	}

	@Column(name = "ACCOUNT_TYPE_SUB_LEDGER",
			nullable = false,
			length = 4)
	public String getAccountTypeSubLedger() {
		return this.accountTypeSubLedger;
	}

	public void setAccountTypeSubLedger(String accountTypeSubLedger) {
		this.accountTypeSubLedger = accountTypeSubLedger;
	}

	@Column(name = "ENTITY_COMPANY_KEY",
			length = 20)
	public String getEntityCompanyKey() {
		return this.entityCompanyKey;
	}

	public void setEntityCompanyKey(String entityCompanyKey) {
		this.entityCompanyKey = entityCompanyKey;
	}

	@Column(name = "CURRENCY_LOCAL",
			length = 12)
	public String getCurrencyLocal() {
		return this.currencyLocal;
	}

	public void setCurrencyLocal(String currencyLocal) {
		this.currencyLocal = currencyLocal;
	}

	@Column(name = "AMOUNT_PRIOR_YEAR_NET_POST",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPriorYearNetPost() {
		return this.amountPriorYearNetPost;
	}

	public void setAmountPriorYearNetPost(BigDecimal amountPriorYearNetPost) {
		this.amountPriorYearNetPost = amountPriorYearNetPost;
	}

	@Column(name = "AMOUNT_BEGINNING_BALANCE",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountBeginningBalance() {
		return this.amountBeginningBalance;
	}

	public void setAmountBeginningBalance(BigDecimal amountBeginningBalance) {
		this.amountBeginningBalance = amountBeginningBalance;
	}

	@Column(name = "AMOUNT_PERIOD_01",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod01() {
		return this.amountPeriod01;
	}

	public void setAmountPeriod01(BigDecimal amountPeriod01) {
		this.amountPeriod01 = amountPeriod01;
	}

	@Column(name = "AMOUNT_PERIOD_02",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod02() {
		return this.amountPeriod02;
	}

	public void setAmountPeriod02(BigDecimal amountPeriod02) {
		this.amountPeriod02 = amountPeriod02;
	}

	@Column(name = "AMOUNT_PERIOD_03",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod03() {
		return this.amountPeriod03;
	}

	public void setAmountPeriod03(BigDecimal amountPeriod03) {
		this.amountPeriod03 = amountPeriod03;
	}

	@Column(name = "AMOUNT_PERIOD_04",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod04() {
		return this.amountPeriod04;
	}

	public void setAmountPeriod04(BigDecimal amountPeriod04) {
		this.amountPeriod04 = amountPeriod04;
	}

	@Column(name = "AMOUNT_PERIOD_05",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod05() {
		return this.amountPeriod05;
	}

	public void setAmountPeriod05(BigDecimal amountPeriod05) {
		this.amountPeriod05 = amountPeriod05;
	}

	@Column(name = "AMOUNT_PERIOD_06",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod06() {
		return this.amountPeriod06;
	}

	public void setAmountPeriod06(BigDecimal amountPeriod06) {
		this.amountPeriod06 = amountPeriod06;
	}

	@Column(name = "AMOUNT_PERIOD_07",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod07() {
		return this.amountPeriod07;
	}

	public void setAmountPeriod07(BigDecimal amountPeriod07) {
		this.amountPeriod07 = amountPeriod07;
	}

	@Column(name = "AMOUNT_PERIOD_08",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod08() {
		return this.amountPeriod08;
	}

	public void setAmountPeriod08(BigDecimal amountPeriod08) {
		this.amountPeriod08 = amountPeriod08;
	}

	@Column(name = "AMOUNT_PERIOD_09",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod09() {
		return this.amountPeriod09;
	}

	public void setAmountPeriod09(BigDecimal amountPeriod09) {
		this.amountPeriod09 = amountPeriod09;
	}

	@Column(name = "AMOUNT_PERIOD_10",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod10() {
		return this.amountPeriod10;
	}

	public void setAmountPeriod10(BigDecimal amountPeriod10) {
		this.amountPeriod10 = amountPeriod10;
	}

	@Column(name = "AMOUNT_PERIOD_11",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod11() {
		return this.amountPeriod11;
	}

	public void setAmountPeriod11(BigDecimal amountPeriod11) {
		this.amountPeriod11 = amountPeriod11;
	}

	@Column(name = "AMOUNT_PERIOD_12",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod12() {
		return this.amountPeriod12;
	}

	public void setAmountPeriod12(BigDecimal amountPeriod12) {
		this.amountPeriod12 = amountPeriod12;
	}

	@Column(name = "AMOUNT_PERIOD_13",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod13() {
		return this.amountPeriod13;
	}

	public void setAmountPeriod13(BigDecimal amountPeriod13) {
		this.amountPeriod13 = amountPeriod13;
	}

	@Column(name = "AMOUNT_PERIOD_14",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountPeriod14() {
		return this.amountPeriod14;
	}

	public void setAmountPeriod14(BigDecimal amountPeriod14) {
		this.amountPeriod14 = amountPeriod14;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_01",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod01() {
		return this.amountAccumPeriod01;
	}

	public void setAmountAccumPeriod01(BigDecimal amountAccumPeriod01) {
		this.amountAccumPeriod01 = amountAccumPeriod01;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_02",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod02() {
		return this.amountAccumPeriod02;
	}

	public void setAmountAccumPeriod02(BigDecimal amountAccumPeriod02) {
		this.amountAccumPeriod02 = amountAccumPeriod02;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_03",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod03() {
		return this.amountAccumPeriod03;
	}

	public void setAmountAccumPeriod03(BigDecimal amountAccumPeriod03) {
		this.amountAccumPeriod03 = amountAccumPeriod03;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_04",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod04() {
		return this.amountAccumPeriod04;
	}

	public void setAmountAccumPeriod04(BigDecimal amountAccumPeriod04) {
		this.amountAccumPeriod04 = amountAccumPeriod04;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_05",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod05() {
		return this.amountAccumPeriod05;
	}

	public void setAmountAccumPeriod05(BigDecimal amountAccumPeriod05) {
		this.amountAccumPeriod05 = amountAccumPeriod05;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_06",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod06() {
		return this.amountAccumPeriod06;
	}

	public void setAmountAccumPeriod06(BigDecimal amountAccumPeriod06) {
		this.amountAccumPeriod06 = amountAccumPeriod06;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_07",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod07() {
		return this.amountAccumPeriod07;
	}

	public void setAmountAccumPeriod07(BigDecimal amountAccumPeriod07) {
		this.amountAccumPeriod07 = amountAccumPeriod07;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_08",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod08() {
		return this.amountAccumPeriod08;
	}

	public void setAmountAccumPeriod08(BigDecimal amountAccumPeriod08) {
		this.amountAccumPeriod08 = amountAccumPeriod08;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_09",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod09() {
		return this.amountAccumPeriod09;
	}

	public void setAmountAccumPeriod09(BigDecimal amountAccumPeriod09) {
		this.amountAccumPeriod09 = amountAccumPeriod09;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_10",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod10() {
		return this.amountAccumPeriod10;
	}

	public void setAmountAccumPeriod10(BigDecimal amountAccumPeriod10) {
		this.amountAccumPeriod10 = amountAccumPeriod10;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_11",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod11() {
		return this.amountAccumPeriod11;
	}

	public void setAmountAccumPeriod11(BigDecimal amountAccumPeriod11) {
		this.amountAccumPeriod11 = amountAccumPeriod11;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_12",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod12() {
		return this.amountAccumPeriod12;
	}

	public void setAmountAccumPeriod12(BigDecimal amountAccumPeriod12) {
		this.amountAccumPeriod12 = amountAccumPeriod12;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_13",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod13() {
		return this.amountAccumPeriod13;
	}

	public void setAmountAccumPeriod13(BigDecimal amountAccumPeriod13) {
		this.amountAccumPeriod13 = amountAccumPeriod13;
	}

	@Column(name = "AMOUNT_ACCUM_PERIOD_14",
			precision = 22,
			scale = 0)
	public BigDecimal getAmountAccumPeriod14() {
		return this.amountAccumPeriod14;
	}

	public void setAmountAccumPeriod14(BigDecimal amountAccumPeriod14) {
		this.amountAccumPeriod14 = amountAccumPeriod14;
	}

	@Override
	public String toString() {
		return "FactAccountBalance [dimAccountMaster=" + dimAccountMaster + ", fiscalYear=" + fiscalYear + ", accountTypeLedger=" + accountTypeLedger + ", entityBusinessUnitKey=" + entityBusinessUnitKey + ", accountObject=" + accountObject + ", accountSubsidiary=" + accountSubsidiary + ", accountTypeSubLedger=" + accountTypeSubLedger + ", accountSubLedger=" + accountSubLedger + ", entityCompanyKey=" + entityCompanyKey + ", currencyLocal=" + currencyLocal + ", amountPriorYearNetPost=" + amountPriorYearNetPost + ", amountBeginningBalance=" + amountBeginningBalance + ", amountPeriod01=" + amountPeriod01 + ", amountPeriod02=" + amountPeriod02 + ", amountPeriod03=" + amountPeriod03 + ", amountPeriod04=" + amountPeriod04 + ", amountPeriod05=" + amountPeriod05 + ", amountPeriod06=" + amountPeriod06 + ", amountPeriod07=" + amountPeriod07 + ", amountPeriod08=" + amountPeriod08 + ", amountPeriod09=" + amountPeriod09 + ", amountPeriod10=" + amountPeriod10 + ", amountPeriod11=" + amountPeriod11 + ", amountPeriod12=" + amountPeriod12 + ", amountPeriod13=" + amountPeriod13 + ", amountPeriod14=" + amountPeriod14 + ", amountAccumPeriod01=" + amountAccumPeriod01 + ", amountAccumPeriod02=" + amountAccumPeriod02 + ", amountAccumPeriod03=" + amountAccumPeriod03 + ", amountAccumPeriod04=" + amountAccumPeriod04 + ", amountAccumPeriod05=" + amountAccumPeriod05 + ", amountAccumPeriod06=" + amountAccumPeriod06 + ", amountAccumPeriod07=" + amountAccumPeriod07 + ", amountAccumPeriod08=" + amountAccumPeriod08 + ", amountAccumPeriod09=" + amountAccumPeriod09 + ", amountAccumPeriod10=" + amountAccumPeriod10 + ", amountAccumPeriod11=" + amountAccumPeriod11 + ", amountAccumPeriod12=" + amountAccumPeriod12 + ", amountAccumPeriod13=" + amountAccumPeriod13 + ", amountAccumPeriod14=" + amountAccumPeriod14 + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((accountObject == null) ? 0 : accountObject.hashCode());
		result = prime * result + ((accountSubLedger == null) ? 0 : accountSubLedger.hashCode());
		result = prime * result + ((accountSubsidiary == null) ? 0 : accountSubsidiary.hashCode());
		result = prime * result + ((accountTypeLedger == null) ? 0 : accountTypeLedger.hashCode());
		result = prime * result + ((accountTypeSubLedger == null) ? 0 : accountTypeSubLedger.hashCode());
		result = prime * result + ((amountAccumPeriod01 == null) ? 0 : amountAccumPeriod01.hashCode());
		result = prime * result + ((amountAccumPeriod02 == null) ? 0 : amountAccumPeriod02.hashCode());
		result = prime * result + ((amountAccumPeriod03 == null) ? 0 : amountAccumPeriod03.hashCode());
		result = prime * result + ((amountAccumPeriod04 == null) ? 0 : amountAccumPeriod04.hashCode());
		result = prime * result + ((amountAccumPeriod05 == null) ? 0 : amountAccumPeriod05.hashCode());
		result = prime * result + ((amountAccumPeriod06 == null) ? 0 : amountAccumPeriod06.hashCode());
		result = prime * result + ((amountAccumPeriod07 == null) ? 0 : amountAccumPeriod07.hashCode());
		result = prime * result + ((amountAccumPeriod08 == null) ? 0 : amountAccumPeriod08.hashCode());
		result = prime * result + ((amountAccumPeriod09 == null) ? 0 : amountAccumPeriod09.hashCode());
		result = prime * result + ((amountAccumPeriod10 == null) ? 0 : amountAccumPeriod10.hashCode());
		result = prime * result + ((amountAccumPeriod11 == null) ? 0 : amountAccumPeriod11.hashCode());
		result = prime * result + ((amountAccumPeriod12 == null) ? 0 : amountAccumPeriod12.hashCode());
		result = prime * result + ((amountAccumPeriod13 == null) ? 0 : amountAccumPeriod13.hashCode());
		result = prime * result + ((amountAccumPeriod14 == null) ? 0 : amountAccumPeriod14.hashCode());
		result = prime * result + ((amountBeginningBalance == null) ? 0 : amountBeginningBalance.hashCode());
		result = prime * result + ((amountPeriod01 == null) ? 0 : amountPeriod01.hashCode());
		result = prime * result + ((amountPeriod02 == null) ? 0 : amountPeriod02.hashCode());
		result = prime * result + ((amountPeriod03 == null) ? 0 : amountPeriod03.hashCode());
		result = prime * result + ((amountPeriod04 == null) ? 0 : amountPeriod04.hashCode());
		result = prime * result + ((amountPeriod05 == null) ? 0 : amountPeriod05.hashCode());
		result = prime * result + ((amountPeriod06 == null) ? 0 : amountPeriod06.hashCode());
		result = prime * result + ((amountPeriod07 == null) ? 0 : amountPeriod07.hashCode());
		result = prime * result + ((amountPeriod08 == null) ? 0 : amountPeriod08.hashCode());
		result = prime * result + ((amountPeriod09 == null) ? 0 : amountPeriod09.hashCode());
		result = prime * result + ((amountPeriod10 == null) ? 0 : amountPeriod10.hashCode());
		result = prime * result + ((amountPeriod11 == null) ? 0 : amountPeriod11.hashCode());
		result = prime * result + ((amountPeriod12 == null) ? 0 : amountPeriod12.hashCode());
		result = prime * result + ((amountPeriod13 == null) ? 0 : amountPeriod13.hashCode());
		result = prime * result + ((amountPeriod14 == null) ? 0 : amountPeriod14.hashCode());
		result = prime * result + ((amountPriorYearNetPost == null) ? 0 : amountPriorYearNetPost.hashCode());
		result = prime * result + ((currencyLocal == null) ? 0 : currencyLocal.hashCode());
		result = prime * result + ((dimAccountMaster == null) ? 0 : dimAccountMaster.hashCode());
		result = prime * result + ((entityBusinessUnitKey == null) ? 0 : entityBusinessUnitKey.hashCode());
		result = prime * result + ((entityCompanyKey == null) ? 0 : entityCompanyKey.hashCode());
		result = prime * result + ((fiscalYear == null) ? 0 : fiscalYear.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		FactAccountBalance other = (FactAccountBalance) obj;
		if (accountObject == null) {
			if (other.accountObject != null)
				return false;
		} else if (!accountObject.equals(other.accountObject))
			return false;
		if (accountSubLedger == null) {
			if (other.accountSubLedger != null)
				return false;
		} else if (!accountSubLedger.equals(other.accountSubLedger))
			return false;
		if (accountSubsidiary == null) {
			if (other.accountSubsidiary != null)
				return false;
		} else if (!accountSubsidiary.equals(other.accountSubsidiary))
			return false;
		if (accountTypeLedger == null) {
			if (other.accountTypeLedger != null)
				return false;
		} else if (!accountTypeLedger.equals(other.accountTypeLedger))
			return false;
		if (accountTypeSubLedger == null) {
			if (other.accountTypeSubLedger != null)
				return false;
		} else if (!accountTypeSubLedger.equals(other.accountTypeSubLedger))
			return false;
		if (amountAccumPeriod01 == null) {
			if (other.amountAccumPeriod01 != null)
				return false;
		} else if (!amountAccumPeriod01.equals(other.amountAccumPeriod01))
			return false;
		if (amountAccumPeriod02 == null) {
			if (other.amountAccumPeriod02 != null)
				return false;
		} else if (!amountAccumPeriod02.equals(other.amountAccumPeriod02))
			return false;
		if (amountAccumPeriod03 == null) {
			if (other.amountAccumPeriod03 != null)
				return false;
		} else if (!amountAccumPeriod03.equals(other.amountAccumPeriod03))
			return false;
		if (amountAccumPeriod04 == null) {
			if (other.amountAccumPeriod04 != null)
				return false;
		} else if (!amountAccumPeriod04.equals(other.amountAccumPeriod04))
			return false;
		if (amountAccumPeriod05 == null) {
			if (other.amountAccumPeriod05 != null)
				return false;
		} else if (!amountAccumPeriod05.equals(other.amountAccumPeriod05))
			return false;
		if (amountAccumPeriod06 == null) {
			if (other.amountAccumPeriod06 != null)
				return false;
		} else if (!amountAccumPeriod06.equals(other.amountAccumPeriod06))
			return false;
		if (amountAccumPeriod07 == null) {
			if (other.amountAccumPeriod07 != null)
				return false;
		} else if (!amountAccumPeriod07.equals(other.amountAccumPeriod07))
			return false;
		if (amountAccumPeriod08 == null) {
			if (other.amountAccumPeriod08 != null)
				return false;
		} else if (!amountAccumPeriod08.equals(other.amountAccumPeriod08))
			return false;
		if (amountAccumPeriod09 == null) {
			if (other.amountAccumPeriod09 != null)
				return false;
		} else if (!amountAccumPeriod09.equals(other.amountAccumPeriod09))
			return false;
		if (amountAccumPeriod10 == null) {
			if (other.amountAccumPeriod10 != null)
				return false;
		} else if (!amountAccumPeriod10.equals(other.amountAccumPeriod10))
			return false;
		if (amountAccumPeriod11 == null) {
			if (other.amountAccumPeriod11 != null)
				return false;
		} else if (!amountAccumPeriod11.equals(other.amountAccumPeriod11))
			return false;
		if (amountAccumPeriod12 == null) {
			if (other.amountAccumPeriod12 != null)
				return false;
		} else if (!amountAccumPeriod12.equals(other.amountAccumPeriod12))
			return false;
		if (amountAccumPeriod13 == null) {
			if (other.amountAccumPeriod13 != null)
				return false;
		} else if (!amountAccumPeriod13.equals(other.amountAccumPeriod13))
			return false;
		if (amountAccumPeriod14 == null) {
			if (other.amountAccumPeriod14 != null)
				return false;
		} else if (!amountAccumPeriod14.equals(other.amountAccumPeriod14))
			return false;
		if (amountBeginningBalance == null) {
			if (other.amountBeginningBalance != null)
				return false;
		} else if (!amountBeginningBalance.equals(other.amountBeginningBalance))
			return false;
		if (amountPeriod01 == null) {
			if (other.amountPeriod01 != null)
				return false;
		} else if (!amountPeriod01.equals(other.amountPeriod01))
			return false;
		if (amountPeriod02 == null) {
			if (other.amountPeriod02 != null)
				return false;
		} else if (!amountPeriod02.equals(other.amountPeriod02))
			return false;
		if (amountPeriod03 == null) {
			if (other.amountPeriod03 != null)
				return false;
		} else if (!amountPeriod03.equals(other.amountPeriod03))
			return false;
		if (amountPeriod04 == null) {
			if (other.amountPeriod04 != null)
				return false;
		} else if (!amountPeriod04.equals(other.amountPeriod04))
			return false;
		if (amountPeriod05 == null) {
			if (other.amountPeriod05 != null)
				return false;
		} else if (!amountPeriod05.equals(other.amountPeriod05))
			return false;
		if (amountPeriod06 == null) {
			if (other.amountPeriod06 != null)
				return false;
		} else if (!amountPeriod06.equals(other.amountPeriod06))
			return false;
		if (amountPeriod07 == null) {
			if (other.amountPeriod07 != null)
				return false;
		} else if (!amountPeriod07.equals(other.amountPeriod07))
			return false;
		if (amountPeriod08 == null) {
			if (other.amountPeriod08 != null)
				return false;
		} else if (!amountPeriod08.equals(other.amountPeriod08))
			return false;
		if (amountPeriod09 == null) {
			if (other.amountPeriod09 != null)
				return false;
		} else if (!amountPeriod09.equals(other.amountPeriod09))
			return false;
		if (amountPeriod10 == null) {
			if (other.amountPeriod10 != null)
				return false;
		} else if (!amountPeriod10.equals(other.amountPeriod10))
			return false;
		if (amountPeriod11 == null) {
			if (other.amountPeriod11 != null)
				return false;
		} else if (!amountPeriod11.equals(other.amountPeriod11))
			return false;
		if (amountPeriod12 == null) {
			if (other.amountPeriod12 != null)
				return false;
		} else if (!amountPeriod12.equals(other.amountPeriod12))
			return false;
		if (amountPeriod13 == null) {
			if (other.amountPeriod13 != null)
				return false;
		} else if (!amountPeriod13.equals(other.amountPeriod13))
			return false;
		if (amountPeriod14 == null) {
			if (other.amountPeriod14 != null)
				return false;
		} else if (!amountPeriod14.equals(other.amountPeriod14))
			return false;
		if (amountPriorYearNetPost == null) {
			if (other.amountPriorYearNetPost != null)
				return false;
		} else if (!amountPriorYearNetPost.equals(other.amountPriorYearNetPost))
			return false;
		if (currencyLocal == null) {
			if (other.currencyLocal != null)
				return false;
		} else if (!currencyLocal.equals(other.currencyLocal))
			return false;
		if (dimAccountMaster == null) {
			if (other.dimAccountMaster != null)
				return false;
		} else if (!dimAccountMaster.equals(other.dimAccountMaster))
			return false;
		if (entityBusinessUnitKey == null) {
			if (other.entityBusinessUnitKey != null)
				return false;
		} else if (!entityBusinessUnitKey.equals(other.entityBusinessUnitKey))
			return false;
		if (entityCompanyKey == null) {
			if (other.entityCompanyKey != null)
				return false;
		} else if (!entityCompanyKey.equals(other.entityCompanyKey))
			return false;
		if (fiscalYear == null) {
			if (other.fiscalYear != null)
				return false;
		} else if (!fiscalYear.equals(other.fiscalYear))
			return false;
		return true;
	}

}
