ALTER SESSION SET CURRENT_SCHEMA = PCMSDATAPROD;

INSERT INTO PERSONNEL_MAP
(ID, TITLE, USER_GROUP, USER_SEQUENCE, REQUIRED_APPROVAL, STATUS, USERNAME_CREATED, DATE_CREATED, USERNAME_LAST_MODIFIED, DATE_LAST_MODIFIED)
VALUES(17, 'Budget Owner', 'Budget Owner', 17, 'N', 'ACTIVE', 'IDT', sysdate, 'IDT', sysdate);

ALTER TABLE PERSONNEL ADD (DESCRIPTION VARCHAR2(255 CHAR) );
ALTER TABLE PERSONNEL_AUDIT ADD (DESCRIPTION VARCHAR2(255 CHAR) );
