-- 4. new tables 
--------------------------------------------------------
--  DDL for Table ADDENDUM
--------------------------------------------------------
-- Sequences

SPOOL C:\4.LOG
SET ECHO ON;
CREATE SEQUENCE  PCMSDATAPROD.ADDENDUM_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999999999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

--table
CREATE TABLE PCMSDATAPROD.ADDENDUM(	
    ID                          NUMBER(19, 0),
    ID_SUBCONTRACT              NUMBER(19, 0),
    NO_JOB                      VARCHAR2(5 CHAR),
    NO_SUBCONTRACT              VARCHAR2(4 CHAR),
    DESCRIPTION_SUBCONTRACT     VARCHAR2(255 CHAR),
    NO_SUBCONTRACTOR            VARCHAR2(10 CHAR),
    NAME_SUBCONTRACTOR          VARCHAR2(255 CHAR),
    NO                          NUMBER(10, 0),
    TITLE                       VARCHAR2(255 CHAR),
    AMT_SUBCONTRACT_REMEASURED  NUMBER(19, 2),
    AMT_SUBCONTRACT_REVISED     NUMBER(19, 2),
    AMT_ADDENDUM_TOTAL          NUMBER(19, 2),
    AMT_ADDENDUM_TOTAL_TBA      NUMBER(19, 2),
    AMT_ADDENDUM                NUMBER(19, 2),
    AMT_SUBCONTRACT_REVISED_TBA NUMBER(19, 2),
    DATE_SUBMISSION             DATE,
    DATE_APPROVAL               DATE,
    STATUS                      VARCHAR2(20 CHAR),
    STATUS_APPROVAL             VARCHAR2(20 CHAR),
    NO_ADDENDUM_DETAIL_NEXT     NUMBER(10, 0),
    USERNAME_PREPARED_BY        VARCHAR2(20 CHAR),
    REMARKS                     VARCHAR2(1000 CHAR),
    USERNAME_CREATED            VARCHAR2(20 CHAR),
    DATE_CREATED                DATE,
    USERNAME_LAST_MODIFIED      VARCHAR2(20 CHAR),
    DATE_LAST_MODIFIED          DATE,
	CONSTRAINT ADDENDUM_PK PRIMARY KEY(ID)ENABLE
);
-- Constraints
-- ALTER TABLE ADDENDUM ADD PRIMARY KEY (ID);

ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (NO_JOB NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (NO_SUBCONTRACT NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (NO_SUBCONTRACTOR NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (NO NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (USERNAME_CREATED NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (DATE_CREATED NOT NULL ENABLE);

ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (AMT_SUBCONTRACT_REMEASURED DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (AMT_SUBCONTRACT_REVISED DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (AMT_ADDENDUM_TOTAL DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (AMT_ADDENDUM_TOTAL_TBA DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (AMT_ADDENDUM DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM MODIFY (AMT_SUBCONTRACT_REVISED_TBA DEFAULT 0);
--Index
-- alter index SYS_C0041482 rename to ADDENDUM_PK;   

--------------------------------------------------------
--  DDL for Table ADDENDUM_DETAIL
--------------------------------------------------------
-- Sequences
CREATE SEQUENCE  PCMSDATAPROD.ADDENDUM_DETAIL_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999999999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

--table
CREATE TABLE PCMSDATAPROD.ADDENDUM_DETAIL(
    ID                          NUMBER(19, 0),
    ID_ADDENDUM                 NUMBER(19, 0),
    ID_RESOURCE_SUMMARY         NUMBER(19, 0),
    ID_SUBCONTRACT_DETAIL       NUMBER(19, 0),
    NO_JOB                      VARCHAR2(5 CHAR),
    NO_SUBCONTRACT              VARCHAR2(4 CHAR),
    NO                          NUMBER(10, 0),
    TYPE_HD                     VARCHAR2(10 CHAR),
    TYPE_VO                     VARCHAR2(2 CHAR),
    TYPE_ACTION                 VARCHAR2(10 CHAR),
    BPI                         VARCHAR2(255 CHAR),
    DESCRIPTION                 VARCHAR2(2000 CHAR),
    QUANTITY                    NUMBER(19, 4),
    RATE_ADDENDUM               NUMBER(19, 4),
    AMT_ADDENDUM                NUMBER(19, 2),
    RATE_BUDGET                 NUMBER(19, 4),
    AMT_BUDGET                  NUMBER(19, 2),
    QUANTITY_TBA                NUMBER(19, 4),
    RATE_ADDENDUM_TBA           NUMBER(19, 4),
    AMT_ADDENDUM_TBA            NUMBER(19, 2),
    RATE_BUDGET_TBA             NUMBER(19, 4),
    AMT_BUDGET_TBA              NUMBER(19, 2),
    CODE_OBJECT                 VARCHAR2(6 CHAR),
    CODE_SUBSIDIARY             VARCHAR2(8 CHAR),
    UNIT                        VARCHAR2(10 CHAR),
    REMARKS                     VARCHAR2(500 CHAR),
    CODE_OBJECT_FOR_DAYWORK     VARCHAR2(6 CHAR),
    NO_SUBCONTRACT_CHARGED_REF  VARCHAR2(4 CHAR),
    ID_HEADER_REF               NUMBER(19, 0),
    USERNAME_CREATED            VARCHAR2(20 CHAR),
    DATE_CREATED                DATE,
    USERNAME_LAST_MODIFIED      VARCHAR2(20 CHAR),
    DATE_LAST_MODIFIED          DATE,
	CONSTRAINT ADDENDUM_DETAIL_PK PRIMARY KEY(ID)ENABLE
);

-- Constraints
-- ALTER TABLE ADDENDUM_DETAIL ADD PRIMARY KEY (ID);

ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (ID_ADDENDUM NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (NO_JOB NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (NO_SUBCONTRACT NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (NO NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (TYPE_HD NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (USERNAME_CREATED NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (DATE_CREATED NOT NULL ENABLE);

ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (QUANTITY DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (RATE_ADDENDUM DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (AMT_ADDENDUM DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (RATE_BUDGET DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (AMT_BUDGET DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (QUANTITY_TBA DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (RATE_ADDENDUM_TBA DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (AMT_ADDENDUM_TBA DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (RATE_BUDGET_TBA DEFAULT 0);
ALTER TABLE PCMSDATAPROD.ADDENDUM_DETAIL MODIFY (AMT_BUDGET_TBA DEFAULT 0);

--Index
-- alter index SYS_C0041418 rename to ADDENDUM_DETAIL_PK;               

--------------------------------------------------------
--  DDL for Table ATTACHMENT
--------------------------------------------------------
-- Sequences
CREATE SEQUENCE  PCMSDATAPROD.ATTACHMENT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999999999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

-- Table
CREATE TABLE PCMSDATAPROD.ATTACHMENT(
  ID                      NUMBER(19, 0),
  ID_TABLE                NUMBER(19, 0),
  NAME_TABLE              VARCHAR2(30 CHAR),
  NO_SEQUENCE             NUMBER(19, 0),
  TYPE_DOCUMENT           VARCHAR2(10 CHAR),
  NAME_FILE               VARCHAR2(100 CHAR),
  PATH_FILE               VARCHAR2(500 CHAR),
  TEXT                    VARCHAR2(2000 CHAR),
  USERNAME_CREATED        VARCHAR2(20 CHAR),
  DATE_CREATED            DATE,
  USERNAME_LAST_MODIFIED  VARCHAR2(20 CHAR),
  DATE_LAST_MODIFIED      DATE,
  CONSTRAINT ATTACHMENT_PK PRIMARY KEY(ID)ENABLE
);
-- Constraints
-- ALTER TABLE ATTACHMENT ADD PRIMARY KEY (ID);

ALTER TABLE PCMSDATAPROD.ATTACHMENT MODIFY (ID_TABLE NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ATTACHMENT MODIFY (NAME_TABLE NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ATTACHMENT MODIFY (NO_SEQUENCE NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ATTACHMENT MODIFY (TYPE_DOCUMENT NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ATTACHMENT MODIFY (USERNAME_CREATED NOT NULL ENABLE);
ALTER TABLE PCMSDATAPROD.ATTACHMENT MODIFY (DATE_CREATED NOT NULL ENABLE);
-- Index
-- alter index SYS_C0041434 rename to ATTACHMENT_PK; 

--------------------------------------------------------
--  Grant privileges on tables & sequences
--------------------------------------------------------
/* GRANT PRIVILEGES ON TABLES */
BEGIN
   FOR r IN (SELECT owner, table_name FROM all_tables WHERE owner='PCMSDATAPROD') LOOP
      EXECUTE IMMEDIATE 'GRANT INSERT, SELECT, UPDATE, DELETE on '||r.owner||'.'||r.table_name||' to PCMSUSER_ROLE';
   END LOOP;
END;
/
BEGIN
   FOR r IN (SELECT owner, table_name FROM all_tables WHERE owner='PCMSDATAPROD') LOOP
      EXECUTE IMMEDIATE 'GRANT SELECT on '||r.owner||'.'||r.table_name||' to IMS_SUPPORT_ROLE_QS';
   END LOOP;
END;
/

/* GRANT PRIVILEGES ON SEQUENCE */
BEGIN   
   FOR s IN (SELECT * FROM USER_SEQUENCES) LOOP
      EXECUTE IMMEDIATE 'GRANT select on ' || s.SEQUENCE_NAME || ' to PCMSUSER_ROLE';
   END LOOP;
END;
/

BEGIN   
   FOR s IN (SELECT * FROM USER_SEQUENCES) LOOP
      EXECUTE IMMEDIATE 'GRANT select on ' || s.SEQUENCE_NAME || ' to IMS_SUPPORT_ROLE_QS';
   END LOOP;
END;
/


SPOOL OFF;