SPOOL C:\PCMSDATATST\4.LOG;
SET ECHO ON;
-- 4. new tables 
--------------------------------------------------------
--  DDL for Table TENDER_VARIANCE
--------------------------------------------------------
-- Sequences
CREATE SEQUENCE  "PCMSDATATST"."TENDER_VARIANCE_SEQ"
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999999999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

--table
CREATE UNIQUE INDEX PCMSDATATST.TENDER_VARIANCE_PK ON PCMSDATATST.TENDER_VARIANCE (ID ASC);
CREATE TABLE "PCMSDATATST"."TENDER_VARIANCE"(	
    "ID"                          NUMBER(19, 0),
    "ID_TENDER"                   NUMBER(19, 0),
    "NO_JOB"                      VARCHAR2(5 CHAR),
    "NO_SUBCONTRACT"              VARCHAR2(4 CHAR),
    "NO_SUBCONTRACTOR"            VARCHAR2(10 CHAR),
    "NAME_SUBCONTRACTOR"          VARCHAR2(255 CHAR),
    "CLAUSE"                      VARCHAR2(500 CHAR),
    "GENERAL_CONDITION"           VARCHAR2(2000 CHAR),
    "PROPOSED_VARIANCE"           VARCHAR2(2000 CHAR),
    "REASON"                      VARCHAR2(2000 CHAR),
    "USERNAME_CREATED"            VARCHAR2(20 CHAR),
    "DATE_CREATED"                DATE,
    "USERNAME_LAST_MODIFIED"      VARCHAR2(20 CHAR),
    "DATE_LAST_MODIFIED"          DATE,
    CONSTRAINT TENDER_VARIANCE_PK PRIMARY KEY(ID)ENABLE
);
-- Constraints
-- ALTER TABLE "TENDER_VARIANCE" ADD PRIMARY KEY ("ID");

ALTER TABLE "PCMSDATATST"."TENDER_VARIANCE" MODIFY ("ID_TENDER" NOT NULL ENABLE);
ALTER TABLE "PCMSDATATST"."TENDER_VARIANCE" MODIFY ("NO_JOB" NOT NULL ENABLE);
ALTER TABLE "PCMSDATATST"."TENDER_VARIANCE" MODIFY ("NO_SUBCONTRACT" NOT NULL ENABLE);
ALTER TABLE "PCMSDATATST"."TENDER_VARIANCE" MODIFY ("NO_SUBCONTRACTOR" NOT NULL ENABLE);
ALTER TABLE "PCMSDATATST"."TENDER_VARIANCE" MODIFY ("USERNAME_CREATED" NOT NULL ENABLE);
ALTER TABLE "PCMSDATATST"."TENDER_VARIANCE" MODIFY ("DATE_CREATED" NOT NULL ENABLE);

-- Index
-- alter index SYS_C0042377 rename to TENDER_VARIANCE_PK;
-- alter table TENDER_VARIANCE rename constraint SYS_C0042377 to TENDER_VARIANCE_PK;

--------------------------------------------------------
--  Grant privileges on tables & sequences
--------------------------------------------------------
/* GRANT PRIVILEGES ON TABLES */
BEGIN
   FOR r IN (SELECT owner, table_name FROM all_tables WHERE owner='PCMSDATATST') LOOP
      EXECUTE IMMEDIATE 'GRANT INSERT, SELECT, UPDATE, DELETE on '||r.owner||'.'||r.table_name||' to PCMSUSER_ROLE';
   END LOOP;
END;
/
/*
BEGIN
   FOR r IN (SELECT owner, table_name FROM all_tables WHERE owner='PCMSDATATST') LOOP
      EXECUTE IMMEDIATE 'GRANT SELECT on '||r.owner||'.'||r.table_name||' to IMS_SUPPORT_ROLE_QS';
   END LOOP;
END;
/
*/

/* GRANT PRIVILEGES ON SEQUENCE */
BEGIN   
   FOR s IN (SELECT * FROM USER_SEQUENCES) LOOP
      EXECUTE IMMEDIATE 'GRANT select on ' || s.SEQUENCE_NAME || ' to PCMSUSER_ROLE';
   END LOOP;
END;
/
/*
BEGIN   
   FOR s IN (SELECT * FROM USER_SEQUENCES) LOOP
      EXECUTE IMMEDIATE 'GRANT select on ' || s.SEQUENCE_NAME || ' to IMS_SUPPORT_ROLE_QS';
   END LOOP;
END;
/
*/

SPOOL OFF;