ALTER TABLE "PCMSDATATST"."TENDER" ADD "AMT_BUYING_GAIN_LOSS" NUMBER(19, 2) DEFAULT 0;
ALTER TABLE "PCMSDATATST"."TENDER" ADD "REMARKS" VARCHAR2(500 CHAR) DEFAULT ' ';
ALTER TABLE "PCMSDATATST"."TENDER" ADD "STATUS_CHANGE_EXECUTION_OF_SC" VARCHAR2(10 CHAR) DEFAULT 'N/A';
ALTER TABLE "PCMSDATATST"."TENDER" ADD "USERNAME_PREPARED" VARCHAR2(20 CHAR);
ALTER TABLE "PCMSDATATST"."TENDER" ADD "DATE_PREPARED" DATE;
ALTER TABLE "PCMSDATATST"."TENDER" ADD "NAME_SUBCONTRACTOR" VARCHAR2(500 CHAR) DEFAULT ' ';
