--------------------------------------------------------
--  Alter Table - Add New Columns
--------------------------------------------------------
-- SUBCONTRACT
ALTER TABLE PCMSDATAPROD.SUBCONTRACT ADD NAME_SUBCONTRACTOR VARCHAR2(500 CHAR) DEFAULT ' ';
ALTER TABLE PCMSDATAPROD.SUBCONTRACT ADD NOTES VARCHAR2(1000 CHAR) DEFAULT ' ';
ALTER TABLE PCMSDATAPROD.SUBCONTRACT ADD WORK_SCOPE NUMBER(19, 0);

-- SUBCONTRACT_DETAIL
ALTER TABLE PCMSDATAPROD.SUBCONTRACT_DETAIL ADD AMT_SUBCONTRACT NUMBER(19, 2) DEFAULT 0;
ALTER TABLE PCMSDATAPROD.SUBCONTRACT_DETAIL ADD AMT_BUDGET NUMBER(19, 2) DEFAULT 0;

ALTER TABLE PCMSDATAPROD.SUBCONTRACT_DETAIL ADD AMT_CUMULATIVE_CERT NUMBER(19, 2) DEFAULT 0;
ALTER TABLE PCMSDATAPROD.SUBCONTRACT_DETAIL ADD AMT_POSTED_CERT NUMBER(19, 2) DEFAULT 0;
ALTER TABLE PCMSDATAPROD.SUBCONTRACT_DETAIL ADD AMT_CUMULATIVE_WD NUMBER(19, 2) DEFAULT 0;
ALTER TABLE PCMSDATAPROD.SUBCONTRACT_DETAIL ADD AMT_POSTED_WD NUMBER(19, 2) DEFAULT 0;
ALTER TABLE PCMSDATAPROD.SUBCONTRACT_DETAIL ADD AMT_SUBCONTRACT_NEW NUMBER(19, 2) DEFAULT 0;

-- PAYMENT_CERT_DETAIL
ALTER TABLE PCMSDATAPROD.PAYMENT_CERT_DETAIL ADD DESCRIPTION VARCHAR2(255 CHAR) DEFAULT ' ';

-- RESOURCE_SUMMARY
ALTER TABLE PCMSDATAPROD.RESOURCE_SUMMARY ADD AMT_BUDGET NUMBER(19, 2) DEFAULT 0;

-- RESOURCE
ALTER TABLE PCMSDATAPROD.BPI_ITEM_RESOURCE ADD AMT_BUDGET NUMBER(19, 2) DEFAULT 0;

-- BPI_ITEM
ALTER TABLE PCMSDATAPROD.BPI_ITEM ADD AMT_BUDGET NUMBER(19, 2) DEFAULT 0;
ALTER TABLE PCMSDATAPROD.BPI_ITEM ADD AMT_SELLING NUMBER(19, 2) DEFAULT 0;

-- TENDER_DETAIL
ALTER TABLE PCMSDATAPROD.TENDER_DETAIL ADD AMT_BUDGET NUMBER(19, 2) DEFAULT 0;
ALTER TABLE PCMSDATAPROD.TENDER_DETAIL ADD AMT_FOREIGN NUMBER(19, 2) DEFAULT 0;
ALTER TABLE PCMSDATAPROD.TENDER_DETAIL ADD AMT_SUBCONTRACT NUMBER(19, 2) DEFAULT 0;

-- SUBCONTRACT_SNAPSHOT
ALTER TABLE PCMSDATAPROD.SUBCONTRACT_SNAPSHOT
	ADD (
  	NAME_SUBCONTRACTOR VARCHAR2(500) DEFAULT ' ',
    NOTES VARCHAR2(1000) DEFAULT ' ',
    WORK_SCOPE NUMBER(19,0)
    );