ALTER session SET current_schema = PCMSDATADEV;

-- 1. Clean up previous data
/*
drop table ROC;
drop table ROC_AUDIT;
drop table ROC_DETAIL;
drop table ROC_DETAIL_AUDIT;
drop table ROC_SUBDETAIL;
drop table ROC_SUBDETAIL_AUDIT;
drop table ROC_CLASS_DESC_MAP;
drop table ROC_CLASS_DESC_MAP_AUDIT;

drop sequence ROC_SEQ;
drop sequence ROC_DETAIL_SEQ;
drop sequence ROC_SUBDETAIL_SEQ;
drop sequence ROC_CLASS_DESC_MAP_SEQ;

 */

-- 2. Recreate table for ROC and grant permission
CREATE TABLE ROC
(
    ID                 NUMBER(19) NOT NULL ENABLE,
    PROJECT_NO         VARCHAR2(5 CHAR) NOT NULL ENABLE,
    ITEM_NO            NUMBER(19) NOT NULL ENABLE,
    PROJECT_REF        VARCHAR2(10 CHAR),
    ROC_CAT            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    CLASSIFICATION     VARCHAR2(50 CHAR) NOT NULL ENABLE,
    IMPACT             VARCHAR2(50 CHAR) NOT NULL ENABLE,
    DESCRIPTION        VARCHAR2(300 CHAR) NOT NULL ENABLE,
    STATUS             VARCHAR2(10 CHAR) NOT NULL ENABLE,
    ROC_OWNER          VARCHAR2(20 CHAR),
    OPEN_DATE          DATE NOT NULL ENABLE,
    CLOSED_DATE        DATE,
    LAST_MODIFIED_DATE DATE NOT NULL ENABLE,
    LAST_MODIFIED_USER VARCHAR2(50),
    CREATED_DATE       DATE NOT NULL ENABLE,
    CREATED_USER       VARCHAR2(50) NOT NULL ENABLE,
    SYSTEM_STATUS      VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "ROC_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE TABLE ROC_AUDIT
(
    "ID"                 NUMBER(19,0) NOT NULL ENABLE,
    "REV"                NUMBER(10,0) NOT NULL ENABLE,
    "REVTYPE"            NUMBER(3,0),
    "PROJECT_NO"         VARCHAR2(5 CHAR) NOT NULL ENABLE,
    "ITEM_NO"            NUMBER(19,0) NOT NULL ENABLE,
    "PROJECT_REF"        VARCHAR2(10 CHAR),
    "ROC_CAT"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CLASSIFICATION"     VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "IMPACT"             VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "DESCRIPTION"        VARCHAR2(300 CHAR) NOT NULL ENABLE,
    "STATUS"             VARCHAR2(10 CHAR) NOT NULL ENABLE,
    "ROC_OWNER"          VARCHAR2(20 CHAR),
    "OPEN_DATE"          DATE NOT NULL ENABLE,
    "CLOSED_DATE"        DATE,
    "LAST_MODIFIED_DATE" DATE NOT NULL ENABLE,
    "LAST_MODIFIED_USER" VARCHAR2(50 BYTE),
    "CREATED_DATE"       DATE NOT NULL ENABLE,
    "CREATED_USER"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SYSTEM_STATUS"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ROC_AUDIT_ID_NN" CHECK ("ID"   IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_AUDIT_REV_NN" CHECK ("REV" IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_AUDIT_PK" PRIMARY KEY ("ID", "REV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE TABLE ROC_DETAIL
(
    ID                 NUMBER(19) NOT NULL ENABLE,
    ID_ROC             NUMBER(19) NOT NULL ENABLE,
    AMOUNT_BEST        NUMBER(19, 2) DEFAULT 0,
    AMOUNT_EXPECTED    NUMBER(19, 2) DEFAULT 0,
    AMOUNT_WORST       NUMBER(19, 2) DEFAULT 0,
    REMARKS            VARCHAR2(4000 CHAR),
    YEAR               NUMBER(4) NOT NULL ENABLE,
    MONTH              NUMBER(2) NOT NULL ENABLE,
    STATUS             VARCHAR2(10 CHAR) NOT NULL ENABLE,
    LAST_MODIFIED_DATE DATE NOT NULL,
    LAST_MODIFIED_USER VARCHAR2(50),
    CREATED_DATE       DATE NOT NULL ENABLE,
    CREATED_USER       VARCHAR2(50) NOT NULL ENABLE,
    SYSTEM_STATUS      VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "ROC_DETAIL_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE TABLE ROC_DETAIL_AUDIT
(
    "ID"                 NUMBER(19,0) NOT NULL ENABLE,
    "REV"                NUMBER(10,0) NOT NULL ENABLE,
    "REVTYPE"            NUMBER(3,0),
    "ID_ROC"             NUMBER(19,0) NOT NULL ENABLE,
    "AMOUNT_BEST"        NUMBER(19,2) DEFAULT 0,
    "AMOUNT_EXPECTED"    NUMBER(19,2) DEFAULT 0,
    "AMOUNT_WORST"       NUMBER(19,2) DEFAULT 0,
    "REMARKS"            VARCHAR2(4000 CHAR),
    "YEAR"               NUMBER(4,0) NOT NULL ENABLE,
    "MONTH"              NUMBER(2,0) NOT NULL ENABLE,
    "STATUS"             VARCHAR2(10 CHAR) NOT NULL ENABLE,
    "LAST_MODIFIED_DATE" DATE NOT NULL ENABLE,
    "LAST_MODIFIED_USER" VARCHAR2(50 BYTE),
    "CREATED_DATE"       DATE NOT NULL ENABLE,
    "CREATED_USER"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SYSTEM_STATUS"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ROC_DETAIL_AUDIT_ID_NN" CHECK ("ID"   IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_DETAIL_AUDIT_REV_NN" CHECK ("REV" IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_DETAIL_AUDIT_PK" PRIMARY KEY ("ID", "REV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE TABLE ROC_SUBDETAIL
(
    ID                 NUMBER(19) NOT NULL ENABLE,
    ID_ROC             NUMBER(19) NOT NULL ENABLE,
    DESCRIPTION        VARCHAR2(300 CHAR) NOT NULL ENABLE,
    AMOUNT_BEST        NUMBER(19, 2) DEFAULT 0,
    AMOUNT_EXPECTED    NUMBER(19, 2) DEFAULT 0,
    AMOUNT_WORST       NUMBER(19, 2) DEFAULT 0,
--     INPUT_DATE         DATE NOT NULL ENABLE,
    YEAR               NUMBER(4) NOT NULL ENABLE,
    MONTH              NUMBER(2) NOT NULL ENABLE,
    HYPERLINK          VARCHAR2(2083 CHAR),
    REMARKS            VARCHAR2(4000 CHAR),
    LAST_MODIFIED_DATE DATE NOT NULL ENABLE,
    LAST_MODIFIED_USER VARCHAR2(50),
    CREATED_DATE       DATE NOT NULL ENABLE,
    CREATED_USER       VARCHAR2(50) NOT NULL ENABLE,
    SYSTEM_STATUS      VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "ROC_SUBDETAIL_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE TABLE ROC_SUBDETAIL_AUDIT
(
    "ID"                 NUMBER(19,0) NOT NULL ENABLE,
    "REV"                NUMBER(10,0) NOT NULL ENABLE,
    "REVTYPE"            NUMBER(3,0),
    "ID_ROC"             NUMBER(19,0) NOT NULL ENABLE,
    "DESCRIPTION"        VARCHAR2(300 CHAR) NOT NULL ENABLE,
    "AMOUNT_BEST"        NUMBER(19,2) DEFAULT 0,
    "AMOUNT_EXPECTED"    NUMBER(19,2) DEFAULT 0,
    "AMOUNT_WORST"       NUMBER(19,2) DEFAULT 0,
--     "INPUT_DATE"         DATE NOT NULL ENABLE,
    "YEAR"               NUMBER(4) NOT NULL ENABLE,
    "MONTH"              NUMBER(2) NOT NULL ENABLE,
    "HYPERLINK"          VARCHAR2(2083 CHAR),
    "REMARKS"            VARCHAR2(4000 CHAR),
    "LAST_MODIFIED_DATE" DATE NOT NULL ENABLE,
    "LAST_MODIFIED_USER" VARCHAR2(50 BYTE),
    "CREATED_DATE"       DATE NOT NULL ENABLE,
    "CREATED_USER"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SYSTEM_STATUS"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ROC_SUBDETAIL_AUDIT_ID_NN" CHECK ("ID"   IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_SUBDETAIL_AUDIT_REV_NN" CHECK ("REV" IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_SUBDETAIL_AUDIT_PK" PRIMARY KEY ("ID", "REV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE TABLE ROC_CLASS_DESC_MAP
(
    ID                 NUMBER(19) NOT NULL ENABLE,
    CLASSIFICATION     VARCHAR2(50 CHAR) NOT NULL ENABLE,
    DESCRIPTION        VARCHAR2(300 CHAR) NOT NULL ENABLE,
    LAST_MODIFIED_DATE DATE NOT NULL ENABLE,
    LAST_MODIFIED_USER VARCHAR2(50),
    CREATED_DATE       DATE NOT NULL ENABLE,
    CREATED_USER       VARCHAR2(50) NOT NULL ENABLE,
    SYSTEM_STATUS      VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "ROC_CLASS_DESC_MAP_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE TABLE ROC_CLASS_DESC_MAP_AUDIT
(
    "ID"                 NUMBER(19,0) NOT NULL ENABLE,
    "REV"                NUMBER(10,0) NOT NULL ENABLE,
    "REVTYPE"            NUMBER(3,0),
    "CLASSIFICATION"     VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "DESCRIPTION"        VARCHAR2(300 CHAR) NOT NULL ENABLE,
    "LAST_MODIFIED_DATE" DATE NOT NULL ENABLE,
    "LAST_MODIFIED_USER" VARCHAR2(50 BYTE),
    "CREATED_DATE"       DATE NOT NULL ENABLE,
    "CREATED_USER"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SYSTEM_STATUS"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ROC_CLASS_DESC_MAP_AUDIT_ID_NN" CHECK ("ID" IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_CLASS_DE_MAP_AUDIT_REV_NN" CHECK ("REV" IS NOT NULL) ENABLE,
    CONSTRAINT "ROC_CLASS_DESC_MAP_AUDIT_FK" PRIMARY KEY ("ID", "REV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
);

CREATE sequence ROC_SEQ minvalue 1 nocache ;
CREATE sequence ROC_DETAIL_SEQ minvalue 1 nocache ;
CREATE sequence ROC_SUBDETAIL_SEQ minvalue 1 nocache ;
CREATE sequence ROC_CLASS_DESC_MAP_SEQ minvalue 1 nocache ;

GRANT SELECT, INSERT, UPDATE, DELETE ON ROC TO pcmsuser_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_AUDIT TO pcmsuser_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_DETAIL TO pcmsuser_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_DETAIL_AUDIT TO pcmsuser_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_SUBDETAIL to pcmsuser_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_SUBDETAIL_AUDIT to pcmsuser_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_CLASS_DESC_MAP TO pcmsuser_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROC_CLASS_DESC_MAP_AUDIT TO pcmsuser_role;
GRANT SELECT ON ROC_SEQ TO pcmsuser_role;
GRANT SELECT ON ROC_DETAIL_SEQ TO pcmsuser_role;
GRANT SELECT ON ROC_SUBDETAIL_SEQ TO pcmsuser_role;
GRANT SELECT ON ROC_CLASS_DESC_MAP_SEQ TO pcmsuser_role;

-- 3. Insert intial data
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'CPF Income', 'Income associated with CPF (Costs considered elsewhere)', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Variations Income', 'Income associated with Variations, Potential Variations or Future Variations or agreed in principle Compensation Events', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Claims Income', 'Income associated with Claims, Potential Claims or disputed Compensation Events', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Labour', 'Impact of labour costs (excluding Covid related)', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Staff', 'Impact of staff costs (excluding Covid related)', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Plant', 'Impact of plant costs (excluding Covid related)', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Materials', 'Impact of material costs (excl commodities buying gains or losses or Covid)', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Buying Losses Commodities', 'Buying losses on rebar, copper, steel, conc, etc', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Buying Gains Commodities', 'Buying gains on rebar, copper, steel, conc, etc', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Sub-Con', 'Impact of Sub-Con Costs (excl non Recoverable ISCs and buying gains \ losses)', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Non-Recoverable ISCs', 'Costs associated with non-recoverable ISCs', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Sub-Con Buying Losses', 'Income or Costs associated with Sub-Contract Buying losses', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Sub-Con Buying Gains', 'Income or Costs associated with Sub-Contract Buying gains', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Insurance', 'Insurance Claims, Premiums, ECI, etc', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Covid', 'Costs associated with Covid', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Damages', 'Impact of Liquidated or General Damages', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Defects', 'Impact of Defects and Outstanding Works', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Design issues', 'Impact of Design including late Approvals', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Safety Issues', 'Impact of Safety requirements or non-implementation of safety requirements', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Inspections and T&C', 'As E&M risks and opps normally arising from inspections and T&C', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
INSERT INTO ROC_CLASS_DESC_MAP (ID, CLASSIFICATION, DESCRIPTION, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS) VALUES (ROC_CLASS_DESC_MAP_SEQ.nextval, 'Others', 'If some items cannot match the exiting classification, the QS can input here, say additional storage cost that are incurred directly under GCL, not under SC/ Supplier; or impact to site running costs, etc', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2021-08-12', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'ACTIVE');
commit;
