create or replace Procedure PCMSDATAUAT.P_GENERATE_SUBCONTRACTSNAPSHOT Is
  SNAPSHOTDATE DATE := sysdate;

  CURRENTMONTH Varchar2(2);
  NEXTMONTH Varchar2(2);
  CURRENTYEAR varchar2(4);
  FROMDATE DATE;
  THRUDATE DATE;
  
  PID SUBCONTRACT_SNAPSHOT.ID%TYPE;
  
  SCPACKAGE_SNAPSHOT PCMSDATAUAT.SUBCONTRACT_SNAPSHOT%ROWTYPE;
  SCPACKAGE PCMSDATAUAT.SUBCONTRACT%ROWTYPE;
  
  TYPE Rcursor IS REF CURSOR;
  SNAPSHOTCURSOR Rcursor;
  
  CURSOR PACKAGECURSOR IS 
                      SELECT * FROM PCMSDATAUAT.SUBCONTRACT WHERE SYSTEM_STATUS = 'ACTIVE';
                      
                      
BEGIN    

    CURRENTMONTH:= To_Char(SNAPSHOTDATE, 'mm');
    CURRENTYEAR:= TO_CHAR(SNAPSHOTDATE, 'yyyy');
    
    FROMDATE:= To_Date('01'||Currentmonth||Currentyear, 'ddmmyyyy');
    --DBMS_OUTPUT.PUT_LINE('FROMDATE: '||FROMDATE);    
  
   
     IF(TO_NUMBER(CURRENTMONTH)<12) THEN
      NEXTMONTH := To_Char(To_Number(To_Char(SNAPSHOTDATE, 'mm'))+1);
      IF(LENGTH(NEXTMONTH)=1) THEN
        NEXTMONTH:= CONCAT('0',NEXTMONTH);
      END IF;
      --DBMS_OUTPUT.PUT_LINE('NEXTMONTH: '||NEXTMONTH);
      
      THRUDATE:=TO_DATE('01'||NEXTMONTH||CURRENTYEAR, 'ddmmyyyy')-1;
   
    Else
      THRUDATE:= TO_DATE('31'||Currentmonth||Currentyear, 'ddmmyyyy');
    End IF;
    
    --DBMS_OUTPUT.PUT_LINE('THRUDATE: '||THRUDATE);
    
    OPEN SNAPSHOTCURSOR FOR
          SELECT * FROM PCMSDATAUAT.SUBCONTRACT_SNAPSHOT WHERE SYSTEM_STATUS = 'ACTIVE' AND SNAPSHOT_DATE >= FROMDATE AND SNAPSHOT_DATE <= THRUDATE;
    LOOP
        FETCH SNAPSHOTCURSOR INTO SCPACKAGE_SNAPSHOT;
        EXIT WHEN SNAPSHOTCURSOR%NOTFOUND;
        
        UPDATE PCMSDATAUAT.SUBCONTRACT_SNAPSHOT
        SET SYSTEM_STATUS = 'INACTIVE'
        WHERE ID = SCPACKAGE_SNAPSHOT.ID;       
         
    END LOOP;
    CLOSE SNAPSHOTCURSOR;
    
    
    SELECT MAX(ID) INTO PID FROM PCMSDATAUAT.SUBCONTRACT_SNAPSHOT;
     IF (PID is null) THEN
        PID := 0;
    END IF;
    
    OPEN PACKAGECURSOR;
    LOOP
        FETCH PACKAGECURSOR INTO SCPACKAGE;     
        EXIT WHEN PACKAGECURSOR%NOTFOUND;
        
        PID := PID + 1;
  
        INSERT INTO PCMSDATAUAT.SUBCONTRACT_SNAPSHOT(ID, LAST_MODIFIED_DATE, LAST_MODIFIED_USER, CREATED_DATE, CREATED_USER, SYSTEM_STATUS, SUBCONTRACT_ID, JOB_INFO_ID, PACKAGENO, 
                    DESCRIPTION, PACKAGETYPE, VENDORNO, PACKAGESTATUS, SCSTATUS, SCNATURE, ORIGINALSCSUM, APPROVEDVOAMOUNT, REMEASUREDSCSUM, APPROVALROUTE, RETENTIONTERMS,
                    MAXRETPERCENT, INTERIMRETPERENT, MOSRETPERENT, RETAMOUNT, ACCUMLATEDRET, RETRELEASE, PAYMENTINFO, PAYMENTCURRENCY, EXCHANGERATE, PAYMENTTERMS, SCTERM,
                    CPFCALCULATION, CPFBASEPERIOD, CPFBASEYEAR, FORMOFSUBCONTRACT, INTERNALJOBNO, PAYMENTSTATUS, SUBMITTEDADDENDUM, LABOURINCLUDED, PLANTINCLUDED, MATERIALINCLUDED,
                    SPLITTERMINATESTATUS, TOTALPOSTEDCERTAMT, TOTALCUMCERTAMT, TOTALPOSTEDWDAMT, TOTALCUMWDAMT, TOTALCCPOSTEDCERTAMT, TOTALMOSPOSTEDCERTAMT, PAYMENTTERMSDESCRIPTION,
                    REQUISITION_APPROVED_DATE, TA_APPROVED_DATE, PREAWARD_MEETING_DATE, LOA_SIGNED_DATE, SC_DOC_SCR_DATE, SC_DOC_LEGAL_DATE, WORK_COMMENCE_DATE, ONSITE_START_DATE,
                    SNAPSHOT_DATE)
        VALUES (PID, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', 'ACTIVE', SCPACKAGE.ID, SCPACKAGE.JOB_INFO_ID, SCPACKAGE.PACKAGENO, SCPACKAGE.DESCRIPTION, SCPACKAGE.PACKAGETYPE, SCPACKAGE.VENDORNO, 
                SCPACKAGE.PACKAGESTATUS, SCPACKAGE.SCSTATUS, SCPACKAGE.SCNATURE, SCPACKAGE.ORIGINALSCSUM, SCPACKAGE.APPROVEDVOAMOUNT, SCPACKAGE.REMEASUREDSCSUM, SCPACKAGE.APPROVALROUTE, 
                SCPACKAGE.RETENTIONTERMS, SCPACKAGE.MAXRETPERCENT, SCPACKAGE.INTERIMRETPERENT, SCPACKAGE.MOSRETPERENT, SCPACKAGE.RETAMOUNT, SCPACKAGE.ACCUMLATEDRET, SCPACKAGE.RETRELEASE,
                SCPACKAGE.PAYMENTINFO, SCPACKAGE.PAYMENTCURRENCY, SCPACKAGE.EXCHANGERATE, SCPACKAGE.PAYMENTTERMS, SCPACKAGE.SCTERM, SCPACKAGE.CPFCALCULATION, SCPACKAGE.CPFBASEPERIOD, 
                SCPACKAGE.CPFBASEYEAR, SCPACKAGE.FORMOFSUBCONTRACT, SCPACKAGE.INTERNALJOBNO, SCPACKAGE.PAYMENTSTATUS, SCPACKAGE.SUBMITTEDADDENDUM, SCPACKAGE.LABOURINCLUDED, SCPACKAGE.PLANTINCLUDED, 
                SCPACKAGE.MATERIALINCLUDED, SCPACKAGE.SPLITTERMINATESTATUS, SCPACKAGE.TOTALPOSTEDCERTAMT, SCPACKAGE.TOTALCUMCERTAMT, SCPACKAGE.TOTALPOSTEDWDAMT, SCPACKAGE.TOTALCUMWDAMT, 
                SCPACKAGE.TOTALCCPOSTEDCERTAMT, SCPACKAGE.TOTALMOSPOSTEDCERTAMT, SCPACKAGE.PAYMENTTERMSDESCRIPTION, SCPACKAGE.REQUISITION_APPROVED_DATE, SCPACKAGE.TA_APPROVED_DATE, 
                SCPACKAGE.PREAWARD_MEETING_DATE, SCPACKAGE.LOA_SIGNED_DATE, SCPACKAGE.SC_DOC_SCR_DATE, SCPACKAGE.SC_DOC_LEGAL_DATE, SCPACKAGE.WORK_COMMENCE_DATE, SCPACKAGE.ONSITE_START_DATE,
                SNAPSHOTDATE);
         
    END LOOP;
    CLOSE PACKAGECURSOR;
    
    
    COMMIT;
    
END P_GENERATE_SUBCONTRACTSNAPSHOT;
/

grant EXECUTE on "PCMSDATAUAT"."P_GENERATE_SUBCONTRACTSNAPSHOT" to "PCMSUSER_ROLE";
/