--P_GENERATE_SUBCONTRACTSNAPSHOT
grant EXECUTE on PCMSDATATST.P_GENERATE_SUBCONTRACTSNAPSHOT to PCMSUSER_ROLE;

--P_QS_JOB
grant EXECUTE on PCMSDATATST.P_QS_JOB to PCMSUSER_ROLE;
grant select, update On CRPDTA.F0006 to PCMSDATATST;

--P_F03B14_UPDATE_QS_MAIN_CERT
grant EXECUTE on PCMSDATATST.P_F03B14_UPDATE_QS_MAIN_CERT to PCMSUSER_ROLE;
grant select On CRPDTA.F03b11 to PCMSDATATST;
grant select On CRPDTA.F03b14 to PCMSDATATST;

--P_QS_UPDATE_F58001
grant EXECUTE on PCMSDATATST.P_QS_UPDATE_F58001 to PCMSUSER_ROLE;
grant select, update, insert On  CRPDTA.F58001 to PCMSUSER_ROLE;

--P_QS_UPDATE_F58011
grant EXECUTE on PCMSDATATST.P_QS_UPDATE_F58011 to PCMSUSER_ROLE;
grant select, update, insert On CRPDTA.F58011 to PCMSUSER_ROLE;

--P_AUDIT_HOUSEKEEP
grant EXECUTE on PCMSDATATST.P_AUDIT_HOUSEKEEP to PCMSUSER_ROLE;
grant EXECUTE on PCMSDATATST.UNIX_TS_TO_DATE to PCMSUSER_ROLE ;

