--P_GENERATE_SUBCONTRACTSNAPSHOT
grant EXECUTE on "PCMSDATAUAT"."P_GENERATE_SUBCONTRACTSNAPSHOT" to "PCMSUSER_ROLE";

--P_QS_JOB
grant EXECUTE on "PCMSDATAUAT"."P_QS_JOB" to "PCMSUSER_ROLE";

--P_F03B14_UPDATE_QS_MAIN_CERT
grant EXECUTE on "PCMSDATAUAT"."P_F03B14_UPDATE_QS_MAIN_CERT" to "PCMSUSER_ROLE";
grant select On "CRPDTA"."F03b11" to "PCMSUSER_ROLE";
grant select On "CRPDTA"."P_F03b14" to "PCMSUSER_ROLE";

--P_QS_UPDATE_F58001
grant EXECUTE on "PCMSDATAUAT"."P_QS_UPDATE_F58001" to "PCMSUSER_ROLE";
grant select, update, insert On  "CRPDTA"."F58001" to "PCMSUSER_ROLE";

--P_QS_UPDATE_F58011
grant EXECUTE on "PCMSDATAUAT"."P_QS_UPDATE_F58011" to "PCMSUSER_ROLE";
grant select, update, insert On "CRPDTA"."F58011" to "PCMSUSER_ROLE";

--P_AUDIT_HOUSEKEEP
grant EXECUTE on "PCMSDATAUAT"."P_AUDIT_HOUSEKEEP" to "PCMSUSER_ROLE";
grant EXECUTE on "PCMSDATAUAT"."UNIX_TS_TO_DATE" to "PCMSUSER_ROLE" ;

