SPOOL C:\VERIFY.LOG;
SET ECHO ON;
--1) from QS_SYSTEMCONSTANT to APP_SUBCONTRACT_STANDARD_TERMS --;
select 'QS_SYSTEMCONSTANT' as from_table, count(1) from QSDATAPROD.QS_SYSTEMCONSTANT;
select 'APP_SUBCONTRACT_STANDARD_TERMS' as to_table, count(1) from PCMSDATAPROD.APP_SUBCONTRACT_STANDARD_TERMS;
select count(1) from PCMSDATAPROD.APP_SUBCONTRACT_STANDARD_TERMS minus select count(1) from QSDATAPROD.QS_SYSTEMCONSTANT;	
select 'No. of unmatched record:', count(1) as record from (select SYSTEM_CODE,COMPANY,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SCPAYMENTTERM,SCMAXRETPERCENT,SCINTERIMRETPERCENT,SCMOSRETPERCENT,RETENTIONTYPE,FINQS0REVIEW from PCMSDATAPROD.APP_SUBCONTRACT_STANDARD_TERMS
minus select SYSTEM_CODE,COMPANY,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SCPAYMENTTERM,SCMAXRETPERCENT,SCINTERIMRETPERCENT,SCMOSRETPERCENT,RETENTIONTYPE,FINQS0REVIEW from QSDATAPROD.QS_SYSTEMCONSTANT);
--2) from QS_TRANSITCODEMATCH to APP_TRANSIT_RESOURCE_CODE --;	
select 'QS_TRANSITCODEMATCH' as from_table, count(1) from QSDATAPROD.QS_TRANSITCODEMATCH;	
select 'APP_TRANSIT_RESOURCE_CODE' as to_table, count(1) from PCMSDATAPROD.APP_TRANSIT_RESOURCE_CODE;
select count(1) from PCMSDATAPROD.APP_TRANSIT_RESOURCE_CODE minus select count(1) from QSDATAPROD.QS_TRANSITCODEMATCH;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,MATCHINGTYPE,RESOURCECODE,OBJECTCODE,SUBSIDIARYCODE from PCMSDATAPROD.APP_TRANSIT_RESOURCE_CODE	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,MATCHINGTYPE,RESOURCECODE,OBJECTCODE,SUBSIDIARYCODE from QSDATAPROD.QS_TRANSITCODEMATCH);
--3) from QS_TRANSITUOMMATCH to APP_TRANSIT_UOM --;	
select 'QS_TRANSITUOMMATCH' as from_table, count(1) from QSDATAPROD.QS_TRANSITUOMMATCH;	
select 'APP_TRANSIT_UOM' as to_table, count(1) from PCMSDATAPROD.APP_TRANSIT_UOM;
select count(1) from PCMSDATAPROD.APP_TRANSIT_UOM minus select count(1) from QSDATAPROD.QS_TRANSITUOMMATCH;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,CAUSEWAYUOM,JDEUOM from PCMSDATAPROD.APP_TRANSIT_UOM	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,CAUSEWAYUOM,JDEUOM from QSDATAPROD.QS_TRANSITUOMMATCH);
--4) from QS_MAIN_CERTIFICATE_ATTACHMENT to ATTACH_MAIN_CERT --;	
select 'QS_MAIN_CERTIFICATE_ATTACHMENT' as from_table, count(1) from QSDATAPROD.QS_MAIN_CERTIFICATE_ATTACHMENT;	
select 'ATTACH_MAIN_CERT' as to_table, count(1) from PCMSDATAPROD.ATTACH_MAIN_CERT;
select count(1) from PCMSDATAPROD.ATTACH_MAIN_CERT	minus select count(1) from QSDATAPROD.QS_MAIN_CERTIFICATE_ATTACHMENT;	
select 'No. of unmatched record:', count(1) as record from (select MAIN_CERT_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from PCMSDATAPROD.ATTACH_MAIN_CERT	
minus select MAINCERTIFICATE_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from QSDATAPROD.QS_MAIN_CERTIFICATE_ATTACHMENT);
--5) from QS_SC_PAYMENT_ATTACHMENT to ATTACH_PAYMENT --;	
select 'QS_SC_PAYMENT_ATTACHMENT' as from_table, count(1) from QSDATAPROD.QS_SC_PAYMENT_ATTACHMENT;
select 'ATTACH_PAYMENT' as to_table, count(1) from PCMSDATAPROD.ATTACH_PAYMENT;
select count(1) from PCMSDATAPROD.ATTACH_PAYMENT minus select count(1) from QSDATAPROD.QS_SC_PAYMENT_ATTACHMENT;
select 'No. of unmatched record:', count(1) as record from (select PAYMENT_CERT_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from PCMSDATAPROD.ATTACH_PAYMENT	
minus select SCPAYMENTCERT_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from QSDATAPROD.QS_SC_PAYMENT_ATTACHMENT);
--6) from QS_REPACKAGING_ATTACHMENT to ATTACH_REPACKAGING --;	
select 'QS_REPACKAGING_ATTACHMENT' as from_table, count(1) from QSDATAPROD.QS_REPACKAGING_ATTACHMENT;
select 'ATTACH_REPACKAGING' as to_table, count(1) from PCMSDATAPROD.ATTACH_REPACKAGING;
select count(1) from PCMSDATAPROD.ATTACH_REPACKAGING minus select count(1) from QSDATAPROD.QS_REPACKAGING_ATTACHMENT;
select 'No. of unmatched record:', count(1) as record from (select REPACKAGING_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from PCMSDATAPROD.ATTACH_REPACKAGING	
minus select REPACKAGINGENTRY_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from QSDATAPROD.QS_REPACKAGING_ATTACHMENT);
--7) from QS_SC_ATTACHMENT to ATTACH_SUBCONTRACT --;	
select 'QS_SC_ATTACHMENT' as from_table, count(1) from QSDATAPROD.QS_SC_ATTACHMENT;	
select 'ATTACH_SUBCONTRACT' as to_table, count(1) from PCMSDATAPROD.ATTACH_SUBCONTRACT;
select count(1) from PCMSDATAPROD.ATTACH_SUBCONTRACT	minus select count(1) from QSDATAPROD.QS_SC_ATTACHMENT;	
select 'No. of unmatched record:', count(1) as record from (select SUBCONTRACT_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from PCMSDATAPROD.ATTACH_SUBCONTRACT	
minus select SCPACKAGE_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from QSDATAPROD.QS_SC_ATTACHMENT);
--8) from QS_SC_DETAILS_ATTACHMENT to ATTACH_SUBCONTRACT_DETAIL --;	
select 'QS_SC_DETAILS_ATTACHMENT' as from_table, count(1) from QSDATAPROD.QS_SC_DETAILS_ATTACHMENT;	
select 'ATTACH_SUBCONTRACT_DETAIL' as to_table, count(1) from PCMSDATAPROD.ATTACH_SUBCONTRACT_DETAIL;
select count(1) from PCMSDATAPROD.ATTACH_SUBCONTRACT_DETAIL minus select count(1) from QSDATAPROD.QS_SC_DETAILS_ATTACHMENT;	
select 'No. of unmatched record:', count(1) as record from (select SUBCONTRACT_DETAIL_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from PCMSDATAPROD.ATTACH_SUBCONTRACT_DETAIL
minus select SCDETAILS_ID,SEQUENCENO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,FILELINK,FILENAME,DOCUMENTTYPE,TEXTATTACHMENT from QSDATAPROD.QS_SC_DETAILS_ATTACHMENT);
--9) from QS_BILL to BPI_BILL --;	
select 'QS_BILL' as from_table, count(1) from QSDATAPROD.QS_BILL;	
select 'BPI_BILL' as to_table, count(1) from PCMSDATAPROD.BPI_BILL;
select count(1) from PCMSDATAPROD.BPI_BILL minus select count(1) from QSDATAPROD.QS_BILL;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,BILLNO,DESCRIPTION,SUBBILLNO,SECTIONNO,JOB_INFO_ID from PCMSDATAPROD.BPI_BILL	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,BILLNO,DESCRIPTION,SUBBILLNO,SECTIONNO,JOB_ID from QSDATAPROD.QS_BILL);
--10) from QS_BQITEM to BPI_ITEM --;	
select 'QS_BQITEM' as from_table, count(1) from QSDATAPROD.QS_BQITEM;	
select 'BPI_ITEM' as to_table, count(1) from PCMSDATAPROD.BPI_ITEM;
select count(1) from PCMSDATAPROD.BPI_ITEM minus select count(1) from QSDATAPROD.QS_BQITEM;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SECTION,SUBSECTION,ITEMNO,SEQUENCENO,SORTDISPLAYSEQNO,SUBSIDIARYCODE,BQTYPE,DESCRIPTION,QUANTITY,REMEASUREDQTY,UNIT,SELLINGRATE,COSTRATE,GENUINEMARKUPRATE,BQSTATUS,ACTIVITYCODE,CERTIFIEDPOSTEDQTY,CERTIFIEDCUMQTY,IPAGROUP,IPAPOSTEDQTY,IPACUMQTY,IVGROUP,IVPOSTEDQTY,IVCUMQTY,JOBNOREF,BILLNOREF,SUBBILLNOREF,SECTIONNOREF,PAGENOREF,BPI_PAGE_ID,IVPOSTEDAMOUNT,IVCUMAMOUNT from PCMSDATAPROD.BPI_ITEM	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SECTION,SUBSECTION,ITEMNO,SEQUENCENO,SORTDISPLAYSEQNO,SUBSIDIARYCODE,BQTYPE,DESCRIPTION,QUANTITY,REMEASUREDQTY,UNIT,SELLINGRATE,COSTRATE,GENUINEMARKUPRATE,BQSTATUS,ACTIVITYCODE,CERTIFIEDPOSTEDQTY,CERTIFIEDCUMQTY,IPAGROUP,IPAPOSTEDQTY,IPACUMQTY,IVGROUP,IVPOSTEDQTY,IVCUMQTY,JOBNOREF,BILLNOREF,SUBBILLNOREF,SECTIONNOREF,PAGENOREF,PAGE_ID,IVPOSTEDAMOUNT,IVCUMAMOUNT from QSDATAPROD.QS_BQITEM);
--11) from QS_RESOURCE to BPI_ITEM_RESOURCE --;	many variation**
select 'QS_RESOURCE' as from_table, count(1) from QSDATAPROD.QS_RESOURCE;	
select 'BPI_ITEM_RESOURCE' as to_table, count(1) from PCMSDATAPROD.BPI_ITEM_RESOURCE;
select count(1) from PCMSDATAPROD.BPI_ITEM_RESOURCE minus select count(1) from QSDATAPROD.QS_RESOURCE;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,RESOURCENO,SUBSIDIARYCODE,OBJECTCODE,RESOURCETYPE,DESCRIPTION,QUANTITY,UNIT,COSTRATE,MATERIALWASTAGE,PACKAGENO,PACKAGENATURE,PACKAGESTATUS,PACKAGETYPE,SPLITSTATUS,IVPOSTEDQTY,IVCUMQTY,IVPOSTEDAMOUNT,IVMOVEMENTAMOUNT,JOBNOREF,BILLNOREF,SUBBILLNOREF,SECTIONNOREF,PAGENOREF,ITEMNOREF,BPI_ITEM_ID,REMEASUREDFACTOR,IVCUMAMOUNT from PCMSDATAPROD.BPI_ITEM_RESOURCE	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,RESOURCENO,SUBSIDIARYCODE,OBJECTCODE,RESOURCETYPE,DESCRIPTION,QUANTITY,UNIT,COSTRATE,MATERIALWASTAGE,PACKAGENO,PACKAGENATURE,PACKAGESTATUS,PACKAGETYPE,SPLITSTATUS,IVPOSTEDQTY,IVCUMQTY,IVPOSTEDAMOUNT,IVMOVEMENTAMOUNT,JOBNOREF,BILLNOREF,SUBBILLNOREF,SECTIONNOREF,PAGENOREF,ITEMNOREF,BQITEM_ID,REMEASUREDFACTOR,IVCUMAMOUNT from QSDATAPROD.QS_RESOURCE);
--12) from QS_PAGE to BPI_PAGE --;	
select 'QS_PAGE' as from_table, count(1) from QSDATAPROD.QS_PAGE;	
select 'BPI_PAGE' as to_table, count(1) from PCMSDATAPROD.BPI_PAGE;
select count(1) from PCMSDATAPROD.BPI_PAGE minus select count(1) from QSDATAPROD.QS_PAGE;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,PAGENO,DESCRIPTION,BPI_BILL_ID from PCMSDATAPROD.BPI_PAGE	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,PAGENO,DESCRIPTION,BILL_ID from QSDATAPROD.QS_PAGE);
--13) from QS_IVPOSTING_HISTORY to IV_POSTING_HIST --;	
select 'QS_IVPOSTING_HISTORY' as from_table, count(1) from QSDATAPROD.QS_IVPOSTING_HISTORY;	
select 'IV_POSTING_HIST' as to_table, count(1) from PCMSDATAPROD.IV_POSTING_HIST;
select count(1) from PCMSDATAPROD.IV_POSTING_HIST minus select count(1) from QSDATAPROD.QS_IVPOSTING_HISTORY;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,RESOURCE_SUMMARY_ID,JOBNO,SUBSIDIARYCODE,OBJECTCODE,DESCRIPTION,UNIT,PACKAGENO,RATE,IVMOVEMENTAMOUNT,DOCUMENTNO,EDIBATCHNO from PCMSDATAPROD.IV_POSTING_HIST	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,RESOURCE_SUMMARY_ID,JOBNO,SUBSIDIARYCODE,OBJECTCODE,DESCRIPTION,UNIT,PACKAGENO,RATE,IVMOVEMENTAMOUNT,DOCUMENTNO,EDIBATCHNO from QSDATAPROD.QS_IVPOSTING_HISTORY);
--14) from QS_ACCOUNT_LEDGER to JDE_ACCOUNT_LEDGER --;	
select 'QS_ACCOUNT_LEDGER' as from_table, count(1) from QSDATAPROD.QS_ACCOUNT_LEDGER;	
select 'JDE_ACCOUNT_LEDGER' as to_table, count(1) from PCMSDATAPROD.JDE_ACCOUNT_LEDGER;
select count(1) from PCMSDATAPROD.JDE_ACCOUNT_LEDGER minus select count(1) from QSDATAPROD.QS_ACCOUNT_LEDGER;	
select 'No. of unmatched record:', count(1) as record from (select ID,JOB_NO,OBJECT_CODE,DESCRIPTION,SUBSIDIARY_CODE,SUBLEDGER,SUBLEDGER_TYPE,LEDGER_TYPE,FISCAL_YEAR,BEGIN_BALANCE,CUM_TO_DATE,CURRENT_YEAR_TOTAL,PERIOD01,PERIOD02,PERIOD03,PERIOD04,PERIOD05,PERIOD06,PERIOD07,PERIOD08,PERIOD09,PERIOD10,PERIOD11,PERIOD12,PERIOD13,PERIOD14,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS from PCMSDATAPROD.JDE_ACCOUNT_LEDGER	
minus select ENTRY_ID,JOB_NO,OBJECT_CODE,DESCRIPTION,SUBSIDIARY_CODE,SUBLEDGER,SUBLEDGER_TYPE,LEDGER_TYPE,FISCAL_YEAR,BEGIN_BALANCE,CUM_TO_DATE,CURRENT_YEAR_TOTAL,PERIOD01,PERIOD02,PERIOD03,PERIOD04,PERIOD05,PERIOD06,PERIOD07,PERIOD08,PERIOD09,PERIOD10,PERIOD11,PERIOD12,PERIOD13,PERIOD14,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS from QSDATAPROD.QS_ACCOUNT_LEDGER);
--15) from QS_JOB to JOB_INFO --;	
select 'QS_JOB' as from_table, count(1) from QSDATAPROD.QS_JOB;	
select 'JOB_INFO' as to_table, count(1) from PCMSDATAPROD.JOB_INFO;
select count(1) from PCMSDATAPROD.JOB_INFO minus select count(1) from QSDATAPROD.QS_JOB;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNO,DESCRIPTION,COMPANY,EMPLOYER,CONTRACTTYPE,DIVISION,DEPARTMENT,INTERNALJOB,SOLOJV,COMPLETIONSTATUS,INSURANCECAR,INSURANCEECI,INSURANCETPL,CLIENTCONTRACTNO,PARENTJOBNO,JVPARTNERNO,JVPERCENTAGE,ORIGINALCONTRACTVALUE,PROJECTEDCONTRACTVALUE,ORGINALNSCCONTRACTVALUE,TENDERGP,FORECASTENDYEAR,FORECASTENDPERIOD,MAXRETPERCENT,INTERIMRETPERCENT,MOSRETPERCENT,VALUEOFBSWORK,GROSSFLOORAREA,GROSSFLOORAREAUNIT,BILLINGCURRENCY,PAYMENTTERMFORNSC,DEFECTPROVISIONPERCENT,CPFAPPLICABLE,CPFINDEXNAME,CPFBASEYEAR,CPFBASEPERIOD,LEVYAPPLICABLE,LEVYCITAPERCENT,LEVYPCFBPERCENT,EXPECTEDPCCDATE,ACTUALPCCDATE,EXPECTEDMAKINGGOODDATE,ACTUALMAKINGGOODDATE,DEFECTLIABILITYPERIOD,DEFECTLISTISSUEDDATE,FINANCIALENDDATE,DATEFINALACSETTLEMENT,YEAROFCOMPLETION,BQFINALIZEDFLAG,MANUALINPUTSCWD,LEGACYJOB,CONVERSIONSTATUS,REPACKAGINGTYPE,FINQS0REVIEW from PCMSDATAPROD.JOB_INFO	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNO,DESCRIPTION,COMPANY,EMPLOYER,CONTRACTTYPE,DIVISION,DEPARTMENT,INTERNALJOB,SOLOJV,COMPLETIONSTATUS,INSURANCECAR,INSURANCEECI,INSURANCETPL,CLIENTCONTRACTNO,PARENTJOBNO,JVPARTNERNO,JVPERCENTAGE,ORIGINALCONTRACTVALUE,PROJECTEDCONTRACTVALUE,ORGINALNSCCONTRACTVALUE,TENDERGP,FORECASTENDYEAR,FORECASTENDPERIOD,MAXRETPERCENT,INTERIMRETPERCENT,MOSRETPERCENT,VALUEOFBSWORK,GROSSFLOORAREA,GROSSFLOORAREAUNIT,BILLINGCURRENCY,PAYMENTTERMFORNSC,DEFECTPROVISIONPERCENT,CPFAPPLICABLE,CPFINDEXNAME,CPFBASEYEAR,CPFBASEPERIOD,LEVYAPPLICABLE,LEVYCITAPERCENT,LEVYPCFBPERCENT,EXPECTEDPCCDATE,ACTUALPCCDATE,EXPECTEDMAKINGGOODDATE,ACTUALMAKINGGOODDATE,DEFECTLIABILITYPERIOD,DEFECTLISTISSUEDDATE,FINANCIALENDDATE,DATEFINALACSETTLEMENT,YEAROFCOMPLETION,BQFINALIZEDFLAG,MANUALINPUTSCWD,LEGACYJOB,CONVERSIONSTATUS,REPACKAGINGTYPE,FINQS0REVIEW from QSDATAPROD.QS_JOB);
--16) from QS_MAIN_CONTRACT_CERTIFICATE to MAIN_CERT --;	
select 'QS_MAIN_CONTRACT_CERTIFICATE' as from_table, count(1) from QSDATAPROD.QS_MAIN_CONTRACT_CERTIFICATE;	
select 'MAIN_CERT' as to_table, count(1) from PCMSDATAPROD.MAIN_CERT;
select count(1) from PCMSDATAPROD.MAIN_CERT minus select count(1) from QSDATAPROD.QS_MAIN_CONTRACT_CERTIFICATE;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNO,CERTNO,APPMAINCONTRACTORAMT,APPNSCNDSCAMT,APPMOSAMT,APPMAINCONTRACTORRET,APPMAINCONTRACTORRETREL,APPRETFORNSCNDSC,APPRETRELFORNSCNDSC,APPMOSRET,APPMOSRETREL,APPCCAMT,APPADJUSTMENTAMT,APPCPFAMT,CERTMAINCONTRACTORAMT,CERTNSCNDSCAMT,CERTMOSAMT,CERTMAINCONTRACTORRET,CERTMAINCONTRACTORRETREL,CERTRETFORNSCNDSC,CERTRETRELFORNSCNDSC,CERTMOSRET,CERTMOSRETREL,CERTCCAMT,CERTADJUSTMENTAMT,CERTCPFAMT,GSTRECEIVABLE,GSTPAYABLE,CERTIFICATESTATUS,ARDOCUMENTNO,IPA_SUBMISSION_DATE,IPASENTOUTDATE,CERT_ISSUE_DATE,CERT_AS_AT_DATE,CERTSTATUSCHANGEDATE,CERTDUEDATE,APPADVANCEPAYMENT,CERTADVANCEPAYMENT,CLIENTCERTNO,REMARK,ACTUAL_RECEIPT_DATE,TOTAL_RECEIPT_AMOUNT from PCMSDATAPROD.MAIN_CERT	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNO,CERTNO,APPMAINCONTRACTORAMT,APPNSCNDSCAMT,APPMOSAMT,APPMAINCONTRACTORRET,APPMAINCONTRACTORRETREL,APPRETFORNSCNDSC,APPRETRELFORNSCNDSC,APPMOSRET,APPMOSRETREL,APPCCAMT,APPADJUSTMENTAMT,APPCPFAMT,CERTMAINCONTRACTORAMT,CERTNSCNDSCAMT,CERTMOSAMT,CERTMAINCONTRACTORRET,CERTMAINCONTRACTORRETREL,CERTRETFORNSCNDSC,CERTRETRELFORNSCNDSC,CERTMOSRET,CERTMOSRETREL,CERTCCAMT,CERTADJUSTMENTAMT,CERTCPFAMT,GSTRECEIVABLE,GSTPAYABLE,CERTIFICATESTATUS,ARDOCUMENTNO,IPA_SUBMISSION_DATE,IPASENTOUTDATE,CERT_ISSUE_DATE,CERT_AS_AT_DATE,CERTSTATUSCHANGEDATE,CERTDUEDATE,APPADVANCEPAYMENT,CERTADVANCEPAYMENT,CLIENTCERTNO,REMARK,ACTUAL_RECEIPT_DATE,TOTAL_RECEIPT_AMOUNT from QSDATAPROD.QS_MAIN_CONTRACT_CERTIFICATE);
--17) from QS_MAIN_CONTRA_CHARGE to MAIN_CERT_CONTRA_CHARGE --;	
select 'QS_MAIN_CONTRA_CHARGE' as from_table, count(1) from QSDATAPROD.QS_MAIN_CONTRA_CHARGE;	
select 'MAIN_CERT_CONTRA_CHARGE' as to_table, count(1) from PCMSDATAPROD.MAIN_CERT_CONTRA_CHARGE;
select count(1) from PCMSDATAPROD.MAIN_CERT_CONTRA_CHARGE minus select count(1) from QSDATAPROD.QS_MAIN_CONTRA_CHARGE;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,POSTEDAMOUNT,CUMAMOUNT,OBJECTCODE,SUBSIDIARYCODE,MAIN_CERT_ID from PCMSDATAPROD.MAIN_CERT_CONTRA_CHARGE	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,POSTEDAMOUNT,CUMAMOUNT,OBJECTCODE,SUBSIDIARYCODE,MAINCERT_ID from QSDATAPROD.QS_MAIN_CONTRA_CHARGE);
--18) from QS_RETENTIONREL to MAIN_CERT_RETENTION_RELEASE --;	
select 'QS_RETENTIONREL' as from_table, count(1) from QSDATAPROD.QS_RETENTIONREL;	
select 'MAIN_CERT_RETENTION_RELEASE' as to_table, count(1) from PCMSDATAPROD.MAIN_CERT_RETENTION_RELEASE;
select count(1) from PCMSDATAPROD.MAIN_CERT_RETENTION_RELEASE minus select count(1) from QSDATAPROD.QS_RETENTIONREL;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNO,SEQUENCENO,MAINCERTNO,DUEDATE,FSTRELEASEAMT,ACTRELEASEAMT,RELEASEPERCENT,STATUS,CONTRACTUALDUEDATE from PCMSDATAPROD.MAIN_CERT_RETENTION_RELEASE	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNO,SEQUENCENO,MAINCERTNO,DUEDATE,FSTRELEASEAMT,ACTRELEASEAMT,RELEASEPERCENT,STATUS,CONTRACTUALDUEDATE from QSDATAPROD.QS_RETENTIONREL);
--19) from QS_SCPAYMENT_CERT to PAYMENT_CERT --;	
select 'QS_SCPAYMENT_CERT' as from_table, count(1) from QSDATAPROD.QS_SCPAYMENT_CERT;	
select 'PAYMENT_CERT' as to_table, count(1) from PCMSDATAPROD.PAYMENT_CERT;
select count(1) from PCMSDATAPROD.PAYMENT_CERT minus select count(1) from QSDATAPROD.QS_SCPAYMENT_CERT;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,PAYMENTCERTNO,PAYMENTSTATUS,MAINCONTRACTCERTNO,DUEDATE,ASATDATE,SCIPARECEIVEDDATE,CERTISSUEDATE,CERTAMOUNT,ADDENDUMAMOUNT,PAYMENTTYPE,REMEASUREDSCSUM,JOBNO,PACKAGENO,SUBCONTRACT_ID,DIRECTPAYMENT from PCMSDATAPROD.PAYMENT_CERT 
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,PAYMENTCERTNO,PAYMENTSTATUS,MAINCONTRACTCERTNO,DUEDATE,ASATDATE,SCIPARECEIVEDDATE,CERTISSUEDATE,CERTAMOUNT,ADDENDUMAMOUNT,PAYMENTTYPE,REMEASUREDSCSUM,JOBNO,PACKAGENO,SCPACKAGE_ID,DIRECTPAYMENT from QSDATAPROD.QS_SCPAYMENT_CERT);
--20) from QS_SCPAYMENT_DETAIL to PAYMENT_CERT_DETAIL --;	
select 'QS_SCPAYMENT_DETAIL' as from_table, count(1) from QSDATAPROD.QS_SCPAYMENT_DETAIL;	
select 'PAYMENT_CERT_DETAIL' as to_table, count(1) from PCMSDATAPROD.PAYMENT_CERT_DETAIL;
select count(1) from PCMSDATAPROD.PAYMENT_CERT_DETAIL minus select count(1) from QSDATAPROD.QS_SCPAYMENT_DETAIL;	
select 'No. of unmatched record:', count(1) as record from (select PAYMENT_CERT_ID,SCSEQNO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,PAYMENTCERTNO,LINETYPE,BILLITEM,MOVEMENTAMOUNT,CUMAMOUNT,OBJECTCODE,SUBSIDIARYCODE,SUBCONTRACT_DETAIL_ID from PCMSDATAPROD.PAYMENT_CERT_DETAIL	
minus select SCPAYMENTCERT_ID,SCSEQNO,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,PAYMENTCERTNO,LINETYPE,BILLITEM,MOVEMENTAMOUNT,CUMAMOUNT,OBJECTCODE,SUBSIDIARYCODE,SCDETAIL_ID from QSDATAPROD.QS_SCPAYMENT_DETAIL);
--21) from QS_SCDETAIL_PROV_HIST to PROVISION_POSTING_HIST --;	
select 'QS_SCDETAIL_PROV_HIST' as from_table, count(1) from QSDATAPROD.QS_SCDETAIL_PROV_HIST;	
select 'PROVISION_POSTING_HIST' as to_table, count(1) from PCMSDATAPROD.PROVISION_POSTING_HIST;
select count(1) from PCMSDATAPROD.PROVISION_POSTING_HIST minus select count(1) from QSDATAPROD.QS_SCDETAIL_PROV_HIST;	
select 'No. of unmatched record:', count(1) as record from (select SUBCONTRACT_DETAIL_ID,POSTEDYR,POSTEDMONTH,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,OBJECTCODE,SUBSIDIARYCODE,CERTPOSTEDAMOUNT,LIABILITIESCUMAMOUNT,CERTPOSTEDQTY,LIABILITIESCUMQTY,SCRATE,JOBNO,PACKAGENO from PCMSDATAPROD.PROVISION_POSTING_HIST	
minus select SCDETAIL_ID,POSTEDYR,POSTEDMONTH,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,OBJECTCODE,SUBSIDIARYCODE,CERTPOSTEDAMOUNT,LIABILITIESCUMAMOUNT,CERTPOSTEDQTY,LIABILITIESCUMQTY,SCRATE,JOBNO,PACKAGENO from QSDATAPROD.QS_SCDETAIL_PROV_HIST);
--22) from QS_REPACKAGING_ENTRY to REPACKAGING --;	
select 'QS_REPACKAGING_ENTRY' as from_table, count(1) from QSDATAPROD.QS_REPACKAGING_ENTRY;	
select 'REPACKAGING' as to_table, count(1) from PCMSDATAPROD.REPACKAGING;
select count(1) from PCMSDATAPROD.REPACKAGING minus select count(1) from QSDATAPROD.QS_REPACKAGING_ENTRY;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,REPACKAGINGVERSION,CREATEDATE,TOTALRESALLOWANCE,STATUS,REMARKS,JOB_INFO_ID from PCMSDATAPROD.REPACKAGING	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,REPACKAGINGVERSION,CREATEDATE,TOTALRESALLOWANCE,STATUS,REMARKS,JOB_ID from QSDATAPROD.QS_REPACKAGING_ENTRY);
--23) from QS_REPACKAGING_DETAIL to REPACKAGING_DETAIL --;	
select 'QS_REPACKAGING_DETAIL' as from_table, count(1) from QSDATAPROD.QS_REPACKAGING_DETAIL;	
select 'REPACKAGING_DETAIL' as to_table, count(1) from PCMSDATAPROD.REPACKAGING_DETAIL;
select count(1) from PCMSDATAPROD.REPACKAGING_DETAIL minus select count(1) from QSDATAPROD.QS_REPACKAGING_DETAIL;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,PACKAGENO,OBJECTCODE,SUBSIDIARYCODE,DESCRIPTION,UNIT,QUANTITY,RATE,AMOUNT,REPACKAGING_ID,RESOURCETYPE,RESOURCESUMMARYID,EXCLUDELEVY,EXCLUDEDEFECT from PCMSDATAPROD.REPACKAGING_DETAIL	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,PACKAGENO,OBJECTCODE,SUBSIDIARYCODE,DESCRIPTION,UNIT,QUANTITY,RATE,AMOUNT,REPACKAGINGENTRY_ID,RESOURCETYPE,RESOURCESUMMARYID,EXCLUDELEVY,EXCLUDEDEFECT from QSDATAPROD.QS_REPACKAGING_DETAIL);
--24) from QS_BQRESOURCE_SUMMARY to RESOURCE_SUMMARY --;	
select 'QS_BQRESOURCE_SUMMARY' as from_table, count(1) from QSDATAPROD.QS_BQRESOURCE_SUMMARY;	
select 'RESOURCE_SUMMARY' as to_table, count(1) from PCMSDATAPROD.RESOURCE_SUMMARY;	
select count(1) from PCMSDATAPROD.RESOURCE_SUMMARY minus select count(1) from QSDATAPROD.QS_BQRESOURCE_SUMMARY;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SUBSIDIARYCODE,OBJECTCODE,DESCRIPTION,UNIT,PACKAGENO,QUANTITY,RATE,IVPOSTEDAMOUNT,IVCUMAMOUNT,JOB_INFO_ID,SPLIT_FROM_ID,MERGE_TO_ID,RESOURCETYPE,EXCLUDELEVY,EXCLUDEDEFECT,FORIVROLLBACKONLY,FINALIZED from PCMSDATAPROD.RESOURCE_SUMMARY
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SUBSIDIARYCODE,OBJECTCODE,DESCRIPTION,UNIT,PACKAGENO,QUANTITY,RATE,IVPOSTEDAMOUNT,IVCUMAMOUNT,JOB_ID,SPLIT_FROM_ID,MERGE_TO_ID,RESOURCETYPE,EXCLUDELEVY,EXCLUDEDEFECT,FORIVROLLBACKONLY,FINALIZED from QSDATAPROD.QS_BQRESOURCE_SUMMARY);
--25) from QS_SC_PACKAGE to SUBCONTRACT --;	
select 'QS_SC_PACKAGE' as from_table, count(1) from QSDATAPROD.QS_SC_PACKAGE;	
select 'SUBCONTRACT' as to_table, count(1) from PCMSDATAPROD.SUBCONTRACT;	
select count(1) from PCMSDATAPROD.SUBCONTRACT minus select count(1) from QSDATAPROD.QS_SC_PACKAGE;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOB_INFO_ID,PACKAGENO,DESCRIPTION,PACKAGETYPE,VENDORNO,PACKAGESTATUS,SCSTATUS,SCNATURE,ORIGINALSCSUM,APPROVEDVOAMOUNT,REMEASUREDSCSUM,APPROVALROUTE,RETENTIONTERMS,MAXRETPERCENT,INTERIMRETPERENT,MOSRETPERENT,RETAMOUNT,ACCUMLATEDRET,RETRELEASE,PAYMENTINFO,PAYMENTCURRENCY,EXCHANGERATE,PAYMENTTERMS,SCTERM,CPFCALCULATION,CPFBASEPERIOD,CPFBASEYEAR,FORMOFSUBCONTRACT,INTERNALJOBNO,PAYMENTSTATUS,SUBMITTEDADDENDUM,LABOURINCLUDED,PLANTINCLUDED,MATERIALINCLUDED,SPLITTERMINATESTATUS,SCCREATEDDATE,LATESTADDENDUMVALUEUPDATEDDATE,FIRSTPAYMENTCERTISSUEDDATE,LASTPAYMENTCERTISSUEDDATE,FINALPAYMENTISSUEDDATE,SCAWARDAPPROVALREQUESTSENTDATE,SCAPPROVALDATE,TOTALPOSTEDCERTAMT,TOTALCUMCERTAMT,TOTALPOSTEDWDAMT,TOTALCUMWDAMT,TOTALCCPOSTEDCERTAMT,TOTALMOSPOSTEDCERTAMT,PAYMENTTERMSDESCRIPTION,REQUISITION_APPROVED_DATE,TA_APPROVED_DATE,PREAWARD_MEETING_DATE,LOA_SIGNED_DATE,SC_DOC_SCR_DATE,SC_DOC_LEGAL_DATE,WORK_COMMENCE_DATE,ONSITE_START_DATE from PCMSDATAPROD.SUBCONTRACT	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOB_ID,PACKAGENO,DESCRIPTION,PACKAGETYPE,VENDORNO,PACKAGESTATUS,SCSTATUS,SCNATURE,ORIGINALSCSUM,APPROVEDVOAMOUNT,REMEASUREDSCSUM,APPROVALROUTE,RETENTIONTERMS,MAXRETPERCENT,INTERIMRETPERENT,MOSRETPERENT,RETAMOUNT,ACCUMLATEDRET,RETRELEASE,PAYMENTINFO,PAYMENTCURRENCY,EXCHANGERATE,PAYMENTTERMS,SCTERM,CPFCALCULATION,CPFBASEPERIOD,CPFBASEYEAR,FORMOFSUBCONTRACT,INTERNALJOBNO,PAYMENTSTATUS,SUBMITTEDADDENDUM,LABOURINCLUDED,PLANTINCLUDED,MATERIALINCLUDED,SPLITTERMINATESTATUS,SCCREATEDDATE,LATESTADDENDUMVALUEUPDATEDDATE,FIRSTPAYMENTCERTISSUEDDATE,LASTPAYMENTCERTISSUEDDATE,FINALPAYMENTISSUEDDATE,SCAWARDAPPROVALREQUESTSENTDATE,SCAPPROVALDATE,TOTALPOSTEDCERTAMT,TOTALCUMCERTAMT,TOTALPOSTEDWDAMT,TOTALCUMWDAMT,TOTALCCPOSTEDCERTAMT,TOTALMOSPOSTEDCERTAMT,PAYMENTTERMSDESCRIPTION,REQUISITION_APPROVED_DATE,TA_APPROVED_DATE,PREAWARD_MEETING_DATE,LOA_SIGNED_DATE,SC_DOC_SCR_DATE,SC_DOC_LEGAL_DATE,WORK_COMMENCE_DATE,ONSITE_START_DATE from QSDATAPROD.QS_SC_PACKAGE);
--26) from QS_SC_DETAILS to SUBCONTRACT_DETAIL --;	
select 'SUBCONTRACT_DETAIL' as from_table, count(1) from PCMSDATAPROD.SUBCONTRACT_DETAIL;	
select 'QS_SC_DETAILS' as to_table, count(1) from QSDATAPROD.QS_SC_DETAILS;	
select count(1) from PCMSDATAPROD.SUBCONTRACT_DETAIL minus select count(1) from QSDATAPROD.QS_SC_DETAILS;	
select 'No. of unmatched record:', count(1) as record from (select ID,TYPE,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNO,SEQUENCENO,RESOURCENO,BILLITEM,DESCRIPTION,QUANTITY,SCRATE,OBJECTCODE,SUBSIDIARYCODE,LINETYPE,APPROVED,UNIT,SCREMARK,POSTEDCERTQTY,CUMCERTQTY,ORIGINALQTY,SUBCONTRACT_ID,COSTRATE,POSTEDWDQTY,CUMWDQTY,TOBEAPPROVEDQTY,NEWQTY,TOBEAPPROVEDRATE,CONTRACHARGESCNO,ALTOBJECTCODE,CORRSCLINESEQNO,TENDER_ID from PCMSDATAPROD.SUBCONTRACT_DETAIL	
minus select ID,TYPE,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNO,SEQUENCENO,RESOURCENO,BILLITEM,DESCRIPTION,QUANTITY,SCRATE,OBJECTCODE,SUBSIDIARYCODE,LINETYPE,APPROVED,UNIT,SCREMARK,POSTEDCERTQTY,CUMCERTQTY,ORIGINALQTY,SCPACKAGE_ID,COSTRATE,POSTEDWDQTY,CUMWDQTY,TOBEAPPROVEDQTY,NEWQTY,TOBEAPPROVEDRATE,CONTRACHARGESCNO,ALTOBJECTCODE,CORRSCLINESEQNO,TENDER_ANALYSIS_DETAIL_ID from QSDATAPROD.QS_SC_DETAILS);
--27) from QS_SC_PACKAGE_SNAPSHOT to SUBCONTRACT_SNAPSHOT --;	
select 'QS_SC_PACKAGE_SNAPSHOT' as from_table, count(1) from QSDATAPROD.QS_SC_PACKAGE_SNAPSHOT;	
select 'SUBCONTRACT_SNAPSHOT' as to_table, count(1) from PCMSDATAPROD.SUBCONTRACT_SNAPSHOT;	
select count(1) from PCMSDATAPROD.SUBCONTRACT_SNAPSHOT minus select count(1) from QSDATAPROD.QS_SC_PACKAGE_SNAPSHOT;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SUBCONTRACT_ID,JOB_INFO_ID,PACKAGENO,DESCRIPTION,PACKAGETYPE,VENDORNO,PACKAGESTATUS,SCSTATUS,SCNATURE,ORIGINALSCSUM,APPROVEDVOAMOUNT,REMEASUREDSCSUM,APPROVALROUTE,RETENTIONTERMS,MAXRETPERCENT,INTERIMRETPERENT,MOSRETPERENT,RETAMOUNT,ACCUMLATEDRET,RETRELEASE,PAYMENTINFO,PAYMENTCURRENCY,EXCHANGERATE,PAYMENTTERMS,SCTERM,CPFCALCULATION,CPFBASEPERIOD,CPFBASEYEAR,FORMOFSUBCONTRACT,INTERNALJOBNO,PAYMENTSTATUS,SUBMITTEDADDENDUM,LABOURINCLUDED,PLANTINCLUDED,MATERIALINCLUDED,SPLITTERMINATESTATUS,TOTALPOSTEDCERTAMT,TOTALCUMCERTAMT,TOTALPOSTEDWDAMT,TOTALCUMWDAMT,TOTALCCPOSTEDCERTAMT,TOTALMOSPOSTEDCERTAMT,PAYMENTTERMSDESCRIPTION,REQUISITION_APPROVED_DATE,TA_APPROVED_DATE,PREAWARD_MEETING_DATE,LOA_SIGNED_DATE,SC_DOC_SCR_DATE,SC_DOC_LEGAL_DATE,WORK_COMMENCE_DATE,ONSITE_START_DATE,SNAPSHOT_DATE from PCMSDATAPROD.SUBCONTRACT_SNAPSHOT	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,QS_SC_PACKAGE_ID,JOB_ID,PACKAGENO,DESCRIPTION,PACKAGETYPE,VENDORNO,PACKAGESTATUS,SCSTATUS,SCNATURE,ORIGINALSCSUM,APPROVEDVOAMOUNT,REMEASUREDSCSUM,APPROVALROUTE,RETENTIONTERMS,MAXRETPERCENT,INTERIMRETPERENT,MOSRETPERENT,RETAMOUNT,ACCUMLATEDRET,RETRELEASE,PAYMENTINFO,PAYMENTCURRENCY,EXCHANGERATE,PAYMENTTERMS,SCTERM,CPFCALCULATION,CPFBASEPERIOD,CPFBASEYEAR,FORMOFSUBCONTRACT,INTERNALJOBNO,PAYMENTSTATUS,SUBMITTEDADDENDUM,LABOURINCLUDED,PLANTINCLUDED,MATERIALINCLUDED,SPLITTERMINATESTATUS,TOTALPOSTEDCERTAMT,TOTALCUMCERTAMT,TOTALPOSTEDWDAMT,TOTALCUMWDAMT,TOTALCCPOSTEDCERTAMT,TOTALMOSPOSTEDCERTAMT,PAYMENTTERMSDESCRIPTION,REQUISITION_APPROVED_DATE,TA_APPROVED_DATE,PREAWARD_MEETING_DATE,LOA_SIGNED_DATE,SC_DOC_SCR_DATE,SC_DOC_LEGAL_DATE,WORK_COMMENCE_DATE,ONSITE_START_DATE,SNAPSHOT_DATE from QSDATAPROD.QS_SC_PACKAGE_SNAPSHOT);
--28) from QS_TENDERANALYSIS to TENDER --;	
select 'QS_TENDERANALYSIS' as from_table, count(1) from QSDATAPROD.QS_TENDERANALYSIS;	
select 'TENDER' as to_table, count(1) from PCMSDATAPROD.TENDER;	
select count(1) from PCMSDATAPROD.TENDER minus select count(1) from QSDATAPROD.QS_TENDERANALYSIS;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,VENDORNO,STATUS,CURRENCYCODE,EXCHANGERATE,BUDGETAMOUNT,JOBNO,PACKAGENO,SUBCONTRACT_ID from PCMSDATAPROD.TENDER	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,VENDORNO,STATUS,CURRENCYCODE,EXCHANGERATE,BUDGETAMOUNT,JOBNO,PACKAGENO,SCPACKAGE_ID from QSDATAPROD.QS_TENDERANALYSIS);
--29) from QS_TENDERANALYSISDETAIL to TENDER_DETAIL --;	
select 'QS_TENDERANALYSISDETAIL' as from_table, count(1) from QSDATAPROD.QS_TENDERANALYSISDETAIL;	
select 'TENDER_DETAIL' as to_table, count(1) from PCMSDATAPROD.TENDER_DETAIL;	
select count(1) from PCMSDATAPROD.TENDER_DETAIL minus select count(1) from QSDATAPROD.QS_TENDERANALYSISDETAIL;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SEQUENCENO,RESOURCENO,BILLITEM,DESCRIPTION,QUANTITY,RATE_BUDGET,RATE_SUBCONTRACT,OBJECTCODE,SUBSIDIARYCODE,LINETYPE,UNIT,REMARK,TENDER_ID from PCMSDATAPROD.TENDER_DETAIL	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SEQUENCENO,RESOURCENO,BILLITEM,DESCRIPTION,QUANTITY,FEEDBACKRATED,FEEDBACKRATEF,OBJECTCODE,SUBSIDIARYCODE,LINETYPE,UNIT,REMARK,TENDERANALYSIS_ID from QSDATAPROD.QS_TENDERANALYSISDETAIL);
--30) from QS_TRANSITHEADER to TRANSIT --;	
select 'QS_TRANSITHEADER' as from_table, count(1) from QSDATAPROD.QS_TRANSITHEADER;	
select 'TRANSIT' as to_table, count(1) from PCMSDATAPROD.TRANSIT;	
select count(1) from PCMSDATAPROD.TRANSIT minus select count(1) from QSDATAPROD.QS_TRANSITHEADER;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNUMBER,ESTIMATENO,JOBDESCRIPTION,COMPANY,STATUS,MATCHINGCODE from PCMSDATAPROD.TRANSIT	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,JOBNUMBER,ESTIMATENO,JOBDESCRIPTION,COMPANY,STATUS,MATCHINGCODE from QSDATAPROD.QS_TRANSITHEADER);
--31) from QS_TRANSITBQ to TRANSIT_BPI --;	
select 'QS_TRANSITBQ' as from_table, count(1) from QSDATAPROD.QS_TRANSITBQ;	
select 'TRANSIT_BPI' as to_table, count(1) from PCMSDATAPROD.TRANSIT_BPI;	
select count(1) from PCMSDATAPROD.TRANSIT_BPI minus select count(1) from QSDATAPROD.QS_TRANSITBQ;	
select 'No. of unmatched record:', count(1) as record from (select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SEQUENCENO,BILLNO,SUBBILLNO,PAGENO,ITEMNO,DESCRIPTION,QUANTITY,UNIT,SELLINGRATE,COSTRATE,VALUE,TRANSIT_ID from PCMSDATAPROD.TRANSIT_BPI	
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,SEQUENCENO,BILLNO,SUBBILLNO,PAGENO,ITEMNO,DESCRIPTION,QUANTITY,UNIT,SELLINGRATE,COSTRATE,VALUE,TRANSITHEADER_ID from QSDATAPROD.QS_TRANSITBQ);
--32) from QS_TRANSITRESOURCE to TRANSIT_RESOURCE --;	
select 'QS_TRANSITRESOURCE' as from_table, count(1) from QSDATAPROD.QS_TRANSITRESOURCE;	
select 'TRANSIT_RESOURCE' as to_table, count(1) from PCMSDATAPROD.TRANSIT_RESOURCE;	
select 'No. of unmatched record:', count(1) as record from (select count(1) from PCMSDATAPROD.TRANSIT_RESOURCE minus select count(1) from QSDATAPROD.QS_TRANSITRESOURCE);	
select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,RESOURCENO,RESOURCECODE,TYPE,DESCRIPTION,WASTE,TOTALQUANTITY,UNIT,RATE,VALUE,OBJECTCODE,SUBSIDIARYCODE,PACKAGENO,TRANSIT_BPI_ID from PCMSDATAPROD.TRANSIT_RESOURCE
minus select ID,LAST_MODIFIED_DATE,LAST_MODIFIED_USER,CREATED_DATE,CREATED_USER,SYSTEM_STATUS,RESOURCENO,RESOURCECODE,TYPE,DESCRIPTION,WASTE,TOTALQUANTITY,UNIT,RATE,VALUE,OBJECTCODE,SUBSIDIARYCODE,PACKAGENO,TRANSITBQ_ID from QSDATAPROD.QS_TRANSITRESOURCE;
SPOOL OFF;
