Insert into ACDATADEV.AC_ROLE (APPLICATIONCODE,ROLENAME,JOB,ROLEDESCRIPTION,TYPE,TEMPLATE,LASTMODIFYDATE,LASTMODIFYUSER) 
values('QS','ROLE_QS_DLOA','NA','edit site management and site supervision','F','N', sysdate,'IMS');

Insert into ACDATADEV.AC_ROLE (APPLICATIONCODE,ROLENAME,JOB,ROLEDESCRIPTION,TYPE,TEMPLATE,LASTMODIFYDATE,LASTMODIFYUSER) 
values('QS','ROLE_QS_SITE_ADM','NA','edit site supervision only','F','N', sysdate,'IMS');

--UserPreferenceController.obtainUserPreferenceByCurrentUser
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02160201' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02160201' );
--UserPreferenceController.setDefaultJobNo
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02160301' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02160301' );
--UserPreferenceController.getNotificationReadStatusByCurrentUser
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02160202' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02160202' );
--UserPreferenceController.updateNotificationReadStatusByCurrentUser
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02160302' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02160302' );
--SecurityController.getCurrentUser
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02150201' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02150201' );
--SystemController.getProperties 
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02140209' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02140209' );
--SystemController.obtainCacheKey 
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02140208' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02140208' );
--JobController.getJobList
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02040201' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02040201' );
--JobController.getJob
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02040204' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02040204' );
--JobController.updateJobInfo
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_DLOA', 'F02040301' );
insert into ACDATADEV.AC_FUNCTIONSECURITY ( APPLICATIONCODE, ACCESSRIGHT, STATUS, LASTMODIFYDATE, LASTMODIFYUSER, ROLENAME, FUNCTIONNAME ) 
values ( 'QS', 'ENABLE', 'A', sysdate, 'IMS', 'ROLE_QS_SITE_ADM', 'F02040301' );

