ALTER TABLE PCMSDATADEV.JOB_INFO 
ADD (
NAME_EXECUTIVE_DIRECTOR VARCHAR2(20 CHAR),
NAME_DIRECTOR VARCHAR2(20 CHAR),
NAME_DIRECT_SUPERVISOR_PIC VARCHAR2(20 CHAR),
NAME_PROJECT_IN_CHARGE VARCHAR2(20 CHAR),
NAME_COMMERCIAL_IN_CHARGE VARCHAR2(20 CHAR),
NAME_TEMP_WORK_CONTROLLER VARCHAR2(20 CHAR),
NAME_SAFETY_ENV_REP VARCHAR2(20 CHAR),
NAME_AUTHORIZED_PERSON VARCHAR2(20 CHAR),
NAME_SITE_ADMIN_1 VARCHAR2(20 CHAR),
NAME_SITE_ADMIN_2 VARCHAR2(20 CHAR),
NAME_SITE_MANAGEMENT_1 VARCHAR2(20 CHAR),
NAME_SITE_MANAGEMENT_2 VARCHAR2(20 CHAR),
NAME_SITE_MANAGEMENT_3 VARCHAR2(20 CHAR),
NAME_SITE_MANAGEMENT_4 VARCHAR2(20 CHAR),
NAME_SITE_SUPERVISION_1 VARCHAR2(20 CHAR),
NAME_SITE_SUPERVISION_2 VARCHAR2(20 CHAR),
NAME_SITE_SUPERVISION_3 VARCHAR2(20 CHAR),
NAME_SITE_SUPERVISION_4 VARCHAR2(20 CHAR)
);
ALTER TABLE PCMSDATADEV.JOB_INFO_AUDIT
ADD (
NAME_EXECUTIVE_DIRECTOR VARCHAR2(20 CHAR),
NAME_DIRECTOR VARCHAR2(20 CHAR),
NAME_DIRECT_SUPERVISOR_PIC VARCHAR2(20 CHAR),
NAME_PROJECT_IN_CHARGE VARCHAR2(20 CHAR),
NAME_COMMERCIAL_IN_CHARGE VARCHAR2(20 CHAR),
NAME_TEMP_WORK_CONTROLLER VARCHAR2(20 CHAR),
NAME_SAFETY_ENV_REP VARCHAR2(20 CHAR),
NAME_AUTHORIZED_PERSON VARCHAR2(20 CHAR),
NAME_SITE_ADMIN_1 VARCHAR2(20 CHAR),
NAME_SITE_ADMIN_2 VARCHAR2(20 CHAR),
NAME_SITE_MANAGEMENT_1 VARCHAR2(20 CHAR),
NAME_SITE_MANAGEMENT_2 VARCHAR2(20 CHAR),
NAME_SITE_MANAGEMENT_3 VARCHAR2(20 CHAR),
NAME_SITE_MANAGEMENT_4 VARCHAR2(20 CHAR),
NAME_SITE_SUPERVISION_1 VARCHAR2(20 CHAR),
NAME_SITE_SUPERVISION_2 VARCHAR2(20 CHAR),
NAME_SITE_SUPERVISION_3 VARCHAR2(20 CHAR),
NAME_SITE_SUPERVISION_4 VARCHAR2(20 CHAR)
);
