mainApp.controller('PaymentDetailsCtrl', ['$scope' , '$http', '$stateParams', '$cookieStore', 'paymentService', 'modalService', 'roundUtil', 
                                          function($scope , $http, $stateParams, $cookieStore, paymentService, modalService, roundUtil) {
	loadData();
	$scope.disableButtons = true;

	 $scope.edit = true;
	 $scope.canEdit = function() { 
		 return $scope.edit; 
	};
	  
	$scope.gridOptions = {
			enableFiltering: true,
			enableColumnResizing : true,
			enableGridMenu : true,
			enableRowSelection: true,
			enableSelectAll: true,
			//enableFullRowSelection: true,
			multiSelect: true,
			enableCellEditOnFocus : true,
			showGridFooter : false,
			//showColumnFooter : true,
			exporterMenuPdf: false,

			columnDefs: [
			             { field: 'lineType', enableCellEdit: false},
			             { field: 'billItem', enableCellEdit: false},
			             { field: 'movementAmount', cellClass: "grid-theme-blue", cellEditableCondition : $scope.canEdit,
			            	 /* cellClass: function(grid, row, col, rowRenderIndex, colRenderIndex) {
						          if (grid.getCellValue(row,col) != 'GR') {
						            return 'grid-theme-blue';
						          }
						        }*/
			             },
			             { field: 'cumAmount', displayName: "Cumulative Certified Amount", cellClass: "grid-theme-blue", cellEditableCondition : $scope.canEdit},
			             { field: 'postedAmount', displayName: "Posted Certified Amount", enableCellEdit: false},
			             { field: 'description', enableCellEdit: false},
			             { field: 'scSeqNo', displayName: "Sequence No", enableCellEdit: false},
			             { field: 'objectCode', enableCellEdit: false},
			             {field: 'subsidiaryCode', enableCellEdit: false}
			             ]
	};

	$scope.gridOptions.onRegisterApi = function (gridApi) {
		$scope.gridApi = gridApi;

		gridApi.edit.on.afterCellEdit($scope, function(rowEntity, colDef, newValue, oldValue) {
			if(rowEntity.lineType == "GR" || rowEntity.lineType == "GP" || rowEntity.lineType == "RT" || rowEntity.lineType == "MR"){
				modalService.open('md', 'view/message-modal.html', 'MessageModalCtrl', 'Warn', rowEntity.lineType+" is generated by system.");
			}
			if(colDef.name == "cumAmount"){
				rowEntity.cumAmount  = roundUtil.round(newValue, 2);
				rowEntity.movementAmount = roundUtil.round(rowEntity.cumAmount - rowEntity.postedAmount, 2);
			}
			if(colDef.name == "movementAmount"){
				rowEntity.movementAmount  = roundUtil.round(newValue, 2);
				rowEntity.cumAmount = roundUtil.round(rowEntity.movementAmount + rowEntity.postedAmount, 2);
			}
		});

	}
	

	function loadData() {
		if($cookieStore.get('paymentCertNo') != ""){
			getPaymentCert();
			loadPaymentDetails();
		}else
			modalService.open('md', 'view/message-modal.html', 'MessageModalCtrl', 'Warn', "Please create a payment certificate.");
	}
	
	function getPaymentCert() {
		paymentService.getPaymentCert($scope.jobNo, $scope.subcontractNo, $cookieStore.get('paymentCertNo'))
		.then(
				function( data ) {
					var payment = data;
					$scope.payment = data;

					if($scope.payment.paymentStatus == "PND")
						$scope.disableButtons = false;

				});
	}

	function loadPaymentDetails() {
		paymentService.getPaymentDetailList($scope.jobNo, $scope.subcontractNo, $cookieStore.get('paymentCertNo'))
		.then(
				function( data ) {
					angular.forEach(data, function(value, key){
						value.postedAmount = value.movementAmount+value.cumAmount;
						
						/*if(value.lineType == "GR")
							$scope.edit = false;
						else
							$scope.edit = true;*/
					});
					
					$scope.gridOptions.data = data;
					
					$scope.gridApi.grid.refresh();
				});
	}

}]);