package com.gammon.pcms.model.adl.id;
// Generated Jun 28, 2016 4:30:40 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.gammon.pcms.model.adl.AccountMaster;

/**
 * AccountBalanceAAJIId generated by hbm2java
 */
@Embeddable
public class AccountBalanceAAJIId implements Serializable {

	private static final long serialVersionUID = 6799860358690830105L;

	private AccountMaster accountMaster;
	private BigDecimal fiscalYear;
	private BigDecimal accountPeriod;

	public AccountBalanceAAJIId() {}

	public AccountBalanceAAJIId(AccountMaster accountMaster, BigDecimal fiscalYear, BigDecimal accountPeriod) {
		this.accountMaster = accountMaster;
		this.fiscalYear = fiscalYear;
		this.accountPeriod = accountPeriod;
	}

	@ManyToOne
	@JoinColumn(name = "ACCOUNT_CODE_KEY")
	public AccountMaster getAccountMaster() {
		return this.accountMaster;
	}

	public void setAccountMaster(AccountMaster accountMaster) {
		this.accountMaster = accountMaster;
	}

	@Column(name = "FISCAL_YEAR",
			precision = 22,
			scale = 0)
	public BigDecimal getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(BigDecimal fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "ACCOUNT_PERIOD",
			length = 2)
	public BigDecimal getAccountPeriod() {
		return this.accountPeriod;
	}

	public void setAccountPeriod(BigDecimal accountPeriod) {
		this.accountPeriod = accountPeriod;
	}

	@Override
	public String toString() {
		return "AccountBalanceAAJIId [accountMaster=" + accountMaster + ", fiscalYear=" + fiscalYear + ", accountPeriod=" + accountPeriod + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((accountMaster == null) ? 0 : accountMaster.hashCode());
		result = prime * result + ((accountPeriod == null) ? 0 : accountPeriod.hashCode());
		result = prime * result + ((fiscalYear == null) ? 0 : fiscalYear.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AccountBalanceAAJIId other = (AccountBalanceAAJIId) obj;
		if (accountMaster == null) {
			if (other.accountMaster != null)
				return false;
		} else if (!accountMaster.equals(other.accountMaster))
			return false;
		if (accountPeriod == null) {
			if (other.accountPeriod != null)
				return false;
		} else if (!accountPeriod.equals(other.accountPeriod))
			return false;
		if (fiscalYear == null) {
			if (other.fiscalYear != null)
				return false;
		} else if (!fiscalYear.equals(other.fiscalYear))
			return false;
		return true;
	}

}
