-- 2. Drop tables and sequences
BEGIN 
  FOR c IN (
    SELECT OBJECT_NAME FROM ALL_OBJECTS 
    WHERE OBJECT_TYPE = 'TABLE' 
    AND OWNER = 'PCMSDATAUAT' 
    AND OBJECT_NAME not like 'QS_%' 
    AND OBJECT_NAME not like 'QRTZ_%'
    )
    LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || c.OBJECT_NAME;
    END LOOP;
END;

BEGIN 
  FOR c IN (
    SELECT OBJECT_NAME FROM ALL_OBJECTS 
    WHERE OBJECT_TYPE = 'SEQUENCE' 
    AND OWNER = 'PCMSDATAUAT' 
    AND OBJECT_NAME not like 'QS_%'
	AND OBJECT_NAME != 'MAIN_CONTRACT_CERTIFICATE_SEQ'
    )
    LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || c.OBJECT_NAME;
    END LOOP;
END;

-- drop 13 unnecessary tables (originally have 47 tables)
drop table "PCMSDATAUAT".QS_TERM;
drop table "PCMSDATAUAT".QS_TERM_VARIANCES;
drop table "PCMSDATAUAT".QS_FORECAST;
drop table "PCMSDATAUAT".QS_OBJECT_SUBSIDIARY_RULE;
drop table "PCMSDATAUAT".QS_MSG_BOARD_ATTACHMENT;
drop table "PCMSDATAUAT".QS_MESSAGE_BOARD;

drop table "PCMSDATAUAT".QS_BQITEM_CONTROL;
drop table "PCMSDATAUAT".QS_RESOURCE_CONTROL;
drop table "PCMSDATAUAT".QS_BQRESOURCE_SUMMARY_CONTROL;
drop table "PCMSDATAUAT".QS_SCPACKAGE_CONTROL;
drop table "PCMSDATAUAT".QS_SC_DETAILS_CONTROL;
drop table "PCMSDATAUAT".QS_SCPAYMENT_CERT_CONTROL;
drop table "PCMSDATAUAT".QS_SCPAYMENT_DETAIL_CONTROL;
--34 tables starting with 'QS_*' remaining
--11 tables starting with 'QRTZ_*' remaining

-- drop 12 unncessary sequences (originally have 38 sequences)
drop sequence "PCMSDATAUAT".QS_TERM_VARIANCES_SEQ;
drop sequence "PCMSDATAUAT".QS_FORECAST_SEQ;
drop sequence "PCMSDATAUAT".QS_OBJECT_SUBSIDIARY_RULE_SEQ;
drop sequence "PCMSDATAUAT".QS_MSG_ATTACH_SEQ;
drop sequence "PCMSDATAUAT".QS_MESSAGE_BOARD_SEQ;

drop sequence "PCMSDATAUAT".QS_BQITEM_CONTROL_SEQ;
drop sequence "PCMSDATAUAT".QS_RESOURCE_CONTROL_SEQ;
drop sequence "PCMSDATAUAT".QS_BQRESOURCE_SUMMARY_CTL_SEQ;
drop sequence "PCMSDATAUAT".QS_SC_PACKAGE_CONTROL_SEQ;
drop sequence "PCMSDATAUAT".QS_SC_DETAILS_CONTROL_SEQ;
drop sequence "PCMSDATAUAT".QS_SC_PAYMENT_CERT_CONTROL_SEQ;
drop sequence "PCMSDATAUAT".QS_SC_PAYMENT_DETAIL_CTL_SEQ;
-- 26 sequences remaining
