--------------------------------------------------------
--  3. Rename Table, Sequence, Index & Constraint
--------------------------------------------------------
-- /* JOB */
rename "PCMSDATAUAT"."QS_JOB" to "PCMSDATAUAT"."JOB_INFO";
rename "PCMSDATAUAT"."QS_JOB_SEQ" to "PCMSDATAUAT"."JOB_INFO_SEQ";
alter index "PCMSDATAUAT"."QS_JOB_PK" rename to "PCMSDATAUAT"."JOB_INFO_PK";
alter table "PCMSDATAUAT"."JOB_INFO" rename constraint "QS_JOB_PK" to "JOB_INFO_PK";

rename "PCMSDATAUAT"."QS_BILL" to "PCMSDATAUAT"."BPI_BILL";
rename "PCMSDATAUAT"."QS_BILL_SEQ" to "PCMSDATAUAT"."BPI_BILL_SEQ";
alter index "PCMSDATAUAT"."QS_Bill_PK" rename to "PCMSDATAUAT"."BPI_BILL_PK";
alter table "PCMSDATAUAT"."BPI_BILL" rename constraint "QS_Bill_PK" to "BPI_BILL_PK";

rename "PCMSDATAUAT".QS_PAGE to "PCMSDATAUAT".BPI_PAGE;
rename "PCMSDATAUAT".QS_PAGE_SEQ to "PCMSDATAUAT".BPI_PAGE_SEQ;
alter index "PCMSDATAUAT"."QS_Page_PK" rename to "PCMSDATAUAT".BPI_PAGE_PK;
alter table "PCMSDATAUAT".BPI_PAGE rename constraint "QS_Page_PK" to BPI_PAGE_PK;

rename QS_BQITEM to BPI_ITEM;
rename QS_BQITEM_SEQ to BPI_ITEM_SEQ;
alter index "QS_BQItem_PK" rename to BPI_ITEM_PK;
alter table BPI_ITEM rename constraint "QS_BQItem_PK" to BPI_ITEM_PK;

rename QS_RESOURCE to BPI_ITEM_RESOURCE;
rename QS_RESOURCE_SEQ to BPI_ITEM_RESOURCE_SEQ;
alter index QS_RESOURCE_PK rename to BPI_ITEM_RESOURCE_PK;
alter table BPI_ITEM_RESOURCE rename constraint QS_RESOURCE_PK to BPI_ITEM_RESOURCE_PK;

-- /* TRANSIT */
rename QS_TRANSITHEADER to TRANSIT;
rename QS_TRANSITHEADER_SEQ to TRANSIT_SEQ;
alter index QS_TRANSITHEADER_PK rename to TRANSIT_PK;
alter table TRANSIT rename constraint QS_TRANSITHEADER_PK to TRANSIT_PK;

rename QS_TRANSITBQ to TRANSIT_BPI;
rename QS_TRANSITBQ_SEQ to TRANSIT_BPI_SEQ;
alter index "QS_TransitBQ_PK" rename to TRANSIT_BPI_PK;
alter table TRANSIT_BPI rename constraint "QS_TransitBQ_PK" to TRANSIT_BPI_PK;

rename QS_TRANSITRESOURCE to TRANSIT_RESOURCE;
rename QS_TRANSITRESOURCE_SEQ to TRANSIT_RESOURCE_SEQ;
alter index "QS_TransitResource_PK" rename to TRANSIT_RESOURCE_PK;
alter table TRANSIT_RESOURCE rename constraint "QS_TransitResource_PK" to TRANSIT_RESOURCE_PK;

/* TENDER ANALYSIS */
rename QS_TENDERANALYSIS to TENDER;
rename QS_TENDERANALYSIS_SEQ to TENDER_SEQ;
alter index "QS_TenderAnalysis_PK" rename to TENDER_PK;
alter table TENDER rename constraint "QS_TenderAnalysis_PK" to TENDER_PK;

rename QS_TENDERANALYSISDETAIL to TENDER_DETAIL;
rename QS_TENDERANALYSISDETAIL_SEQ to TENDER_DETAIL_SEQ;
alter index "QS_TenderAnalysisDetail_PK" rename to TENDER_DETAIL_PK;
alter table TENDER_DETAIL rename constraint "QS_TenderAnalysisDetail_PK" to TENDER_DETAIL_PK;

-- /* SUBCONTRACT */
rename QS_SC_PACKAGE to SUBCONTRACT;
rename QS_SC_PACKAGE_SEQ to SUBCONTRACT_SEQ;
alter index QS_SC_PACKAGE_PK rename to SUBCONTRACT_PK;
alter table SUBCONTRACT rename constraint QS_SC_PACKAGE_PK to SUBCONTRACT_PK;

rename QS_SC_PACKAGE_SNAPSHOT to SUBCONTRACT_SNAPSHOT;
rename QS_SC_PACKAGE_SNAPSHOT_SEQ to SUBCONTRACT_SNAPSHOT_SEQ;
alter index PK_SC_PACKAGE_SNAPSHOT rename to SUBCONTRACT_SNAPSHOT_PK;
alter table SUBCONTRACT_SNAPSHOT rename constraint PK_SC_PACKAGE_SNAPSHOT to SUBCONTRACT_SNAPSHOT_PK;

rename QS_SC_DETAILS to SUBCONTRACT_DETAIL;
rename QS_SC_DETAILS_SEQ to SUBCONTRACT_DETAIL_SEQ;
alter index QS_SC_DETAILS_PK rename to SUBCONTRACT_DETAIL_PK;
alter table SUBCONTRACT_DETAIL rename constraint QS_SC_DETAILS_PK to SUBCONTRACT_DETAIL_PK;

rename QS_SCWORKSCOPE to SUBCONTRACT_WORKSCOPE;
rename QS_SC_WORKSCOPE_SEQ to SUBCONTRACT_WORKSCOPE_SEQ;
alter index "QS_SCWorkScope_PK" rename to SUBCONTRACT_WORKSCOPE_PK;
alter table SUBCONTRACT_WORKSCOPE rename constraint "QS_SCWorkScope_PK" to SUBCONTRACT_WORKSCOPE_PK;

-- /* REPACKAGING */
rename QS_REPACKAGING_ENTRY to REPACKAGING;
rename QS_REPACKAGINGENTRY_SEQ to REPACKAGING_SEQ;
alter index QS_REPACKAGING_ENTRY_PK rename to REPACKAGING_PK;
alter table REPACKAGING rename constraint QS_REPACKAGING_ENTRY_PK to REPACKAGING_PK;

rename QS_REPACKAGING_DETAIL to REPACKAGING_DETAIL;
rename QS_REPACKAGINGDETAIL_SEQ to REPACKAGING_DETAIL_SEQ;
alter index QS_REPACKAGING_DETAIL_PK rename to REPACKAGING_DETAIL_PK;
alter table REPACKAGING_DETAIL rename constraint QS_REPACKAGING_DETAIL_PK to REPACKAGING_DETAIL_PK;

rename QS_BQRESOURCE_SUMMARY to RESOURCE_SUMMARY;
rename QS_BQRESOURCE_SUMMARY_SEQ to RESOURCE_SUMMARY_SEQ;
alter index QS_BQRESOURCE_SUMMARY_PK rename to RESOURCE_SUMMARY_PK;
alter table RESOURCE_SUMMARY rename constraint QS_BQRESOURCE_SUMMARY_PK to RESOURCE_SUMMARY_PK;

rename QS_AUDIT_RESOURCESUMMARY to RESOURCE_SUMMARY_AUDIT_CUSTOM;
rename QS_AUDIT_RESOURCESUMMARY_SEQ to RESOURCE_SUMMARY_AUDIT_CUS_SEQ;
alter index QS_AUDIT_RESOURCESUMMARY_PK rename to RESOURCE_SUMMARY_AUDIT_CUS_PK;
alter table RESOURCE_SUMMARY_AUDIT_CUSTOM rename constraint QS_AUDIT_RESOURCESUMMARY_PK to RESOURCE_SUMMARY_AUDIT_CUS_PK;

-- /* PAYMENT */
rename QS_SCPAYMENT_CERT to PAYMENT_CERT;
rename QS_SC_PAYMENT_CERT_SEQ to PAYMENT_CERT_SEQ;
alter index QS_SCPAYMENT_CERT_PK rename to PAYMENT_CERT_PK;
alter table PAYMENT_CERT rename constraint QS_SCPAYMENT_CERT_PK to PAYMENT_CERT_PK;

rename QS_SCPAYMENT_DETAIL to PAYMENT_CERT_DETAIL;
-- No sequence table
alter index QS_SCPAYMENT_DETAIL_PK rename to PAYMENT_CERT_DETAIL_PK;
alter table PAYMENT_CERT_DETAIL rename constraint QS_SCPAYMENT_DETAIL_PK to PAYMENT_CERT_DETAIL_PK;


-- /* MAIN CONTRACT CERTIFICATE */
rename QS_MAIN_CONTRACT_CERTIFICATE to MAIN_CERT;
rename MAIN_CONTRACT_CERTIFICATE_SEQ to MAIN_CERT_SEQ;
alter index QS_MAIN_CONTRACT_CERT_PK rename to MAIN_CERT_PK;
alter table MAIN_CERT rename constraint QS_MAIN_CONTRACT_CERT_PK to MAIN_CERT_PK;

rename QS_MAIN_CONTRA_CHARGE to MAIN_CERT_CONTRA_CHARGE;
rename QS_MAIN_CONTRA_CHARGE_SEQ to  MAIN_CERT_CONTRA_CHARGE_SEQ;
alter index QS_MAIN_CONTRA_CHARGE_PK rename to MAIN_CERT_CONTRA_CHARGE_PK;
alter table MAIN_CERT_CONTRA_CHARGE rename constraint QS_MAIN_CONTRA_CHARGE_PK to MAIN_CERT_CONTRA_CHARGE_PK;

rename QS_RETENTIONREL to MAIN_CERT_RETENTION_RELEASE;
rename QS_RETENTIONREL_SEQ to MAIN_CERT_RR_SEQ;
alter index QS_RETENTIONREL_PK rename to MAIN_CERT_RETENTION_RELEASE_PK;
alter table MAIN_CERT_RETENTION_RELEASE rename constraint QS_RETENTIONREL_PK to MAIN_CERT_RETENTION_RELEASE_PK;

-- /* PROVISION */
rename QS_SCDETAIL_PROV_HIST to PROVISION_POSTING_HIST;
--No sequence table
alter index QS_SCDETAIL_PROV_HIST_PK rename to PROVISION_POSTING_HIST_PK;
alter table PROVISION_POSTING_HIST rename constraint QS_SCDETAIL_PROV_HIST_PK to PROVISION_POSTING_HIST_PK;

-- /* IV */
rename QS_IVPOSTING_HISTORY to IV_POSTING_HIST;
rename QS_IVPOSTING_HISTORY_SEQ to IV_POSTING_HIST_SEQ;
alter index QS_IVPOSTING_HISTORY_PK rename to IV_POSTING_HIST_PK;
alter table IV_POSTING_HIST rename constraint QS_IVPOSTING_HISTORY_PK to IV_POSTING_HIST_PK;


-- /* ATTACHMENT */
rename QS_SC_ATTACHMENT to ATTACH_SUBCONTRACT;
alter index QS_SC_ATTACHMENT_PK rename to ATTACH_SUBCONTRACT_PK;
alter table ATTACH_SUBCONTRACT rename constraint QS_SC_ATTACHMENT_PK to ATTACH_SUBCONTRACT_PK;

rename QS_SC_DETAILS_ATTACHMENT to ATTACH_SUBCONTRACT_DETAIL;
alter index QS_SC_DETAILS_ATTACHMENT_PK rename to ATTACH_SUBCONTRACT_DETAIL_PK;
alter table ATTACH_SUBCONTRACT_DETAIL rename constraint QS_SC_DETAILS_ATTACHMENT_PK to ATTACH_SUBCONTRACT_DETAIL_PK;

rename QS_SC_PAYMENT_ATTACHMENT to ATTACH_PAYMENT;
alter index QS_SC_PAYMENT_ATTACHMENT_PK rename to ATTACH_PAYMENT_PK;
alter table ATTACH_PAYMENT rename constraint QS_SC_PAYMENT_ATTACHMENT_PK to ATTACH_PAYMENT_PK;

rename QS_MAIN_CERTIFICATE_ATTACHMENT to ATTACH_MAIN_CERT;
alter index QS_MAIN_CERTIFICATE_ATTACHMENT rename to ATTACH_MAIN_CERT_PK;
alter table ATTACH_MAIN_CERT rename constraint QS_MAIN_CERTIFICATE_ATTACHMENT to ATTACH_MAIN_CERT_PK;

rename QS_REPACKAGING_ATTACHMENT to ATTACH_REPACKAGING;
alter index SYS_C0020485 rename to ATTACH_REPACKAGING_PK;
alter table ATTACH_REPACKAGING rename constraint SYS_C0020485 to ATTACH_REPACKAGING_PK;

-- /* Application Tables */
rename QS_TRANSITUOMMATCH to APP_TRANSIT_UOM;
rename QS_TRANSITUOMMATCH_SEQ to APP_TRANSIT_UOM_SEQ;
alter index "QS_TransitUomMatch_PK" rename to APP_TRANSIT_UOM_PK;
alter table APP_TRANSIT_UOM rename constraint "QS_TransitUomMatch_PK" to APP_TRANSIT_UOM_PK;

rename QS_TRANSITCODEMATCH to APP_TRANSIT_RESOURCE_CODE;
rename QS_TRANSITCODEMATCH_SEQ to APP_TRANSIT_RESOURCE_CODE_SEQ;
alter index "QS_TransitCodeMatch_PK" rename to APP_TRANSIT_RESOURCE_CODE_PK;
alter table APP_TRANSIT_RESOURCE_CODE rename constraint "QS_TransitCodeMatch_PK" to APP_TRANSIT_RESOURCE_CODE_PK;

rename QS_SYSTEMCONSTANT to APP_SUBCONTRACT_STANDARD_TERMS;
-- No sequence tables
alter index "QS_SystemConstant_PK" rename to APP_SUBCONTRACT_STANDARD_T_PK;
alter table APP_SUBCONTRACT_STANDARD_TERMS rename constraint "QS_SystemConstant_PK" to APP_SUBCONTRACT_STANDARD_T_PK;

rename QS_ACCOUNT_LEDGER to JDE_ACCOUNT_LEDGER;
rename QS_ACCOUNT_LEDGER_SEQ to JDE_ACCOUNT_LEDGER_SEQ; 
alter index PK_ENTRY rename to JDE_ACCOUNT_LEDGER_PK;
alter table JDE_ACCOUNT_LEDGER rename constraint PK_ENTRY to JDE_ACCOUNT_LEDGER_PK;
