
ALTER TABLE PCMSDATAPROD.VARIATION_KPI ADD NUMBER_AGREED NUMBER(19,0) DEFAULT 0 NOT NULL;
ALTER TABLE PCMSDATAPROD.VARIATION_KPI ADD AMOUNT_AGREED NUMBER(19,4) DEFAULT 0 NOT NULL;
ALTER TABLE PCMSDATAPROD.VARIATION_KPI_AUDIT ADD NUMBER_AGREED NUMBER(19,0) DEFAULT 0 NOT NULL;
ALTER TABLE PCMSDATAPROD.VARIATION_KPI_AUDIT ADD AMOUNT_AGREED NUMBER(19,4) DEFAULT 0 NOT NULL;