

--P_GENERATE_SUBCONTRACTSNAPSHOT
grant EXECUTE on PCMSDATAPROD.P_GENERATE_SUBCONTRACTSNAPSHOT to PCMSUSER_ROLE;

--P_QS_JOB
grant EXECUTE on PCMSDATAPROD.P_QS_JOB to PCMSUSER_ROLE;
grant select, update On PRODDTA.F0006 to PCMSDATAPROD;

--P_F03B14_UPDATE_QS_MAIN_CERT
grant EXECUTE on PCMSDATAPROD.P_F03B14_UPDATE_QS_MAIN_CERT to PCMSUSER_ROLE;
grant select On PRODDTA.F03b11 to PCMSDATAPROD;
grant select On PRODDTA.F03b14 to PCMSDATAPROD;

--P_QS_UPDATE_F58001
grant EXECUTE on PCMSDATAPROD.P_QS_UPDATE_F58001 to PCMSUSER_ROLE;
grant select, update, insert On  PRODDTA.F58001 to PCMSDATAPROD;

--P_QS_UPDATE_F58011
grant EXECUTE on PCMSDATAPROD.P_QS_UPDATE_F58011 to PCMSUSER_ROLE;
grant select, update, insert On PRODDTA.F58011 to PCMSDATAPROD;

--P_AUDIT_HOUSEKEEP
grant EXECUTE on PCMSDATAPROD.P_AUDIT_HOUSEKEEP to PCMSUSER_ROLE;
grant EXECUTE on PCMSDATAPROD.UNIX_TS_TO_DATE to PCMSUSER_ROLE ;

